### ISSUE TITLE
Incorporate xdmod for usage monitoring

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#101]
This is not included in the submission script. @kenneth59715 what is the command that we should be including in the submission script for Comet?

**Comment by kenneth59715** [comment]
Documentation on gateway_submit_attributes is at:
https://www.xsede.org/ecosystem/science-gateways/gateways-for-developers
For comet, path to the command is:
/opt/ctss/gateway_submit_attributes/gateway_submit_attributes

**Comment by kenneth59715** [comment]
Looks like this is already in the submit script.  I can see two jobs in Oct 2018 for comet with
gateway attributes, but not for jobs on comet-gpu.  Will need to ask Trevor, Mahi, Amit C., 
Nancy

To print out usage info:
 xdusage -j -ja -s 2018-10-01 -e 2018-10-31 -p TG-MCB170058

**Comment by kenneth59715** [comment]
Amit Chourasia sends some clue:
Please try the following on Comet
$ module load  gateway-usage-reporting
$ gateway_submit_attributes --help

-resource automatically filled in for regular compute jobs

for gpu reporting you can set it to

-resource comet-gpu.sdsc.xsede

In general the resource names must match one of those listed under "XDCDB
ResourceName” column at following url
https://info.xsede.org/wh1/warehouse-views/v1/resources-xdcdb-active/?format=html

**Comment by kenneth59715** [comment]
I modified comet_relion_submit.py to have -resource comet-gpu.sdsc.xsede.  Looks like this
is used for all jobs.  output from gateway_submit_attributes says attributes loaded successfully.
Will need to check sometime later to see if the attributes are correctly linked to the job.

**Comment by kenneth59715** [comment]
Next day, I see a gpu job with attributes:
      job id=19918611 jobname=NGBW-JOB-RELION_2D_CLASS_COMET-E86A2586F4A449DA9AC63BEE8EDCA165 resource=comet-gpu.sdsc.xsede submit=2018-11-01@10:50:17 start=2018-11-01@11:07:45 end=2018-11-01@11:10:16 nodecount=1 processors=24 queue=gpu charge=1   
        job-attr id=19918611 name=http://globus.org/names/attribute/gram/audit_v1/gateway_user value=046f34e64f8b7dc1015072dc7aa30a1a@ucsd.edu@cosmic2.sdsc.edu

**Comment by kenneth59715** [comment]
Example cipres tgusage script is in:
\workspace\cipres-config\sdk\scripts\remote_resource\trestles\cipres-tgusage-new
-

**Comment by kenneth59715** [comment]
Ran usage.sh, and it looks like it imported job usage data and created reports.
This was in a set of test scripts in:
/projects/cosmic2/kennethtest/tgusage

I'm going to uncomment Mona's cron.

**Comment by mcianfrocco** [comment]
@kenneth59715 - is this working?

**Comment by kenneth59715** [comment]
I will need to check after I update tool-registry.cfg.xml and the submit script.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
