### ISSUE TITLE
login to gateway failed

### ISSUE THREAD

**Issue by kenneth59715** [cianfrocco-lab/COSMIC-CryoEM-Gateway#104]
The portal gave me this error:
An error has occurred. If you continue to have difficulty using the site, please report the error to us. 

And I see this in the log:
Oct 24 2018 07:44:14 [exec-6] INFO  -               NgbwSupport:1011   |
Redirect auth url:
https://auth.globus.org/v2/oauth2/authorize?client_id=db26c268-0210-43e8-8dfc-b5
85e0d08a21&redirect_uri=https://cosmic2.sdsc.edu:8443/gateway/authcallback.actio
n&response_type=code&scope=openid%20email%20profile%20urn:globus:auth:scope:tran
sfer.api.globus.org:all&state=2p5j10443gef1s5dgj31lq4gj3
Oct 24 2018 07:45:08 [xec-12] DEBUG -               NgbwSupport:1029   |
Mismatching Oauth States:
org.apache.oltu.oauth2.common.exception.OAuthSystemException: Mismatching Oauth
States
org.apache.oltu.oauth2.common.exception.OAuthSystemException: Mismatching Oauth
States
   at edu.sdsc.globusauth.action.AuthCallbackAction.globuslogin(AuthCallbackActi
on.java:383)

**Comment by monaw** [comment]
@kenneth59715 - can you try to login again?  I'm trying to debug this problem...

**Comment by kenneth59715** [comment]
Okay, I clicked login and it gave me the same error.

Kenneth

**Comment by monaw** [comment]
thanks, still debugging...

**Comment by cdesyoun** [comment]
@kenneth59715, what browser are you using?
I doubt you disable the session tracking.

Thanks,
Choonhan Youn

**Comment by kenneth59715** [comment]
Hi Choonhan,

 I am using Firefox.  How should I disable session tracking?

Kenneth

**Comment by cdesyoun** [comment]
I tested the firefox and safarion macbook pro. It went well.
If so, can you try other browsers, google chrome?

**Comment by cdesyoun** [comment]
can you use "New Private Window" option in the firefox? It is on the file menu.

**Comment by cdesyoun** [comment]
I think you need to look into your firefox's setting. I guess you may disable some cookies or sessions related.
If you could reset your firebox as the default, I think it may be worked!

Thanks,
Choonhan Youn

**Comment by kenneth59715** [comment]
Okay, I had to add cookie permission for a4.ucsd.edu and a5.ucsd.edu.

Kenneth

**Comment by kenneth59715** [comment]
Does anyone have a test job I can run?

Kenneth

**Comment by monaw** [comment]
@kenneth59715 - i'll send you test job in another email and closing this ticket

**Comment by monaw** [comment]
tech note:

In AuthCallbackAction.java, getSession() will be null and hence OauthConstants.OAUTH2_STATE also null if user has disabled cookies for session
