### ISSUE TITLE
Update struts version & redeploy

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#108]
After test jobs work, @kenneth59715 will update struts & redeploy the server.

**Comment by kenneth59715** [comment]
I updated portal/pom.xml to use struts 2.3.35, then did a clean and deploy.

**Comment by monaw** [comment]
@kenneth59715 - FYI, I've moved the file from /opt/apps/gateway/scigap_svn/portal/pom.xml (outside our git repo tree) to /opt/apps/gateway/COSMIC-CryoEM-Gateway/gateway_config/portal/pom.xml and created a link from the original location to the new location.  This way, we can have a copy in our git repo and track changes.  The link is needed in the original location by the deployment system.

**Comment by monaw** [comment]
I had some git issues trying to add the pom.xml after deleting the links but all looks ok now; hopefully i didn't munge anything...
