### ISSUE TITLE
Create staging server separate from production

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#109]
Need to stand up staging server so that we can make changes we don't effect user activity

**Comment by kenneth59715** [comment]
I want to also create a debugging area.  For the staging and debugging instance,
I'm going to need new mysql databases.  Mona, who is running our mysql databases?
Is it Mike Dwyer?

**Comment by mcianfrocco** [comment]
We only have one CPU on COSMIC2 (whereas NSG has 2) - need to investigate if we can run production vs. dev on same machine

**Comment by mcianfrocco** [comment]
Needed: 
-Another database
-Another VM just so it's ready to go in case we need it

**Comment by monaw** [comment]
@kenneth59715 - is the same cosmic2-gw account being used on the cosmic2dev also?  should we separate out account environment variables & settings for production and development into a file that can be 'source' to avoid possible problems of getting production & development confused?

**Comment by kenneth59715** [comment]
For deploying the test gateway on cosmic2dev, I have env variables in
/projects/cosmic2/kennethtest/dev/devenv
On Comet, I have a remote_scripts directory in
/home/cosmic2/gatewaydev

/home/cosmic2/gatewaydev/bashrc.dev is used to set the environment for
remote scripts.

The workspace is in /projects/cosmic2/gatewaydev/workspace

The tgusage directory is hardcoded into the scripts as '~tgusage',
so there is some potential for conflict there.  I have the cron
scripts running 30 min apart to try and avoid that.

Could you request different users on cosmic2dev and comet for
running the test stuff?

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
