### ISSUE TITLE
Data organization

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#116]
Hi @kenneth59715 & @monaw - 

A data organization question: when users are uploading their data via globus, all data goes into the same directory on our server. This happens even if the users are uploading data into different 'folders' on the cosmic2 portal. 

I'm afraid that this might lead to confusion of the backend data as some naming schemes are sort-of generic. Meaning that if a user has a dataset, they will: 

1) Create a project directory:  

MyDataSet/

2) Then create a sub folder within this for their data: 

MyDataSet/Movies

Then, after preprocessing and analysis using RELION, there will be output directories named: 

MyDataSet/Extract/job001/particles.star
MyDataSet/Extract/job002/particles.star

For these cases of particles.star shown here, the data lives within the same directory, meaning that the actual data for: 

MyDataSet/Extract/job001/particles.star
 
Would be the files found here:

MyDataSet/Extract/job001/Movies/

This is a long way of saying that there is a good chance that users may have directory structures named 'Extract/jobXXX' that may overlap **between different projects**. Therefore, if we could put uploaded data into different project folders this would solve this problem.

Does this make sense and would it be possible? 

Mike

**Comment by monaw** [comment]
let's discuss this in our next meeting on 11/8 if you two can make the call...
