### ISSUE TITLE
Create new tools for RELION3

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#117]
@monaw & @kenneth59715  - what are the steps needed to create a new tool? I want to add RELION3 to the tool list, for the same tasks, 2D & 3D classification, as well as 3D refinement.

I also want to try this myself so I can add notes to the manual for future additions. 

Thanks!

**Comment by kenneth59715** [comment]
Add a new too xml file.  It looks like these are in:
/opt/apps/gateway/scigap_svn/gateway_config/sdk/src/main/resources/pisexml

Then modify the tool-registry.cfg.xml file to have a stanza for the new tool.

/opt/apps/gateway/scigap_svn/gateway_config/sdk/src/main/resources/tool

Then deploy the gateway.  (At least that's how it works for NSG).

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
