### ISSUE TITLE
COSMIC2 is down

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#119]
Website is down as of 11/20 @ 11 pm

**Comment by kenneth59715** [comment]
I started it with 'startt'.  There was rebooting of the VMs by the cloud people
tonight.

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
