### ISSUE TITLE
Set user storage limit

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#120]
If user goes above storage limit of _____ GB, prevent user from uploading more data and notify gateway admins (Mike, Kenneth, Mona)

**Comment by mcianfrocco** [comment]
See also #53

**Comment by mcianfrocco** [comment]
Including @monaw to see if Globus can 'filter out' transfers that exceed a certain size.

**Comment by mcianfrocco** [comment]
Also would be preferred that this would check a database to give us control over who can upload data and how much.

**Comment by kenneth59715** [comment]
There are two settings in build.properties that allow setting a storage limit per user:
user.data.size.max=107374182400
user.data.size.warn=53687091200

If the max is exceeded, job submit is disabled.  The code in SessionManager.java
seems to take a possible override setting from the database user_preferences
table to allow select users to exceed the max.

**Comment by kenneth59715** [comment]
It looks like neither globus transfers nor browser upload are disabled when the limit is exceeded.
