### ISSUE TITLE
Task info not displaying help

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#124]
Just clicked 'information' link on task page and got a page not found error.

Example link: 

http://cosmic-cryoem.org/tools/relion_3d_refine_comet.html

**Comment by mcianfrocco** [comment]
Also applies to Create Task page 'Click for more info'

**Comment by kenneth59715** [comment]
Looks like this is in the static pages of cosmic-cryoem.org.  Can I get username and password
for wp-admin?

**Comment by mcianfrocco** [comment]
hi @kenneth59715 - I'm looking into this now. It turns out that the wordpress static site can make any URL we want, but it doesn't use .html as a suffix. Where would I remove this naming convention so that instead of looking for: 

http://cosmic-cryoem.org/tools/relion_3d_refine_comet.html

It is looking for: 

http://cosmic-cryoem.org/tools/relion_3d_refine_comet/

**Comment by kenneth59715** [comment]
I'm not sure about this.  I would guess you can change the href in
menu.jsp to
[http://cosmic-cryoem.org/tools/relion_3d_refine_comet](http://cosmic-cryoem.org/tools/relion_3d_refine_comet.html)

        <li>
          <a href="javascript:window.open('${staticSite}/docs/', 'cosmic2_help')"><span>Help</span></a>
        </li>

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
hi @kenneth59715 - where is menu.jsp located on the webserver? I can only find the main menu but not the ones for helping with tools (the "i" next to each tool): 

<img width="985" alt="menus" src="https://user-images.githubusercontent.com/1464469/52593125-34b5d200-2e16-11e9-8119-cf2284618a43.png">

**Comment by monaw** [comment]
/opt/apps/gateway/COSMIC-CryoEM-Gateway/gateway_config/portal/src/main/webapp/pages/common/menu.jsp

**Comment by mcianfrocco** [comment]
Thanks @monaw - yes this is menu.jsp. Do you know where the help is for a tool? The "i" in the image above?

**Comment by monaw** [comment]
I think /opt/apps/gateway/COSMIC-CryoEM-Gateway/gateway_config/portal/src/main/webapp/pages/user/tools.jsp

**Comment by mcianfrocco** [comment]
Thanks - that did it!

**Comment by mcianfrocco** [comment]
Hi @kenneth59715 - I changed this file: 

/opt/apps/gateway/COSMIC-CryoEM-Gateway/gateway_config/portal/src/main/webapp/pages/user/tools.jsp

To point to non-html static web pages for help. However, it appears this has been overwritten - did you change anything with this file?

**Comment by kenneth59715** [comment]
No, I haven't changed tools.jsp.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
How would this have changed, then? Is this generated during compiling?

**Comment by kenneth59715** [comment]
That file should not get changed during a clean and deplooy.
It should get copied into build, so the hierarchy under build gets
copied over each deploy, but gateway_config files should not get
changed.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
Appears to be working now...

**Comment by mcianfrocco** [comment]
Ah - there is also the 'Click for more info' button after a tool is selected. Needs to be updated too.

**Comment by mcianfrocco** [comment]
@monaw - I can't edit the file: 

gateway_config/portal/src/main/webapp/pages/user/task/taskSummary.jsp

Due to permissions issues since you edited it last. Can you open up the permissions on this for me?

**Comment by monaw** [comment]
Done; writable by cosmic2 group now.

**Comment by mcianfrocco** [comment]
I keep getting this file overwritten: 

/opt/apps/gateway/COSMIC-CryoEM-Gateway/gateway_config/portal/src/main/webapp/pages/user/tools.jsp

I think it might be because I didn't commit it to the github repo? I'll try again.

**Comment by mcianfrocco** [comment]
Seems ok now...not sure what's happening.
