### ISSUE TITLE
Create sub-directories based on user created folders

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#125]
Create folder within user's globus directory that mirrors 'folders' created on the COSMIC2 website, that way users put data into different folders on COSMIC2 to prevent data from being overwritten.

**Comment by mcianfrocco** [comment]
also assigning to myself -> make sure output files go back into this same user-named sub-folder

**Comment by monaw** [comment]
@mcianfrocco - ok, adding user's folder label to the storage path is now working; i tested transferring to and from the gateway storage and my tests are successful.  please confirm.

this does mean that previous upload data will no longer be "found" and the backend scripts will need to be updated with the new path.

**Comment by mcianfrocco** [comment]
that's awesome @monaw ! I'm excited to try it!

**Comment by mcianfrocco** [comment]
It worked for me - the new system will create directories on the server based on the folder name. 

In order to test it, I tried submitting a job and I got a command rendering error: 

Sat Feb 02 11:51:02 PST 2019 > COMMANDRENDERING : ERROR : NGBW-JOB-RELION_2D_CLASS_COMET-81027AFA42E0458A832B8412E75ADD9B : java.lang.RuntimeException: java.io.IOException: Cannot run program "piseEval": error=2, No such file or directory 

I'm now assuming that we aren't passing the new directory name along with the command. 

@monaw - can you give @kenneth59715 advice on where to start debugging this? I'd like to see if we can make progress in the meantime since you won't be back on COSMIC2 until the week of Feb 11 sometime.

**Comment by monaw** [comment]
sorry, just saw this...
@kenneth59715 - do you know what piseEval is doing?  will a change of directory impact its function?  i haven't dug into that step...

**Comment by monaw** [comment]
#153

**Comment by monaw** [comment]
same error as reported by @kenneth59715 in #153

**Comment by monaw** [comment]
looks like /projects/cosmic2/gateway/scripts/piseEval was changed on 2/12.  is someone working on it?

**Comment by kenneth59715** [comment]
I think a bunch of files in that directory get copied over during every deploy.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by monaw** [comment]
ah i forgot to use the new "build" alias and so it didn't get updated...my bad...

**Comment by monaw** [comment]
@mcianfrocco - can the comet_relion_submit.py backend script be modified to work with this:

```
relion_refine_mpi --angpix 1  --offset_step 2 --psi_step 10 --iter 25 --particle
_diameter 200 --K 50  --offset_range 5 --ctf  --strict_highres_exp -1 --tau2_fud
ge 2 --i "issue 125 b/monkey1/two.star"
```
Note the double quote around the --i parameter...

Right now, my test run is throwing the following error message:

> File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 528, in <module>
> relion_command,outdir,runhours,nodes,numiters,worksubdir,partition,gpuextra1,gpuextra2,gpuextra3,mpi_to_use=prepareRelionRun(args['commandline'])
>   File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 195, in prepareRelionRun
>     rlno1=open(starfilename,'r')
> IOError: [Errno 2] No such file or directory: '/projects/cosmic2/gateway/globus_transfers/mona/"issue'
>

**Comment by kenneth59715** [comment]
I put in some code to strip the double quotes before creating the path.
My job submit is getting past that error, but apparently one of my
globus transfer directories has disappeared, so my cloned task is
failing.  See if it works for you.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by monaw** [comment]
better, now looks like the script is only picking up part of the path due to spaces in folder name; so add double quote back to the full path maybe?

i am now getting this error:

```
[...]
Feb 14 2019 11:50:02 [read-6] WARN  -      SSHExecProcessWorker:284   [task=702, job=NGBW-JOB-RELION_2D_CLASS_COMET-8F34E5322670468D99FE13DD2AB56D8B] | Error submitting job: /projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-8F34E5322670468D99FE13DD2AB56D8B
. Traceback (most recent call last):
  File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 528, in <module>
    relion_command,outdir,runhours,nodes,numiters,worksubdir,partition,gpuextra1,gpuextra2,gpuextra3,mpi_to_use=prepareRelionRun(args['commandline'])
  File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 195, in prepareRelionRun
    rlno1=open(starfilename,'r')
IOError: [Errno 2] No such file or directory: '/projects/cosmic2/gateway/globus_transfers/mona/issue'
```

**Comment by kenneth59715** [comment]
Okay, let me work on this a bit this afternoon.  I think the problem
is that the inputline is getting split().  Instead, argparse should
probably be used.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by monaw** [comment]
@kenneth59715 - ok thanks; let me know when done and i can run another test...or you can test with a new Globus upload (your previous Globus data upload locations will no longer work...

**Comment by kenneth59715** [comment]
Mona,  you can give it a try now.  I put in some code to deal with the
spaces and double quotes.  My jobs are failing because my data
directories can't be found...

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by monaw** [comment]
@kenneth59715 - the transfer took quite awhile; finally submitted a relion 2d task and got a different error this time:

> [...]
> Feb 14 2019 20:31:54 [read-9] DEBUG -        AsyncProcessRunner:210   [task=725, job=NGBW-JOB-RELION_2D_CLASS_COMET-81347FB3461249A38D16B5F21A67ECC0] | Completed :  ssh -i /users/u2/cosmic2-gw/.ssh/id_rsa cosmic2@comet.sdsc.edu source /home/cosmic2/.bash_profile; export WB_JOBID=NGBW-JOB-RELION_2D_CLASS_COMET-81347FB3461249A38D16B5F21A67ECC0; cd /projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-81347FB3461249A38D16B5F21A67ECC0/; comet_relion_submit.py --account TG-MCB170058 --url '-k https://cosmic2.sdsc.edu:8443/gateway/taskupdate.action?taskId=725\&jh=NGBW-JOB-RELION_2D_CLASS_COMET-81347FB3461249A38D16B5F21A67ECC0' -- 'relion_refine_mpi --angpix 1 --offset_step 2 --psi_step 10 --iter 25 --particle_diameter 200 --K 10 --offset_range 5 --ctf --strict_highres_exp -1 --tau2_fudge 2 --i "issue 125 b/job009/particles.star" '
> Feb 14 2019 20:31:54 [read-9] DEBUG -      SSHExecProcessWorker:266   [task=725, job=NGBW-JOB-RELION_2D_CLASS_COMET-81347FB3461249A38D16B5F21A67ECC0] | Returned:/projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-81347FB3461249A38D16B5F21A67ECC0
> Could not find input star file
> 
> Feb 14 2019 20:31:54 [read-9] ERROR -      SSHExecProcessWorker:273   [task=725, job=NGBW-JOB-RELION_2D_CLASS_COMET-81347FB3461249A38D16B5F21A67ECC0] | Qsub returned exit status 0, but jobid can't be parsed from stdout.
> Feb 14 2019 20:31:54 [read-9] WARN  -      SSHExecProcessWorker:284   [task=725, job=NGBW-JOB-RELION_2D_CLASS_COMET-81347FB3461249A38D16B5F21A67ECC0] | Error submitting job: /projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-81347FB3461249A38D16B5F21A67ECC0
> Could not find input star file
> [...]

**Comment by mcianfrocco** [comment]
This appears to be due to incorrect symbolic linking of the user data directory. taking a look at this now.

@kenneth59715 - how are you able to submit jobs ? I am only getting piseval errors so I won't be able to debug this

**Comment by monaw** [comment]
@mcianfrocco - you still getting piseEval error?  Did you try it with a new Globus upload?  What's the piseEval error you are getting now?

**Comment by mcianfrocco** [comment]
ok - new globus upload fixed the problem. now I can help with the name space debugging
