### ISSUE TITLE
Globus upload path page 

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#127]
Need to clarify user design for globus upload. Specifically relating to the directory names that will be uploaded with the data.

Tabs? Tab for endpoints, tab for transfer?

**Comment by mcianfrocco** [comment]
Guide user to data -> first endpoint, then directory name, then sub-directory?

**Comment by monaw** [comment]
@monaw - review transfer function on Globus' sample gateway at https://mrdp.globus.org:5000

**Comment by monaw** [comment]
@mcianfrocco - ok, i think i have the Globus Transfer page in a good state for you to test.  Let me know what you think...

**Comment by monaw** [comment]
new Globus transfer UI page pushed out to production; see commits f882fba8ba9b29c255f97d793d2c2340ddd823a7 and b1ef423a828e8d65fae83d1d270c57f5e1430c2f
