### ISSUE TITLE
Globus transfer not working (yet says succeeded)

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#130]
Hi @monaw - I had an issue transferring files into the gateway today. I selected files to upload and the gateway said 'succeeded' and also created the directories on comet. Yet, there are no files on comet, and, appropriately so, no star files ingested into the data overview page.

Globus task IDs - 

Task ID: 971c9a88-0efd-11e9-9832-0262a1f2f698
Task ID: 2c657be2-0efd-11e9-9832-0262a1f2f698

Where would I find an error if there was one? I didn't see anything obvious in logs/gateway.log. 

Mike

**Comment by kenneth59715** [comment]
I think might be due to the test code I left running in production.  I did a clean and
deploy in the production repo and was able to do a globus transfer.  Could you try
the transfer again and see if it resolves this and #131 and #132?

**Comment by mcianfrocco** [comment]
I have both errors still, although your reboot fixed the listing of the uploaded 3D volume into the data listing page.
