### ISSUE TITLE
3D refinement job staging error

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#132]
Hi @monaw and @kenneth59715 - 

I got this error when I trying to submit a 3D refinement test. I'm not sure what the error means. I don't know if it is related to globus issue #130 at all.

Mike

```
Jan 02 2019 18:48:16 [read-1] ERROR -              TaskInitiate:249   [task=581, job=NGBW-JOB-RELION_3D_REFINE_COMET-0FC1E9BF78EE408CAB6B4710EAB99C45] | 
java.lang.Exception: User data item for parameter ref_ has a label that contains characters other than ascii letters, numbers, period and underscore
	at org.ngbw.sdk.tool.TaskInitiate.stageInputData(TaskInitiate.java:423)
	at org.ngbw.sdk.tool.TaskInitiate.stageAndRun(TaskInitiate.java:294)
	at org.ngbw.sdk.tool.TaskInitiate.runTask(TaskInitiate.java:234)
	at org.ngbw.utils.StageAndSubmitATask.stageAndSubmit(StageAndSubmitATask.java:37)
	at org.ngbw.utils.SubmitJob$ProcessRunningTask.run(SubmitJob.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mcianfrocco** [comment]
This error also shows up for input filename having '/' present: 

Thu Jan 03 12:53:23 PST 2019 > INPUTSTAGING : ERROR : NGBW-JOB-RELION_3D_REFINE_COMET-FD5E2CCCA5F34E04B57EBAE22A7D3D67 : java.lang.Exception: User data item for parameter infile_ has a label that contains characters other than ascii letters, numbers, period and underscore 

Where the infile_ was the following: 

`betagal/Extract/job080/particles.star`

**Comment by monaw** [comment]
@mcianfrocco - for 3d, the user will  usually upload the reference map separately right?  not part of their globus upload?

**Comment by monaw** [comment]
@mcianfrocco - i believe this is fixed.  i just ran a 3d refinement and my infile was "job180/particles.star".  the job ran successful (:  feel free to verify and reopen this issue if it is still not working for you

**Comment by mcianfrocco** [comment]
Hi @monaw - I just re-tried this with an input 3D volume file that had multiple '/' within it: 

T20S/InitialModel/job011/run_it300_class001.mrc
(File name on Cosmic2)

And got this staging error: 

Wed Jan 23 19:37:36 PST 2019 > INPUTSTAGING : ERROR : NGBW-JOB-RELION_3D_REFINE_COMET-ACB798DC921D4B78A6E4EF54F2E25A7B : com.trilead.ssh2.SFTPException: No such file (SSH_FX_NO_SUCH_FILE: A reference was made to a file which does not exist.)

**Comment by mcianfrocco** [comment]
And I should follow up to say that if I uploaded a 3D volume with the name: 

run_it300_class001.mrc
(file name on Cosmic2)

There was no problem staging.
