### ISSUE TITLE
Format for MRC 3D volumes 

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#133]
Change format of 3D volumes to 'MRC' instead of 'unknown'

**Comment by monaw** [comment]
done; the beta_gal_test_for_job180.mrc is the one added after i got this working:

![Screen Shot 2019-06-07 at 7 55 28 PM](https://user-images.githubusercontent.com/18472048/59141259-417aaa80-895e-11e9-83e2-f90986a6f469.png)
