### ISSUE TITLE
Remove 'Move' from data page

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#134]
For now - let's remove 'Move' selected data from Data page

**Comment by kenneth59715** [comment]
This looks like it's in dataList.jsp also.

**Comment by monaw** [comment]
@mcianfrocco - shall we also disable "Copy" feature as well?

**Comment by mcianfrocco** [comment]
Yes

**Comment by mcianfrocco** [comment]
@kenneth59715 - comment out move as well

**Comment by mcianfrocco** [comment]
Just noticed that the move button is still there - i will try to remove it

**Comment by mcianfrocco** [comment]
Hi @monaw & @kenneth59715 - I'm trying to remove the 'Move' option from the output task summary list page. Where is this page found? 

![testpage](https://user-images.githubusercontent.com/1464469/52986589-0b70e500-33c6-11e9-8b0b-967ea63cd7ae.png)

**Comment by kenneth59715** [comment]
Is this the View Task Output page?  I'm not seeing a Move button on there...

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by monaw** [comment]
hi @mcianfrocco - it is taskList.jsp; I just copied the one from the framework to gateway_config/portal/src/main/webapp/pages/user/task/ and you can edit that copy...

**Comment by monaw** [comment]
you probably already know this but just in case...don't delete the code...just comment out the section...we'll probably fix this feature for later release (:

**Comment by mcianfrocco** [comment]
Thanks @monaw - unfortunately I can't edit this file b/c of permissions either

**Comment by monaw** [comment]
oops sorry @mcianfrocco, just fixed permission on all files in that directory...

**Comment by mcianfrocco** [comment]
thanks!
