### ISSUE TITLE
job failure CUDA libs?

### ISSUE THREAD

**Issue by kenneth59715** [cianfrocco-lab/COSMIC-CryoEM-Gateway#136]
ERROR: CUDA driver version is insufficient for CUDA runtime version in /share/apps/gpu/relion2/downloads/relion/src/ml_optimiser_mpi.cpp at line 212 (error-code 35)
[comet-30-18.sdsc.edu:mpi_rank_1][error_sighandler] Caught error: Segmentation fault (signal 11)
ERROR: CUDA driver version is insufficient for CUDA runtime version in /share/apps/gpu/relion2/downloads/relion/src/ml_optimiser_mpi.cpp at line 212 (error-code 35)
[comet-30-18.sdsc.edu:mpi_rank_2][error_sighandler] Caught error: Segmentation fault (signal 11)
ERROR: CUDA driver version is insufficient for CUDA runtime version in /share/apps/gpu/relion2/downloads/relion/src/ml_optimiser_mpi.cpp at line 212 (error-code 35)
[comet-30-18.sdsc.edu:mpi_rank_3][error_sighandler] Caught error: Segmentation fault (signal 11)

**Comment by mcianfrocco** [comment]
What job did this come from? My jobs have been running fine for 2D classification.

**Comment by mcianfrocco** [comment]
Nevermind - found the issue !

**Comment by mcianfrocco** [comment]
Submitted help ticket to XSEDE - seems to be something changed on Comet

**Comment by mcianfrocco** [comment]
Fixed - was issue when submission script was sourcing .bashrc in home directory which was no compatible with new RELION version.
