### ISSUE TITLE
 Wordpress access to gateway team

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#138]
Get kenneth access to wordpress static webpage

**Comment by mcianfrocco** [comment]
@kenneth59715 - I just invited you to the wordpress site. let me know when you create an account & can login.

**Comment by kenneth59715** [comment]
The activation link failed for me.  It says I don't have permission to access
wp-activate.php.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
Ok - I'll have to dig into this further. In the meantime, please send any update requests to the static site through me.
