### ISSUE TITLE
globus uploaded data items not showing up

### ISSUE THREAD

**Issue by kenneth59715** [cianfrocco-lab/COSMIC-CryoEM-Gateway#139]
I tried an upload from SDSC Data Oasis of an Extract directory.  Transfer succeeded,
but data list does not show it.

**Comment by monaw** [comment]
hi @kenneth59715 - was there any error?  did you get an email about the transfer?

**Comment by mcianfrocco** [comment]
@kenneth59715 - what was in the directory you were trying to upload?

**Comment by kenneth59715** [comment]
I tried Extract and Extract.newversion.  Both succeeded, but do not
show up in the data list.  Does it work for you still?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
Extract from the globus endpoint?

**Comment by kenneth59715** [comment]
I downloaded from the globus endpoint to my directory in SDSC data Oasis, then uploaded from there to
Cosmic2 on comet.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
New items do show up, but duplicates of old items do not.  Is that how it should be?

**Comment by monaw** [comment]
@kenneth59715 - I'm not clear on your question...please elaborate...picture might be helpful...

**Comment by mcianfrocco** [comment]
Hi @kenneth59715 - is this still a problem for you? if not, I'm going to close this. I haven't had any issues.

**Comment by kenneth59715** [comment]
Right, please close.  Thanks, Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
