### ISSUE TITLE
purge oauth_consumer.properties from git repo & history?

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#140]
looks like the oath_consumer.properties was checked into GitHub; there are 2 copies:

1. gateway_config/portal/src/main/resources/oauth_consumer.properties
2. globus_sources/portal/src/main/resources/oauth_consumer.properties

i feel these information is sensitive and would like to purge them from the git repo & history.

Here is a link that may be helpful, https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by mcianfrocco** [comment]
Should get new credentials and update as we are probably needing a new credential setup @kenneth59715

**Comment by kenneth59715** [comment]
https://docs.globus.org/api/auth/developer-guide/#register-app
