### ISSUE TITLE
Add Initial Model to Task List

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#144]
Add RELION Initial model as a new tool to task list

**Comment by mcianfrocco** [comment]
hi @kenneth59715 - I created a new tool within the pisxml directory:

pisexml/relion_3d_initial_model_comet.xml

And added it into the tool registry: 

tool/tool-registry.cfg.xml -> starting at line 83

Then I cleaned & redeployed the webserver and it finished out errors ( as far as I can tell). I see the tool in the tool registry list, but the tool font size is all caps and is missing the description: 

![example](https://user-images.githubusercontent.com/1464469/51795483-2038cf00-21b2-11e9-9f90-9b1729113555.png)

"RELION_3D_INITIAL_MODEL" should be written "Relion 3D initial model calculation" based on the title that I put into the .xml tool file  relion_3d_initial_model_comet.xml. Can you see what formatting mistake I made to result in this error? I copied the relion_2d_class_comet.xml tool to use as a template for this so I'm confused why it looks different. 

thanks for your help!

**Comment by kenneth59715** [comment]
I'll take a look.

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
@kenneth59715  - I've updated the pisxml file for this tool, so I was going to test it out, but I got this error when I clicked the  'Set parameters' button for this task:

![initial_model_error](https://user-images.githubusercontent.com/1464469/51883036-37f98a00-234f-11e9-80d6-06492e992514.png)

What linked information is the new tool missing?

**Comment by kenneth59715** [comment]
Okay, please try that tool now.  There are weird, undocumented rules
for specifying tool labels.  I made Tool id and configfile in tool-registry.cfg.xml
match the pisexml filename and the command in the pisexml file.

            <Tool id="RELION_3D_INITIAL_MODEL_COMET" name="Relion 3D initial model calculation on Comet"
                toolresource="COMET"
                configfile="pisexml/relion_3d_initial_model_comet.xml"

  <command>relion_3d_initial_model_comet</command>

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
Thanks @kenneth59715 - that fixed it!
