### ISSUE TITLE
Parameter checking error for 3D initial model task

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#145]
Hi @kenneth59715 - I'm running into a weird problem with the new tool that you helped fix. Now that I can select the tool, when I try to save the parameters, I get this message: 

"Please enter an integer > 0 for the initial resolution for calculing initial model"

This is weird because the default entry is already satisfying this requirement, as the default is 35. 

Here is the entry for the parameter in the pisxml file: 

```
<parameter type="Integer" ismandatory="1">
        <name>sgd_ini_res</name>
        <attributes>
            <group>1</group>
            <prompt>Initial resolution (A) (sgd_ini_resol)</prompt>
            <format>
                <language>perl</language>
                <code>"--sgd_ini_resol $value"</code>
            </format>
            <vdef>
                <value>35</value>
            </vdef>
            <ctrls>
                <ctrl>
                    <message>Please enter an integer > 0 for the initial resolution for calculating initial model</message>
                    <language>perl</language>
                    <code>$sgd_ini_resol &lt; 1</code>
                </ctrl>
            </ctrls>
        </attributes>
    </parameter>
```
Can you see anything that could be wrong? Something is confused as no matter what entry I put into the parameter, I get this message. If you'd like to test this out, all you need to do is select a data file and then go to 3D initial model task. Here are the parameters that you can use:

![iniital_model](https://user-images.githubusercontent.com/1464469/51993622-3af29880-247d-11e9-96ae-551bf1eb5a53.png)

Mike

**Comment by kenneth59715** [comment]
Okay, please try it now.  I changed the pisexml file, and it saves the parameters.
I think the perl code that does the integer check needs the variable name to
match the variable name at the start of that section:

    <parameter type="Integer" ismandatory="1">
        <name>sgd_fin_sub</name>
        <attributes>
            <group>1</group>
            <prompt>Final mini-batch size (sgd_fin_subset)</prompt>
            <format>
                <language>perl</language>
                <code>"--sgd_fin_subset $value"</code>
            </format>
            <vdef>
                <value>500</value>
            </vdef>
            <ctrls>
                <ctrl>
                    <message>Please enter an integer > 0 for the final subset size</message>
                    <language>perl</language>
                    <code>$sgd_fin_sub &lt; 1</code>
                </ctrl>
            </ctrls>
        </attributes>
    </parameter>

*** 379,385 ****
                  <ctrl>
                      <message>Please enter an integer > 0 for the final subset size</message>
                      <language>perl</language>
!                     <code>$sgd_fin_subset &lt; 1</code>
                  </ctrl>
              </ctrls>
          </attributes>
--- 379,385 ----
                  <ctrl>
                      <message>Please enter an integer > 0 for the final subset size</message>
                      <language>perl</language>
!                     <code>$sgd_fin_sub &lt; 1</code>
                  </ctrl>
              </ctrls>
          </attributes>

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
Oh I see - thanks @kenneth59715 ! Fixed!
