### ISSUE TITLE
Renew XSEDE credential/certificate

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#150]
Our current credential expires on 3/17/19

**Comment by monaw** [comment]
@kenneth59715 - info from Choonhan on the credential renewal isn't too clear but it is at https://github.com/cianfrocco-lab/COSMIC-CryoEM-Gateway/issues/93.  FYI, I just submitted a ticket to XSEDE to ask how to check and renew and I will add this info to the management doc...

**Comment by monaw** [comment]
ok, it turns out that it is the web server's SSL certificate that needs to be renewed, not Globus or XSEDE.  Choonhan has made the update and it seems to be working.  Our new certificate expires on 3/2/20:

![screen shot 2019-02-28 at 9 59 26 am](https://user-images.githubusercontent.com/18472048/53591875-ea3c9100-3b49-11e9-9cd3-77a1397ff91c.png)

**Comment by mcianfrocco** [comment]
This is related to this problem on the gateway? 

<img width="913" alt="screen shot 2019-02-28 at 3 55 45 pm" src="https://user-images.githubusercontent.com/1464469/53597913-58e11500-3b71-11e9-90f0-c0cef4b0cff3.png">

**Comment by monaw** [comment]
Yes I think they are related.  Choonhan has offered to help us resolve this issue and is working on it...

**Comment by monaw** [comment]
Choonhan updated the community account's DN in the XSEDE portal (profile -> "Manage DNs").  He is able to see and transfer files but Mike and Mona are not...

**Comment by monaw** [comment]
Choonhan worked with SDSC's Scott Sakai to update certificate & DN entries.  We had compounding problems where the SDSC data mover went down, got updated and also Kenneth's identity was somehow linked with the community account (now separated).

I did a Globus transfer test via gateway and it worked

**Comment by mcianfrocco** [comment]
Yes - globus is working for me too ! Closing this issue for now...
