### ISSUE TITLE
Create 'known issues' button at top of task bar 

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#151]
To link users to 'bugs' within Beta-testing milestone for easy information access. 

URL: 
https://github.com/cianfrocco-lab/COSMIC-CryoEM-Gateway/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22COSMIC2+beta+release%22+label%3Abug

**Comment by mcianfrocco** [comment]
Hi @kenneth59715 - can you point me to where I can add a new menu option on the cosmic2 webserver? This can let me point users to a web page with a current list of known issues if/when problems come up.

**Comment by kenneth59715** [comment]
Not sure where this would be.  It might be under portal/src/main/webapp/pages/user
in *.jsp files.  That's where I changed data list number of items menu pulldown
and removed the move data item option.  What page do you want a new
menu on?  If there is a corresponding jsp file, that might be where to insert
a menu.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
hi @kenneth59715 - I want the name to be a hyperlink in this task/menu listing at the top of every page: 

<img width="1006" alt="cosmic" src="https://user-images.githubusercontent.com/1464469/52385908-b2ae5d80-2a51-11e9-813c-d34ba5ec6ef6.png">

Similar to how the 'Help' menu links out to the static website for user issues. 

So, a more refined question would be, where is the 'Help' button in the backend code? And can I just add another button that says 'Known issues' to link out to a static page?

**Comment by mcianfrocco** [comment]
Hi @kenneth59715 - I found the file that lays out the menu: 

gateway_config.current/portal/src/main/webapp/pages/common/menu.jsp 

Do I edit this directly or do I edit this somewhere else (and then it gets compiled into this location)?

**Comment by kenneth59715** [comment]
I think it is gateway_config, rather than gateway_config.current?  When the build directory
is populated, the files in scigap_svn get copied into build, then whatever is in the gateway_config
heirarchy gets copied over that.  You should modify menu.jsp in gateway_config.

**Comment by mcianfrocco** [comment]
Thanks @kenneth59715 - that did it.
