### ISSUE TITLE
no piseEval file found

### ISSUE THREAD

**Issue by kenneth59715** [cianfrocco-lab/COSMIC-CryoEM-Gateway#153]
I've seen this twice:
Tue Feb 12 09:56:40 PST 2019 > QUEUE : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-0EEC8264E5F8430388DE345F4E06AC88 : Added to run queue.
Tue Feb 12 09:56:43 PST 2019 > COMMANDRENDERING : ERROR : NGBW-JOB-RELION_2D_CLASS_COMET-0EEC8264E5F8430388DE345F4E06AC88 : java.lang.RuntimeException: java.io.IOException: Cannot run program "piseEval": error=2, No such file or directory 

might be due to automounter not having /projects/cosmic2 mounted?
(gatewayVE)[cosmic2-gw@cosmic2 scigap_svn]$ which piseEval
/projects/cosmic2/gateway/scripts/piseEval
(gatewayVE)[cosmic2-gw@cosmic2 scigap_svn]$ ls -l /projects/cosmic2/gateway/scripts/piseEval
-rwxr-xr-x 1 cosmic2-gw cosmic2 388 Feb 12 10:00 /projects/cosmic2/gateway/scripts/piseEval

Workaround is to do an ls -l of that file before use.  Not sure where that would go in the web
app.

**Comment by monaw** [comment]
@kenneth59715 - auto mounter should mount the filesystem when referenced...can you check with the Comet admin (Mahidhar) on the auto mount setup and see if they have seen these issues and have a work-around suggestion at the system level?

**Comment by kenneth59715** [comment]
I'm not sure if this is an automounter issue.  I think it's on cosmic2.sdsc.edu rather
than comet...

**Comment by mcianfrocco** [comment]
I'd like to re-up this issue - I'm currently having this issue on the gateway. I can't submit any job right now - can either of you @monaw & @kenneth59715 ?

**Comment by kenneth59715** [comment]
It's failing for me also.  I do see piseEval, so I don't think it's an automounter issue:
(gatewayVE)[cosmic2-gw@cosmic2 logs]$ ls -l /projects/cosmic2/gateway/scripts/piseEval
-rwxr-xr-x 1 cosmic2-gw cosmic2 388 Feb 13 17:49 /projects/cosmic2/gateway/scripts/piseEval
(gatewayVE)[cosmic2-gw@cosmic2 logs]$

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
It looks like PATH is getting set in .bash_profile rather than .bashrc.
.bash_profile gets run in login shells only.  Is someone starting or
deploying the gateway in a non-login shell?

http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
Ah, I think I know the answer to that: cron!  The current
portal process was started by cron at 0435.  It probably
does not have a path to piseEval.  We could try putting the
export PATH settings in .bashrc or we could put them in a
script for cron to use to restart the gateway.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
Looks like there is a commented-out PATH line in crontab:
#PATH=/usr/bin:/bin:/projects/cosmic2/gateway/scripts

I'm going to uncomment that and try a gateway restart from cron
to see if that works to allow job submit.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
setting PATH in crontab is not working.  Maybe we need a setenv.sh in CATALINA_HOME.
Mona, can you allow group write in
/usr/share/tomcat/apache-tomcat-7.0.70/bin?

**Comment by monaw** [comment]
@kenneth59715 - done.  though i don't understand why piseEval worked before and is not now...adding the user folder path should not impact piseEval...i think something else may be the cause...but let's try your fix kenneth and see how it goes...

**Comment by monaw** [comment]
ah, your problem is with cron, not job submission...different issue than 125...

i thought piseEval is only used for job task creation?  i'm curious what's the cron job doing with it?

**Comment by kenneth59715** [comment]
cron is doing a restart of tomcat every morning at 0435, so I needed to
set up a $CATALINA_HOME/bin/setenv.sh file to set the PATH, so
the web app could find piseEval.  I think that's working now.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
I just tried to resubmit a job and got the piseval error @kenneth59715

**Comment by kenneth59715** [comment]
Okay, I am getting that also right now.  I'll investigate.  It was working for
a while yesterday.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
It's working for me now.  I think this is an issue with the daemon restart
entry in the crontab.  Cron clears out the PATH variable, so it's necessary to
explicitly put in paths for piseEval.  These would be /usr/bin:/usr/local/bin:/projects/cosmic2/gateway/scripts
That should be possible by setting PATH in crontab, but for some reason that was not working.
For daemon startups, I use /opt/apps/gateway/scigap_svn/gateway_config/sdk/scripts/daemonshut
In that script, I added a PATH setting line.

I tested out of cron, and it appears to work now, so I think it will work for the daily cron
restart.

**Comment by monaw** [comment]
hi guys, i believe this issue is specifically for running piseEval from the cron job; NOT user job submission on the gateway...that's a separate issue #125

**Comment by mcianfrocco** [comment]
ah ok

**Comment by kenneth59715** [comment]
cron does a restart of the submitJobD, so after a cron restart of that daemon,
all user job submissions will be affected by the cron environment seen by that
daemon.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
