### ISSUE TITLE
comet_relion_submit.py : directory name with space

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#154]
Can comet_relion_submit.py be made to handle directory names that contain a space?  Maybe quoting the path?  This is the error I'm getting for such a case:

Feb 13 2019 09:50:38 [read-1] WARN  -      SSHExecProcessWorker:284   [task=677, job=NGBW-JOB-RELION_2D_CLASS_COMET-1ED76343A7E64782B845801D9DC5F2CC] | Error submitting job: /projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-1ED76343A7E64782B845801D9DC5F2CC
. Traceback (most recent call last):
  File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 528, in <module>
    relion_command,outdir,runhours,nodes,numiters,worksubdir,partition,gpuextra1,gpuextra2,gpuextra3,mpi_to_use=prepareRelionRun(args['commandline'])
  File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 195, in prepareRelionRun
    rlno1=open(starfilename,'r')
IOError: [Errno 2] No such file or directory: '/projects/cosmic2/gateway/globus_transfers/mona/globus'

**Comment by kenneth59715** [comment]
NSG ran into this.  I put in single quotes when using the dirname, like:
        os.system("/projects/ps-nsg/home/nsguser/ngbw/contrib/scripts/makelib.sh '%s' %s" % (modeldir,nrnivmodl))
modeldir is a string that may have spaces.

But the directory below does not have a space in it.  And I would expect
the open() function to be able to already handle direnames with spaces...

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
Yes I think we can make it work.

We just need it passed along with the data file - last I checked part of the Problem was that comet relion submit didn't get the user folder name (unless you fixed that)?

**Comment by monaw** [comment]
@mcianfrocco - yes the folder name is passed in the --i parameter now; see issue #125

**Comment by kenneth59715** [comment]
I was able to submit a job with spaced directory successfully:
Feb 15 2019 09:48:08 [read-2] DEBUG -      SSHExecProcessWorker:262   [task=733, job=NGBW-JOB-RELION_2D_CLASS_COMET-32B521A1C0AF496BB32820AAED848859] | Running ssh command: source /home/cosmic2/.bash_profile; export WB_JOBID=NGBW-JOB-RELION_2D_CLASS_COMET-32B521A1C0AF496BB32820AAED848859; cd /projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-32B521A1C0AF496BB32820AAED848859/; comet_relion_submit.py --account TG-MCB170058 --url '-k https://cosmic2.sdsc.edu:8443/gateway/taskupdate.action?taskId=733\&jh=NGBW-JOB-RELION_2D_CLASS_COMET-32B521A1C0AF496BB32820AAED848859' --  'relion_refine_mpi --angpix 3.68  --offset_step 2 --psi_step 10 --iter 10 --particle_diameter 200 --K 15  --offset_range 5 --ctf  --strict_highres_exp -1 --tau2_fudge 2 --i "test1/Extract space/job007/particles.star" '

I was trying to get it to use the 'Extract space' directory as input.  The job dir has links for both
'Extract' and 'Extract space' directories.  The batch_commad.run for the job looks like
it's using 'Extract':

mpirun -np 4 relion_refine_mpi --o Class2D_cosmic/job001/run --angpix 3.68 --off
set_step 2 --psi_step 10 --iter 10 --particle_diameter 200 --K 15 --offset_range
 5 --ctf --strict_highres_exp -1 --tau2_fudge 2 --i Extract/job007/particles.sta
r --j 6 --gpu 0,1,2,3 >>stdout.txt 2>>stderr.txt

**Comment by monaw** [comment]
@kenneth59715 - so is it using the wrong directory?  Maybe move the "Extract/" out to make sure it is using "Extract space/"?

**Comment by kenneth59715** [comment]
Mona,

 I guess my question is why does the link to 'Extract' get created and why
does that directory get put into the batch_command.run file, instead of
'Extract space'?

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
let's talk about this - comet_relion_submit is mostly my doing so I can help with this.

**Comment by monaw** [comment]
looks like that file is generated by comet_relion_submit.py...

**Comment by mcianfrocco** [comment]
*should* be fixed now - closing for now.

**Comment by mcianfrocco** [comment]
hi @monaw & @kenneth59715 - right now this works only for 2D classification, as the quotes around the folder name are only being passed from 2D classification jobs. For 3D initial model, 3D classification and 3D refinement do not have quotes around the --i input directory.

Where did you add this into the code so we can update this?

**Comment by monaw** [comment]
ok, i just added the same fix to the other tool's XML files and the double quote should be going through now; sorry i forgot to do that earlier...

however, in my testing, i spotted another problem with the reference file; opened a new issue (#161) for that...
