### ISSUE TITLE
Globus link for activating endpoint link deprecated

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#155]
Sometimes users have to re-activate Globus endpoints (normal behavior).

<img width="890" alt="screen shot 2019-02-14 at 9 53 07 am" src="https://user-images.githubusercontent.com/1464469/52794763-7759f300-303e-11e9-9814-ddb28119f89c.png">

I had to do so today and when I followed the link into Globus, I saw this message saying that our links will be discontinued April 2019:

<img width="1008" alt="screen shot 2019-02-14 at 9 54 43 am" src="https://user-images.githubusercontent.com/1464469/52794836-96588500-303e-11e9-8f33-222009db8019.png">

The URL that they want us to use is: 

https://app.globus.org/file-manager?origin_id=3ccf082a-6b2b-11e8-92ba-0a6d4e044368

Whereas our gateway generated this link: 

https://www.globus.org/app/endpoints/3ccf082a-6b2b-11e8-92ba-0a6d4e044368/activate

@monaw - can you update this?

**Comment by monaw** [comment]
@mcianfrocco - ok, i've updated that; can you re-test it?  i am not getting that message so I can't test...

**Comment by monaw** [comment]
i just saw that kenneth got that message and it seems the URL is now updated.  let me know if you find otherwise...

**Comment by mcianfrocco** [comment]
Ok - thanks @monaw. Closing the issue for now
