### ISSUE TITLE
Add folder naming rules 

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#157]
Reject 'bad' folder names: 

Restrict to alphabet, space, numbers, dashes, underscore 

1) Don't allow folder to be created 
2) add information to folder create page that this is the naming scheme

**Comment by monaw** [comment]
@mcianfrocco - what do you think of this text:

![screen shot 2019-02-15 at 12 51 27 pm](https://user-images.githubusercontent.com/18472048/52883615-7dc09b80-3120-11e9-8137-298fffde9728.png)

**Comment by mcianfrocco** [comment]
Looks good - could you change the language to be: "Only alpha-numeric, underscore, hyphen, and spaces are allowed as a folder label" ?

**Comment by monaw** [comment]
Done:

![screen shot 2019-02-16 at 2 17 15 pm](https://user-images.githubusercontent.com/18472048/52905882-a1a1e100-31f5-11e9-9ac2-9980e270395d.png)

**Comment by mcianfrocco** [comment]
Great !
