### ISSUE TITLE
Remove all data from gateway after specified time period

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#163]
Write script that will remove all files with timestamps older than a specified time period. To start, let's do 14 days.

We will need to update each users total storage on the gateway after their data is cleaned out.

**Comment by kenneth59715** [comment]
Are these the files in:
/projects/cosmic2/gateway/globus_transfers

Where is users total storage displayed on the gateway?  How does this get updated?

I do have the datawarn.py script that checks for user total storage in globus_transfers,
but that is not integrated with the gateway.

**Comment by monaw** [comment]
Both in /projects/cosmic2/gateway/globus_transfers/ and the original CIPRES document location in /projects/cosmic2/gateway/db_documents/.  User total can be seen in the gateway at the top of the folder listing on the left side:

![screen shot 2019-02-21 at 9 38 05 am](https://user-images.githubusercontent.com/18472048/53189519-8dc2fa00-35bc-11e9-871f-82bd4de6a4d6.png)

Apparently I've hit our current 100 GB limit.

The total is from a query to the database...see User.queryDataSize() for the actual query which Paul Hoover helped me with.

**Comment by kenneth59715** [comment]
There is a script, sdk/scripts/deleteTasksD, that calls java code in
org/ngbw/utils/DeleteTasks.java
This deletes tasks and associated data, including files in db_documents
from REST users over a certain age.  I think this could be adapted to
portal tasks.  According to Paul Hoover:
Hi Kenneth,

I don't think there are any issues in using the same strategy to delete tasks   
and data for portal users. There isn't any particular requirement for 
synchronizing task and data deletion. Deleting a task deletes everything
associated with that task, i.e. inputs, outputs, log messages, etc. Files in
db_documents are deleted if no documents reference them.

- Paul

Looks like we can set age in days and restOnly to false to get portal tasks and
data purged:
#!/bin/bash

HOST=`hostname`
COMMAND=org.ngbw.utils.DeleteTasks

STDOUT=stdout=${logs}/deleteTasksD.log
LOG=log4j.configuration=deleteTasks_log4j.xml

# Delete tasks created by rest users, 60 days after the day the task was created.
# If you set debug=true, just tells you what it would delete, but doesn't actually delete.
PROPERTIES="-D$LOG -D$STDOUT -Dage=60 -Ddebug=false -DrestOnly=true"

RUN="python $SDK_VERSIONS/daemonize $PROPERTIES $COMMAND"

$RUN

**Comment by kenneth59715** [comment]
I put a new version of deleteTasksD in 
/opt/apps/gateway/scigap_svn/gateway_config/sdk/scripts/deleteTasksD
This is set debug=true, so should not actually delete anything.  It will look for any
Tasks over 14 days old and delete input, output and other data, including db_documents,
according to Paul.  Not sure if it will remove anything in globus_transfers.

**Comment by mcianfrocco** [comment]
Thanks @kenneth59715 - I think we will also want to remove globus data as well since 1) all input data will live there and 2) output data is also moved back into this location.

**Comment by kenneth59715** [comment]
I played with removal of globus_transfers data.  I can remove particles.star files manually,
and this will cause a File not found error on task cloning and submit.  I can upload again
with globus.  The file appears under globus_transfers, and job cloning and submit works.
The new globus upload does not generate a new data item, so there will be old dates on
the data items.  Should I implement a find script that deletes files older than 14 days under
globus_transfers?  Then tell the users to re upload, if they get a file not found error?

**Comment by monaw** [comment]
@kenneth59715 - globus directory uploads have an entry in the userdata_dir table.

perhaps a more user-friendly approach would be to add code to check the data when they clone the task?

**Comment by kenneth59715** [comment]
Mona,

 What gets put into userdata_dir when globus uploads/deletes/moves
a new directory?  What happens when it gets reuploaded, either the
whole directory or a file?

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by monaw** [comment]
delete and move are not being handled; we've disabled those features for now.  new uploads creates a new row in userdata_dir table.  the code looks at the globus status and if the status of the transfer goes from active to success, then a new table entry will be created; so it depends on what's the status that globus gives if the user re-uploads; we need to test this to confirm...

**Comment by kenneth59715** [comment]
Does each file in an uploaded directory get its own row in userdata_dir?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by monaw** [comment]
no, just the *.star files on the top and first sub-directory; checkout the code in Transfer2DataManager.java saveDirectories() calls to create new UserDataDirItem

**Comment by kenneth59715** [comment]
My test job is unhappy if the *.star files are present, but the *.mrcs have been removed.
Since *.mrcs files are not in the database, it would be difficult to check for the presence
of those. I think without integration of input data with the database and db_documents,
there will be too many potential missing files to do good checks.

**Comment by monaw** [comment]
yes *.mrc files need to be added to the code; that's on the todo list for after production release.
if the goal is to remove the data, then how about just removing the entire directory, not just the individual file listed in the database?  we can also remove any entries in the userdata_dir table which has the exact same path.

**Comment by kenneth59715** [comment]
I think putting the directory in as the userdata item would work well.  The DeleteTasks.java
code will also look for data items older than a certain date and cleanly delete them.
If we put the globus transfer dirs in as data items, we should be able to just use
DeleteTasks.java to remove old ones.  That will also remove the dirs from the data items
list.

**Comment by kenneth59715** [comment]
Here are the calls that need to be made from DeleteTasks.java to delete UserDataDirItems:
    to be replicated in UserDataDirItem.java:
            List<UserDataItem> dataCandidates = UserDataItem.findDataItemsByAge(age);
            if (dataCandidates.isEmpty())
            {
                log.debug("dataCandidates List is empty!");
            }  
            else
            {
                log.debug("dataCandidates has " + dataCandidates.size() + " entries.");
            }   
            for (UserDataItem udi : dataCandidates)
            {
                long uid = udi.getUserId();
                long dataId = udi.getUserDataId();
                long sid = udi.getSourceDocumentId();
                String cdate = udi.getCreationDate().toString();
                log.debug("Found user data item older than " + age + " days: " + dataId);
                if (m_restOnly)
                {
                    User user = new User(uid);
                    if (!user.getRole().isRestEndUser())
                    {
                        log.debug("Skipping " + user.getRole() + " user data record " + uid);
                        continue;
                    }
                }
                if (m_debug == false)
                {
                    udi.delete();
                    log.debug("Deleted user data record " + dataId + ", sourceDocument=" + sid + ", date created = " + cdate);
                }  else
                {
                    log.debug("Would delete user data record " + dataId + ", sourceDocument=" + sid + ", date created = " + cdate);
                }
            }

**Comment by kenneth59715** [comment]
I tried out deleteTasksD with the new functions in UserDataDirItem.java, and it is 
mostly working.  There is a leftover Icon link in the directory.  Other than that,
things get wiped.

**Comment by monaw** [comment]
@kenneth59715 - i'm not sure what you mean by an icon link; please elaborate...

**Comment by kenneth59715** [comment]
(gatewayVE)[cosmic2-gw@cosmic2 Extract]$ ls -l
total 8
-rw-r--r-- 1 cosmic2-gw cosmic2    0 May  8 09:58 Icon

**Comment by monaw** [comment]
what's the full path to that directory?

**Comment by kenneth59715** [comment]
/projects/cosmic2/gatewaydev/globus_transfers/046f34e64f8b7dc1015072dc7aa30a1a@ucsd.edu/test1/Extract

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by monaw** [comment]
I see there is also a job007/ subdirectory in there.  Do you have the label of the UserDataDirItem you deleted?

**Comment by kenneth59715** [comment]
No, I don't have that.  What is the Icon file from?

**Comment by monaw** [comment]
Ok, I think probably the UserDataDirItem you deleted was in a subdirectory in Extract/ and that was deleted but Extract/ was left the way it was, including the Icon file which must have come from your original upload because the transfer and delete do not create that file.
