### ISSUE TITLE
Footer on gateway

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#164]
Hi @kenneth59715 - I'd like to add the following text to the footer on the gateway: 

COSMIC² is supported by the National Science Foundation under Award Number 1759826.
Copyright © cosmic-cryoem.org. All Rights Reserved. Terms of Use | Privacy Policy.

With the following links: 
1759826: https://www.nsf.gov/awardsearch/showAward?AWD_ID=1759826&HistoricalAwards=false
Terms of Use: https://cosmic-cryoem.org/terms-of-use/
Privacy Policy: https://cosmic-cryoem.org/privacy-policy/

I see there is a footer.jsp, but I'm not sure how to 1) include text and 2) hyperlink the text to appropriate pages. Can you provide guidance?

Thank you,
Mike

**Comment by kenneth59715** [comment]
I don't know how to do that.

I do see in dataList.jsp an include line that might work to include pagination.jsp:
<%@ include file="/pages/common/pagination.jsp" %>

Maybe that kind of line will work to include footer.jsp in whatever pages need
to have it.

There's an anchor href line in login.jsp:
login.jsp:      <a href="https://cosmic-cryoem.org/user-authentication/">Please read more here.</a><br><br>

Something like that might work to put URIs into footer.jsp.

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
It looks like that is one way to do it: include line pointing to footer.jsp,
with anchor tags for remote links in footer.jsp.  I put the links in
as items lin an unordered list.  I think html formatting can be used
around there to prettify.

**Comment by mcianfrocco** [comment]
Awesome - thanks @kenneth59715 ! 

I have no experience with html or web coding in general, can you help me write this into the footer?

COSMIC² is supported by the National Science Foundation under Award Number [1759826](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1759826&HistoricalAwards=false).
Copyright © cosmic-cryoem.org. All Rights Reserved. [Terms of Use](https://cosmic-cryoem.org/terms-of-use/) | [Privacy Policy](https://cosmic-cryoem.org/privacy-policy/).

**Comment by kenneth59715** [comment]
I put that text in.  Does it look right?

**Comment by mcianfrocco** [comment]
Looks awesome- thanks!

**Comment by monaw** [comment]
@kenneth59715 - I just noticed the following error in the log when I login to the gateway:

```
Mar 01 2019 11:00:13 [xec-25] WARN  -                   Include:68     | Exception thrown during include of /pages/common/footer.jsp
javax.servlet.ServletException: File &quot;/pages/common/footer.jsp&quot; not found
	at org.apache.jasper.servlet.JspServlet.handleMissingResource(JspServlet.java:417)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:397)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)

```
Not sure if it is related but I've reopened the issue...

**Comment by kenneth59715** [comment]
I removed the include line for footer.jsp in home.jsp, and the error is gone.
