### ISSUE TITLE
Delete all tasks & data before beta testing

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#165]
Back up database, recreate databases

Delete globus transfer data as well - clean slate before users come in.

**Comment by monaw** [comment]
@kenneth59715 - did you delete any database entries?  I logged in this morning and much of my folders, data and tasks have disappeared...not a problem but just wanted to understand what happened...

**Comment by monaw** [comment]
@kenneth59715 - very weird, i looked again and the reason i didn't see most of my folders is because i somehow was in as you!  I wish I had grabbed a snapshot to show you.  So i logged out and logged back in using my credential and now i'm back to my own account.  Not sure what happened there...hmmm...

**Comment by monaw** [comment]
my mistake!  i logged in to Globus web app as community account and apparently didn't logout and so when i returned to the gateway, it used the community account credential and showed me that account's folders...

**Comment by monaw** [comment]
@mcianfrocco, @kenneth59715, @yilaili - hi guys, FYI, Mike Dwyer is currently out on vacation but he has received my email and will clear our database tonight at 5pm.  i will bring the gateway down before then so probably best to stay off the gateway today...

**Comment by monaw** [comment]
@mcianfrocco, @kenneth59715 & @yilaili - the database has been cleared, the old globus transfer directory renamed and new, empty one created and the gateway is back up.  i tried to login to the new gateway and got an error:

![screen shot 2019-03-02 at 5 14 12 pm](https://user-images.githubusercontent.com/18472048/53689617-a3e45f00-3d0e-11e9-8302-55881cba9d12.png)

can you guys see if you can login or do you get the same error?

**Comment by mcianfrocco** [comment]
I was able to login into the gateway

**Comment by monaw** [comment]
after cleaning out my account entry in groups, oauth_profile, user_group_lookup and users tables, i was able to successfully login also (:
