### ISSUE TITLE
Divide tool page into sections

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#166]
Check with cipres workbench mailing list

**Comment by monaw** [comment]
Mark Miller said the <category> tag in the tool's XML use to work.  I tried it but it didn't...

**Comment by monaw** [comment]
@mcianfrocco - ok, i think i figured out how the tool listing page works; please describe how would you  like the listing to appear...

**Comment by monaw** [comment]
tech note: following tool's XML file tags map to the java code:
```
<title> - ToolLabel
<version> - ToolVersion
<description> - ToolDescription
<category> - ToolType
infile_ - ToolInput
```

**Comment by monaw** [comment]
@mcianfrocco - what do you think using category as section?  what do you think of  https://cosmic2.sdsc.edu:8443/gateway/tools.action ?

**Comment by mcianfrocco** [comment]
Cool! 

Let's call "Testing" "Preprocessing: movie alignment, CTF estimation, particle picking" 

And "Structural Biology" - "Single particle analysis"
