### ISSUE TITLE
Upgrade Tomcat to 7.0.93

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#167]
We are currently running Tomcat 7.0.70 (which was released in June 2016) and should upgrade to the current latest version (7.0.93) due to the many other security releases have come out, including quite a few security fixes that are rated "important" and some of these can impact our gateway.  This latest version (7.0.93) was released in Sept 2018 so appears to be pretty stable.

Let's install this version on the new dev VM and once we decide it seems to be functioning fine, we can later update the production server also.

**Comment by kenneth59715** [comment]
To install Tomcat, as on cosmic2.sdsc.edu, in system directories requires sudo.
Alternatively, I can install it in cosmic2-gw's home dir, as we do for NSG.
Would that be okay?

**Comment by mcianfrocco** [comment]
Sure thats fine by me

**Comment by monaw** [comment]
@kenneth59715 - sorry I didn't see this earlier.  I was actually thinking we should install the 7.0.93 in the new dev VM that's being setup.  Also, I think putting it in the system place is a bit better...both to be consistent with production and also since we are not sharing this VM, I think installing our servers in the system locations is more standard.  Since our new dev VM is managed, perhaps they can install the 7.0.93 as part of the support of the VM?  I don't know if that's included or not...I think Andrew Ferbert is the person to ask...if they don't install software, they can give you sudo to do the installation...i think that's how i did it initially when we weren't paying for the support before...

**Comment by kenneth59715** [comment]
Okay, let's see if they will install it in the standard place for us,
with write permissions in the content directories.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
@kenneth59715 will follow up to ask about this upgrade for the development server

**Comment by mcianfrocco** [comment]
@monaw will check with Andrew regarding responsiveness on tomcat upgrades

**Comment by monaw** [comment]
I asked Andrew and he said that their group can handle Tomcat upgrade if it is to the latest release  version available via rpm.  If we want a specific version, then there will be a charge for that upgrade.

**Comment by kenneth59715** [comment]
Awesome!  Let's have them do the upgrades.  I think we should stagger
it, if possible, so that it gets upgraded first on dev/staging and we try
a data upload and job run, before they upgrade production.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by monaw** [comment]
ok; that sounds good.  i'd like to meet with Andrew a bit to ask him whether we can stage the 2 upgrade so we can test on staging before updating production.

**Comment by mcianfrocco** [comment]
@monaw & @kenneth59715 - did we upgrade tomcat? 

I'm going through our issues to just clear out old ones.

**Comment by kenneth59715** [comment]
If I remember correctly, Mona was talking to the SDSC IT people about doing the
upgrade for us.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by monaw** [comment]
@mcianfrocco & @kenneth59715 - I recall we decided to do it ourselves since we want to be sure we can test it on our staging before production is updated.  if they do it, they will do both at the same time, as part of their regular updates.

**Comment by kenneth59715** [comment]
Okay, if we want a setup like staging, where tomcat is running from
/projects/cosmic2, I can set that up. If we want it running from
/usr, probably Mona can set it up?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by monaw** [comment]
@kenneth59715 - I think it is better that the Tomcat server software be installed and running locally on the VM, not running out of /projects/cosmic2/ which is mounted.  I don't have permission to /usr/ either.  Can you request a directory with the community account as owner and cosmic2 group permission?

**Comment by kenneth59715** [comment]
Mona,

I emailed helpdesk@sdsc.edu.

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
/localdisk in VM has open permissions, so tomcat can be installed there.
