### ISSUE TITLE
3D refinement MRC file error

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#172]
I am getting the following message & error when I try to run a 3D refinement task:

> Thu Mar 14 11:43:45 PDT 2019 > QUEUE : SUCCESS : NGBW-JOB-RELION_3D_REFINE_COMET-3A91A7939B2145189A5FA68DC80EB33B : Added to run queue. 
> Thu Mar 14 11:43:47 PDT 2019 > INPUTSTAGING : SUCCESS : NGBW-JOB-RELION_3D_REFINE_COMET-3A91A7939B2145189A5FA68DC80EB33B : Staging input files to COMET 
> Thu Mar 14 11:43:55 PDT 2019 > INPUTSTAGING : SUCCESS : NGBW-JOB-RELION_3D_REFINE_COMET-3A91A7939B2145189A5FA68DC80EB33B : Input files staged successfully 
> Thu Mar 14 11:43:56 PDT 2019 > SUBMITTING : ERROR : NGBW-JOB-RELION_3D_REFINE_COMET-3A91A7939B2145189A5FA68DC80EB33B : java.lang.Exception: Error submitting job : [Errno 2] No such file or directory: '/projects/cosmic2/gateway/globus_transfers/mona@xsede.org/emd_6287_scale.mrc' 
It looks like perhaps the backend script is looking for the MRC file in the wrong place?

FYI, I use the exact same MRC file (emd_6287_scale.mrc) for a 3D classification task and that one ran successfully (NGBW-JOB-RELION_3D_CLASS_COMET-2090C70BE42D40C4902F4421E956C0FC).  Also, I checked the working directory for the failed job (NGBW-JOB-RELION_3D_REFINE_COMET-3A91A7939B2145189A5FA68DC80EB33B) and the emd_6287_scale.mrc file is in there.

**Comment by mcianfrocco** [comment]
Hi @monaw - I'm not sure what happened for you. How did you upload the file? Through your web browser? I just ran a 3D refinement and it worked for me.

**Comment by monaw** [comment]
@mcianfrocco - yes through the web browser.  oddly the exact same mrc file worked for a 3D classification task...let me test 3D refinement again...

**Comment by monaw** [comment]
@mcianfrocco - ok, i created a new 3D refinement task with same mrc file and it worked this time (:
