### ISSUE TITLE
user renaming folder

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#174]
When user renames folder, need to add code to rename directory in Globus transfer location!

**Comment by mcianfrocco** [comment]
Should we remove the rename feature?

**Comment by monaw** [comment]
it is a nicer feature from a user perspective...we could disable it for now or i might be able to add the code to rename the directory without too much work...what's your preference?

**Comment by mcianfrocco** [comment]
Let's table this for now to focus on getting everything else ironed out. So, let's remove the button from the user choice.

**Comment by monaw** [comment]
done

![Screen Shot 2019-03-16 at 9 26 41 AM](https://user-images.githubusercontent.com/18472048/54478291-b4480f80-47cd-11e9-9fc6-f385dcec1815.png)

**Comment by mcianfrocco** [comment]
thanks!
