### ISSUE TITLE
Input files not being passed

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#175]
Hi @monaw - I'm not sure if this was caused by dealing with task cloning in #113 but now I can't submit any jobs since they are unable to get the input file passed (--i) input. 

For instance, for 2D classification, this is the error:
ERROR : NGBW-JOB-RELION_2D_CLASS_COMET-E22515D361104024ADD6142B77C7D02F : java.lang.Exception: Error submitting job: Traceback (most recent call last): File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 754, in <module> relion_command,outdir,out_destination,runhours,nodes,numiters,worksubdir,partition,gpuextra1,gpuextra2,gpuextra3,mpi_to_use=prepareRelionRun(args) File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 377, in prepareRelionRun log(statusfile, "can't get inputZipFile, submit_job is returning 1\n"

And if you look in the _COMMANDLINE file in the job directory, you'll see it's missing anything referring to '--i'

**Comment by monaw** [comment]
@mcianfrocco - if your task was created sometime yesterday, it is possible it was during my debugging of the task cloning which may have caused this; although i don't think i was doing anything to the infile (--i) parameter.  i did just fix the task cloning problem and created a brand new 2D classification task and submitted that (NGBW-JOB-RELION_2D_CLASS_COMET-724CF4E5EB8F4E1B8043A2A36EDDA21E).  it does contain the --i parameter:

```
relion_refine_mpi --angpix 1  --offset_step 2 --psi_step 10 --iter 25 --particle_diameter 200 --K 10  --offset_ra
nge 5 --ctf  --strict_highres_exp -1 --tau2_fudge 2 --i "testing/Extract/job009/particles.star"
```

please try with a brand new 2D classification task...

**Comment by mcianfrocco** [comment]
ok yes - fixed! Thanks for fixing it.
