### ISSUE TITLE
tar failing

### ISSUE THREAD

**Issue by kenneth59715** [cianfrocco-lab/COSMIC-CryoEM-Gateway#176]
Looks like the tar is failing at the end of the job script.  This leaves a return code
of 2, resulting in a Failed email message at job completion.  Looks like it still
goes into ARCHIVE rather than FAIL.  Looks like the job001 directory goes away
before the tar runs.
/bin/tar -cvzf output.tar.gz Class2D_cosmic/job001/

/bin/tar: Class2D_cosmic/job001: Cannot stat: No such file or directory
/bin/tar: Exiting with failure status due to previous errors

**Comment by mcianfrocco** [comment]
We don't use the tarball since we use globus. Do you think if I remove that line of the job submission it will be a problem?

**Comment by kenneth59715** [comment]
NSG uses the tar to provide users with a download archive file.  If we don't
need to do that, I think that line could be commented out.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
ok i'll try commenting it out to see if it fixes it

**Comment by kenneth59715** [comment]
I just ran a 2D refinement test job, and it ended with COMPLETED status in the notification
email.  Output looks the same as older jobs, so I think we're good.
