### ISSUE TITLE
error submitting 2d job

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#177]
I just tested a 2d job and it failed with the message in the gateway:

> Thu Apr 11 19:07:31 PDT 2019 > QUEUE : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-52FC6FD580EF4E4EA8779133DD8BECF6 : Added to run queue. 
> Thu Apr 11 19:07:41 PDT 2019 > INPUTSTAGING : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-52FC6FD580EF4E4EA8779133DD8BECF6 : Staging input files to comet-gpu 
> Thu Apr 11 19:07:42 PDT 2019 > INPUTSTAGING : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-52FC6FD580EF4E4EA8779133DD8BECF6 : Input files staged successfully 
> Thu Apr 11 19:07:44 PDT 2019 > SUBMITTING : ERROR : NGBW-JOB-RELION_2D_CLASS_COMET-52FC6FD580EF4E4EA8779133DD8BECF6 : java.lang.Exception: Error submitting job: 

and in submitJob.log, it shows:

>  Apr 11 2019 19:07:43 [read-1] ERROR -              TaskInitiate:250             [task=947, job=NGBW-JOB-RELION_2D_CLASS_COMET-                                  52FC6FD580EF4E4EA8779133DD8BECF6] |
>  java.lang.Exception: Error submitting job:
>      at org.ngbw.sdk.tool.SSHExecProcessWorker.submitJob(SSHExecProcessWorker.   java:288)
>      at org.ngbw.sdk.tool.SSHExecProcessWorker.submitImpl(SSHExecProcessWorker.  java:96)
>      at org.ngbw.sdk.tool.BaseProcessWorker.submit(BaseProcessWorker.java:126)
>      at org.ngbw.sdk.tool.TaskInitiate.stageAndRun(TaskInitiate.java:315)
>      at org.ngbw.sdk.tool.TaskInitiate.runTask(TaskInitiate.java:235)
>      at org.ngbw.utils.StageAndSubmitATask.stageAndSubmit(StageAndSubmitATask.   java:37)
>      at org.ngbw.utils.SubmitJob$ProcessRunningTask.run(SubmitJob.java:239)
>      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.    java:1149)
>      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.   java:624)
>      at java.lang.Thread.run(Thread.java:748)
>  Apr 11 2019 19:07:44 [read-1] DEBUG -                Statistics:54              [task=947, job=NGBW-JOB-RELION_2D_CLASS_COMET-                                  52FC6FD580EF4E4EA8779133DD8BECF6] | accountingPeriodStart for cpu Hrs is '2016- 07-01'
>  Apr 11 2019 19:07:44 [read-1] DEBUG -                 WorkQueue:204             [task=947, job=NGBW-JOB-RELION_2D_CLASS_COMET-                                  52FC6FD580EF4E4EA8779133DD8BECF6] | Job Failed. About to delete running task    NGBW-JOB-RELION_2D_CLASS_COMET-52FC6FD580EF4E4EA8779133DD8BECF6

**Comment by monaw** [comment]
@mcianfrocco - can you do a test of 2d and see if it works for you?  also, can you take a look at /projects/cosmic2/gateway/workspace/FAILED/NGBW-JOB-RELION_2D_CLASS_COMET-52FC6FD580EF4E4EA8779133DD8BECF6/ and see if you can spot the reason for its failure?  i can't quite tell from the error messages i saw...

**Comment by mcianfrocco** [comment]
hi @monaw - it looks like an issue with the input data not being parsed correctly. I just tried creating a directory with space and it uploaded correctly.

can you send a screenshot of how you selected the data for upload via globus?

**Comment by monaw** [comment]
@mcianfrocco - is this what you want?

![Screen Shot 2019-04-11 at 7 47 25 PM](https://user-images.githubusercontent.com/18472048/56008910-ba2cf580-5c92-11e9-9e3d-55293929864b.png)

I then clicked on the Transfer button.

My Globus transfer worked fine but the job failed...

**Comment by mcianfrocco** [comment]
Ah - ok. Thanks for the screenshot. The issue is that my code (apparently) gets tripped up if the star file and particles are one directory below from where the user selects during the Globus upload. I thought it should have been able to handle this but it does not. 

So - instead of clicking 'job009' for upload, can you go up a directory and click 'Extract' as the upload? This should work. I will create a ticket related to this issue.

**Comment by monaw** [comment]
ok, i tried upload from Extract folder and that worked, thanks
