### ISSUE TITLE
Delete data within directory during directory deletion

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#181]
I just found an issue related to data management - if I 'Delete' a directory on COSMIC2 then the directory is removed from the web interface but the data are not removed from the globus directory.

Can we either: 
1) Tell users to delete data within a directory before deleting the folder? 
or 
2) Delete all data within a directory when a the directory is deleted?

**Comment by monaw** [comment]
@mcianfrocco - #2 above is done
