### ISSUE TITLE
Add new fields to each user in database: job limit & upload limit

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#182]
Create new fields so we can control individual user ability to upload and submit

**Comment by mcianfrocco** [comment]
Or we can update database per user @kenneth59715 as jobs are submitted instead of waiting for tera grid usage.

**Comment by monaw** [comment]
@mcianfrocco - is it reasonable to say that the upload max limit per user is > 100 GB?  If yes, we can save some space in the database (e.g., store 6 instead of 600,000,000,000)

**Comment by mcianfrocco** [comment]
yes that will be the case

**Comment by monaw** [comment]
i have another idea...would it be useful to have a default value for everyone initially and only different size limit for some users?  CIPRES has a table called user_preferences that is meant to store per user settings...

**Comment by mcianfrocco** [comment]
Yes - that would definitely work! Then we just change the group identity for the user for those who can run jobs?
