### ISSUE TITLE
Add CPU or GPU SUs to database

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#186]
Currently, we record only GPU SU numbers but we will have CPU jobs that will need to tracked separately (or at least scaled appropriately) (See #123).

@kenneth59715 will need to update the codebase to allow this.

**Comment by kenneth59715** [comment]
To create the comet GPU entry in resource_conversion table in the db:
INSERT INTO resource_conversion (RESOURCE, CONVERSION)
  VALUES ('comet', '1')
;

**Comment by mcianfrocco** [comment]
Hi @kenneth59715 - here is a CPU based tool ; if you add it to the dev site I can test it 

/opt/apps/gateway/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/particle_picking_ctf_motion.xml

**Comment by mcianfrocco** [comment]
@mcianfrocco - check this CPU works.

**Comment by kenneth59715** [comment]
This is done.  CPU jobs need to be tested.
