### ISSUE TITLE
Ingest .star file even if there are .mrc files in upload directory

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#189]
Hi @monaw & @kenneth59715  - 

[Sorry for the long post, but want to explain this clearly]

**Problem:** 
Globus uploads don't ingest star files correctly (it puts them into the database and removes them from their expected location in a directory on Comet) when there are .mrc files present in the same directory as the .star files. Without the star file in the upload directory, the gateway cannot stage the files correctly as it is looking for the starfile to be physically located in the upload directory (not in the database).

**Proposed solution:**
If there are .mrc files in a directory alongside star files, do not remove the starfile from the directory on Comet.

**Background:** 
Beyond using RELION for image analysis (which works!) I also want users to be able to upload raw data (such as micrographs or movie files). 

A few pieces of info: 
Micrographs are stored as .mrc format whereas movie files are stored as .mrcs

For upload, we can use the same system as we have done previously, the user selects a directory for upload, where, two directories within it, there is a star file and data (this is what we already do with particle stacks).

This upload system works for movie files already. So, if I had a directory: 

Movies/

I would put movies into a subdirectory: 

Movies/job001/

Where it would look like: 

Movies/job001/movies.star     <------ input star file
Movies/job001/movie_files/movie1.mrcs
Movies/job001/movie_files/movie2.mrcs 
...

When I do this upload, I select 'Movies' via the Globus upload interface, and after upload, the directory is transfer and the gateway shows me Movies/job001/movies.star in the data listing page. 

The **problem** is that it breaks down when these are micrographs instead of movies due to the fact that our gateway can upload individual MRC files. 

Example: If I had a micrographs directory: 

Micrographs/

I would put micrographs into a subdirectory: 

Micrographs/job001/

Where it would look like: 

Micrographs/job001/micrographs.star     <------ input star file
Micrographs/job001/micrograph_files/micrograph1.mrc
Micrographs/job001/micrograph_files/micrograph2.mrc 
...

If I do this upload, the globus transfer succeeds and Micrographs/job001/micrographs.star shows up in the data page. However, if I look into this directory on Comet, the star file is no longer found.

I suspected this is due to the presence of .mrc files in the directory, so, if I take the same directory but rename the .mrc files to .mrcs (just for testing), the upload proceeds and is ingested correctly. 

To test this I've shared a directory on Globus to both @monaw & @kenneth59715: 

https://app.globus.org/file-manager?origin_id=b24dbace-83ad-11e9-8e63-029d279f7e24&origin_path=%2F

In this, there are two directories:
* Mics/job001 
* Mics/job002

Mics/job001 has .mrc within it whereas Mics/job002 has .mrcs files. You'll see that if you select 'Mics' for upload, both Mics/job001/micrographs.star & Mics/job002/micrographs.star will appear in the data page, however, if you look on Comet, you'll see that the file Mics/job001/micrographs.star does not exist.

**Comment by monaw** [comment]
@mcianfrocco - ok, after looking at the code, it appears we are only looking for specifically particles.star files, not any other *.star file; please see Issue #78 for more details.  Oddly that your testing worked for movies.star and micrographs.star...

**Comment by monaw** [comment]
i just did a test with the Mics/ data you provided above and I copied the micrographs.star to particles.star (so now there are 2 star files in each subdirectory) and it worked; the star files are still in there:

cosmic2 (74) % /blahblahblah/globus_transfers/mona@xsede.org/friday afternoon/Mics
cosmic2 (75) % find . -name "*.star" -print
./job002/particles.star
./job002/micrographs.star
./job001/particles.star
./job001/micrographs.star

and the gateway listing also looks correct:

![Screen Shot 2019-06-07 at 1 25 05 PM](https://user-images.githubusercontent.com/18472048/59131634-bc749e80-8927-11e9-8c2f-69121fa64cff.png)

**Comment by mcianfrocco** [comment]
Yes! Worked for me too! Thanks @monaw !

**Comment by mcianfrocco** [comment]
Ok - one follow up. This works but can we extend this to directories that have .mrcs files? Previously this worked but now it no longer does. This example can be found in a new directory I added into the globus shared endpoint 'job003'.

**Comment by mcianfrocco** [comment]
Hmm nevermind - I had an issue on my end, this works! Closing again..

**Comment by mcianfrocco** [comment]
Ok - to reopen this - 

For the test upload in Mics/job003, after uploading into the gateway, I'd *like* the display data list to only show: 

Mics/job003/movies.star

But instead it lists this: 

<img width="1164" alt="Screen Shot 2019-06-20 at 4 04 15 PM" src="https://user-images.githubusercontent.com/1464469/59878111-754dcb00-9375-11e9-90c6-c1e9d92c891a.png">

I then used the movies.star file for preprocessing with these inputs: 

<img width="908" alt="Screen Shot 2019-06-20 at 4 07 36 PM" src="https://user-images.githubusercontent.com/1464469/59878215-bba32a00-9375-11e9-955d-a72aba7a7c46.png">

Then, when I submit it I got this error: 

Thu Jun 20 13:07:57 PDT 2019 > QUEUE : SUCCESS : NGBW-JOB-PARTICLE_PICKING_CTF_MOTION-3CB7DBDE52D64EC2BF9BCED4F216B078 : Added to run queue. 
Thu Jun 20 13:08:03 PDT 2019 > INPUTSTAGING : SUCCESS : NGBW-JOB-PARTICLE_PICKING_CTF_MOTION-3CB7DBDE52D64EC2BF9BCED4F216B078 : Staging input files to COMET 
Thu Jun 20 13:08:03 PDT 2019 > INPUTSTAGING : ERROR : NGBW-JOB-PARTICLE_PICKING_CTF_MOTION-3CB7DBDE52D64EC2BF9BCED4F216B078 : com.trilead.ssh2.SFTPException: No such file (SSH_FX_NO_SUCH_FILE: A reference was made to a file which does not exist.)

**Comment by mcianfrocco** [comment]
@monaw - what happened when you uploaded this directory?

**Comment by monaw** [comment]
@mcianfrocco - I grabbed your Mics/job003/ and did a Globus upload and it worked fine...really weird!

![Screen Shot 2019-06-20 at 4 11 09 PM](https://user-images.githubusercontent.com/18472048/59887068-b0043300-9376-11e9-902f-174c4b5e644f.png)

I see something else weird in the database...looks like your transfer went into userdata table:

```
MySQL [cosmic2_sg]> select LABEL, CREATION_DATE from userdata where user_id=2;
+------------------------------------------------------------------+---------------------+
| LABEL                                                            | CREATION_DATE       |
+------------------------------------------------------------------+---------------------+
| norm-amibox05-0.mrc                                              | 2019-05-30 11:39:36 |
| norm-amibox05-0.mrc                                              | 2019-05-31 08:48:57 |
| cosmic2/T20S/movies/14sep05c_00024sq_00003hl_00002es.frames.mrcs | 2019-06-20 11:34:14 |
| cosmic2/T20S/movies/14sep05c_00024sq_00003hl_00005es.frames.mrcs | 2019-06-20 11:34:26 |
| cosmic2/T20S/movies/14sep05c_00024sq_00006hl_00003es.frames.mrcs | 2019-06-20 11:34:38 |
| cosmic2/T20S/movies/movies.star                                  | 2019-06-20 11:34:50 |
| Mics/job003/14sep05c_00024sq_00003hl_00002es.frames.mrcs         | 2019-06-20 13:03:35 |
| Mics/job003/14sep05c_00024sq_00003hl_00005es.frames.mrcs         | 2019-06-20 13:03:47 |
| Mics/job003/14sep05c_00024sq_00006hl_00003es.frames.mrcs         | 2019-06-20 13:03:59 |
| Mics/job003/movies.star                                          | 2019-06-20 13:04:11 |
+------------------------------------------------------------------+---------------------+
10 rows in set (0.01 sec)
```
whereas my transfer went into the userdata_dir table:

```
MySQL [cosmic2_sg]> select LABEL, CREATION_DATE from userdata_dir where user_id=1;
+-------------------------------------+---------------------+
| LABEL                               | CREATION_DATE       |
+-------------------------------------+---------------------+
| Mics/job002/particles.star          | 2019-06-07 16:24:59 |
| Mics/job001/particles.star          | 2019-06-07 16:24:59 |
| 2d_class/betagaltest/particles.star | 2019-06-20 12:37:54 |
| Mics/job003/movies.star             | 2019-06-20 16:10:51 |
+-------------------------------------+---------------------+
4 rows in set (0.00 sec)
```

**Comment by mcianfrocco** [comment]
Oh! I think I know why. 

I had been selecting the entire directory on the globus upload: 

<img width="738" alt="Screen Shot 2019-06-21 at 11 55 12 AM" src="https://user-images.githubusercontent.com/1464469/59935779-91587780-941c-11e9-97b2-2f96ca29b632.png">

But, if I only select the star file, then I get the data to be uploaded correctly (i.e. only one file shows up in the list, movies.star)

I think we just need to tell users about this for now. Long term we woudl need to fix this b/c what happens if someone selects a directory with 1000s of files? Each file gets an entry in the database?

**Comment by mcianfrocco** [comment]
Although, I just tried to submit this and got this error: 

INPUTSTAGING : ERROR : NGBW-JOB-PARTICLE_PICKING_CTF_MOTION-58BE1A181E77488D9EA5E6257511E018 : com.trilead.ssh2.SFTPException: No such file (SSH_FX_NO_SUCH_FILE: A reference was made to a file which does not exist.)

**Comment by monaw** [comment]
fyi, i also select the entire directory when i upload, not the individual files...hmmm...

**Comment by mcianfrocco** [comment]
Hi @monaw - maybe we should just do a wipe of the production server (or just delete my mcianfro@umich.edu account). I just was testing my michael.a.cianfrocco@gmail.com account and I saw that the folder issue I previously reported in #185 is gone. 

So I uploaded Mic/job003 and it ingested correctly (1 file, movies.star) and then I was able to successfully stage & submit to Comet.

This makes me think something is weird with my account mcianfro@umich.edu due to weird uploading that I did as testing?

**Comment by monaw** [comment]
@mcianfrocco - ok i've removed both of your accounts, hope that's ok.  please start over with the account that you intend to use and let's see if the Globus transfer directory gets created with correct permission and if you are able to successfully do a Globus upload...

**Comment by monaw** [comment]
@mcianfrocco - ok after clearing the database, i was able to replicate the problem with the upload:

![Screen Shot 2019-07-03 at 7 53 33 PM](https://user-images.githubusercontent.com/18472048/60636723-7ac30080-9dcc-11e9-8e0c-5e524d097d2b.png)

i guess that's the good news; now I need to debug and fix it...

**Comment by monaw** [comment]
@mcianfrocco - ok i think i finally understand what's happening...the bottom line is...the result depends on how the user selects the files using the globus transfer mechanism...

For my testing, i created the following:

small/job/a.mrc
small/job/b.mrcs
small/job/micrographs.star
small/job/particles.star

The correct behavior we want is that ONLY small/job/particles.star file is listed in the data listing page and all files remain in the transfer directory.

If the user selects the directory WITHOUT listing the file:

![github issue 189](https://user-images.githubusercontent.com/18472048/61507029-01fda000-a999-11e9-83d0-40a3e0c63b68.png)

then the listing is correct and the files stay in the transfer location:

![Screen Shot 2019-07-18 at 8 17 40 PM](https://user-images.githubusercontent.com/18472048/61507293-ff4f7a80-a999-11e9-8142-3f1318419062.png)

However, if the user lists the files and then selects either the file or the directory:

![github issue 189b](https://user-images.githubusercontent.com/18472048/61507826-3030af00-a99c-11e9-91cb-7ab73ee2877e.png)

then the listing is wrong and the files are moved from the transfer location:

![Screen Shot 2019-07-18 at 8 41 35 PM](https://user-images.githubusercontent.com/18472048/61507917-8ef62880-a99c-11e9-9eb8-e66ed8088591.png)

The way the user selects the directory/file impacts the way Globus returns information which impacts how the code handles the data...files are listed and moved but directories are not.

One thing to keep in mind is that if the user uses Globus to upload a single mrc reference map file, then the file is handle properly (listed and moved).

**Comment by monaw** [comment]
your proposed solution in the first posting is possible but perhaps if i can phrase it slightly differently...if there is star file (any *.star or only particles.star?) then nothing is moved and only particles.star is listed (if it exists) OR if there is *.mrc, those files are treated as files and all others are not;  which one makes more sense from the user's perspective?

**Comment by monaw** [comment]
design note:
- if single *.mrc file, list in gateway and handle as file (UserDataItem)
- if multiple files or directory & no *.star, create and list star file; handle as directory (UserDataDirItem)
- if multiple files or directory WITH *.star file(s), list *.star file(s); handle as directory (UserDataDirItem)

**Comment by monaw** [comment]
related to issue #228

**Comment by monaw** [comment]
@mcianfrocco - currently our code will look for any *.star files in a user upload directory (only the 1st level AND look specifically for particles.star in the second level directory (if any).  Is this still the right thing to do for handling user upload directory?

**Comment by mcianfrocco** [comment]
Yes sounds correct.

**Comment by monaw** [comment]
changes have been pushed to production
