### ISSUE TITLE
Cannot delete folder via web interface

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#190]
I just ran into an error where I cannot a delete a folder on the gateway via the 'Delete folder' button. I get this error: 

Folder "Test movie align" could not be deleted.

The gateway error is: 

```
May 31 2019 07:29:07 [xec-18] DEBUG -         SessionController:850    | mcianfro@umich.edu - Error deleting folder [Folder@11: Label "Test movie align"]: Unable to delete file: /projects/cosmic2/gateway/globus_transfers/mcianfro@umich.edu/Test movie align/cosmic2/T20S/crYOLO_cosmic/job031/STAR/14sep05c_00024sq_00003hl_00005es_frames.star
java.io.IOException: Unable to delete file: /projects/cosmic2/gateway/globus_transfers/mcianfro@umich.edu/Test movie align/cosmic2/T20S/crYOLO_cosmic/job031/STAR/14sep05c_00024sq_00003hl_00005es_frames.star
```
Even though the file exists and I was able to delete this when I logged into Comet as cosmic2. 

Thoughts on what happened with this? It could be due to a hiccup with problems I had with micrograph uploads (see #189).

Mike

**Comment by monaw** [comment]
@mcianfrocco - that file indeed doesn't exist but sounds like you manually deleted that file using the cosmic2 account.  So currently, does the folder "Test movie align" still show up in your gateway UI?  If yes, does it show any data files?

**Comment by mcianfrocco** [comment]
Yes - "Test movie align" still shows up and it lists one data file (norm-amibox05-0.mrc).

I'm sure this is due to my testing uploads, but I had this happen with another folder "test-monday1", where I can't delete this folder either.

**Comment by monaw** [comment]
@mcianfrocco - here are the folders that showed up for you in the database:

```
+--------------------+---------------------+
| label              | creation_date       |
+--------------------+---------------------+
| mcianfro@umich.edu | 2019-05-23 19:41:41 |
| Test movie align   | 2019-05-30 10:58:45 |
| test               | 2019-05-31 08:44:54 |
| test-monday1       | 2019-06-17 09:04:55 |
| testing2           | 2019-06-17 13:01:50 |
| 20190620-1         | 2019-06-20 11:31:39 |
| testing-thursday   | 2019-06-20 13:01:25 |
+--------------------+---------------------+
```
Notice the first one which doesn't show up in your gateway folder listing nor the gateway transfer directory...weird!

Can I go ahead and delete the 3 weird folders ("mcianfro@umich.edu", "Test movie align" and "test-monday1") manually and from the database?

**Comment by mcianfrocco** [comment]
yes - please do !

**Comment by monaw** [comment]
ok i've removed the "Test movie align" and "test-monday1" directory and data from the database.  Turns out "mcianfro@umich.edu" folder is your top-level folder and that must stay in the database; every account has one (:
