### ISSUE TITLE
Job staging error: workspace directory not created 'fast enough'

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#191]
I got this error in the gateway: 

Fri May 31 08:51:16 PDT 2019 > SUBMITTING : ERROR : NGBW-JOB-PARTICLE_PICKING_CTF_MOTION-AABCA7B20E494EE6B8805A9C1FAAE5C6 : java.lang.Exception: Error submitting job : [Errno 2] No such file or directory: './scheduler.conf' 

And when I checked the workspace, the workspace directory NGBW-JOB-PARTICLE_PICKING_CTF_MOTION-AABCA7B20E494EE6B8805A9C1FAAE5C6 had not been created yet. However, 30-60 seconds later, the directory appeared with the appropriate files. 

Just wanted to report this in case it happens consistently.

**Comment by mcianfrocco** [comment]
Happened again today: total count = 2

And, after cloning the job and resubmitting, it was able to successfully stage & submit to cluster on second attempt.

**Comment by mcianfrocco** [comment]
@mcianfrocco will make a test job for this error

**Comment by monaw** [comment]
Did the task show the message "...Input files staged successfully" above the SUBMITTING line?

I just did a test of the preprocessing tool with some junk data and got a different error...perhaps you are updating the backend script:

`Fri Jun 07 13:54:24 PDT 2019 > SUBMITTING : ERROR : NGBW-JOB-PARTICLE_PICKING_CTF_MOTION-A4BFD1D1BFAE486CAF92285DCDC30A74 : java.lang.Exception: Error submitting job: Traceback (most recent call last): File "/blahblahblah/remote_scripts/comet_relion_submit.py", line 861, in <module> movie_align_cmd,ctf_cmd,ctf_sel_cmd,picking_cmd,extraction_cmd,mics_for_picking_symlink,class2d_cmd,cryolo_cp_cmd,DirToSymLink=preparePreprocessingRun(args['commandline'],jobdir) TypeError: 'int' object is not iterable 
`

**Comment by mcianfrocco** [comment]
Hi @monaw - the error you got is related to the preprocessing tool that should be fixed now. 

Regarding your question, I don't think it said that, although I think I may have deleted the task that failed. I'll keep an eye out for it.
