### ISSUE TITLE
Add XSEDE & SGCI support & how to cite paper in gateway footer

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#192]
@mcianfrocco - Marlon asked if we can add to the gateway footer info about XSEDE and SGCI support as well as reference about our paper

**Comment by mcianfrocco** [comment]
Hi @monaw - sure we can add this. Do we need to include any hyperlinks or award numbers for XSEDE ECSS and SGCI?

**Comment by monaw** [comment]
I think a link to the main project (XSEDE or SGCI) page would be good enough, thank you!

**Comment by mcianfrocco** [comment]
Ok sounds good.

@kenneth59715 can you update the footer to read like the following (with the same hyperlinks)?

COSMIC2 is supported by the National Science Foundation under Award Number [1759826](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1759826&HistoricalAwards=false), [XSEDE ECSS](https://www.xsede.org/for-users/ecss), and [Science Gateways Community Institute](https://sciencegateways.org/).

**Comment by kenneth59715** [comment]
Okay, footer.jsp has been modified.  I committed the change.
Should I push up to github?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
Thanks @kenneth59715 ! A small change to make, right now the footer looks like this with extra spaces between the name & comma: 

COSMIC2 is supported by the National Science Foundation under Award Number [1759826](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1759826&HistoricalAwards=false) , [XSEDE ECSS](https://www.xsede.org/for-users/ecss) , and [Science Gateways Community Institute](https://sciencegateways.org/). 

When it should look like: 

COSMIC2 is supported by the National Science Foundation under Award Number [1759826](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1759826&HistoricalAwards=false), [XSEDE ECSS](https://www.xsede.org/for-users/ecss), and [Science Gateways Community Institute](https://sciencegateways.org/).

Thanks,
Mike

**Comment by kenneth59715** [comment]
It's not in the footer.jsp file, so I don't know how to fix that.  Maybe
something about jsp formatting?

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
Okay, I think I found it.  I had to comment out a margin-right
directive in gateway.css:

.footer a {
  display: inline-block;
  /* margin-right: 10px; */
}

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
Looks good - thanks!
