### ISSUE TITLE
Update xml tool files in development

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#195]
Update tool files for correct SU accounting

**Comment by kenneth59715** [comment]
diff --git a/gateway_config/sdk/src/main/resources/pisexml/relion_2d_class_comet
index 17361fe..80c5c95 100644
--- a/gateway_config/sdk/src/main/resources/pisexml/relion_2d_class_comet.xml
+++ b/gateway_config/sdk/src/main/resources/pisexml/relion_2d_class_comet.xml
@@ -68,6 +68,8 @@ Mike -->
                                <language>perl</language>
                                <code>
 
+                                "gpu=4\\n" .
+                                "ChargeFactor=1.0\\n" .
                                 "ntasks-per-node=15\\n" .
                                 "node_exclusive=1\\n" .
                                 "nodes=10\\n"
@@ -156,6 +158,7 @@ Mike -->
     

     
     <parameter type="Float" issimple="1" ismandatory="1">
            <name>runtime</name>
            <attributes>
@@ -183,7 +186,6 @@ Mike -->
                    </format>
            </attributes>
     </parameter>
-    -->

     <!-- DISABLE output directory parameter; due to XML syntax, had to add
          a blank between "- -" so if you are going to re-enable this

**Comment by kenneth59715** [comment]
I think this got taken care of in the merge of production gateway_config files
to development and upgrade of production.  Should test each tool on
production.
