### ISSUE TITLE
Merge production > development; then move development into production

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#198]
Overall plan for getting production / development all in line.

**Comment by kenneth59715** [comment]
Here's my plan for merging current production into dev:
- save /projects/cosmic2/kennethtest/dev/41.14/portal-R41.14/gateway_config
- commit changes in dev gateway_config
- git pull from origin (gateway_config on github)
- resolve conflicts

**Comment by kenneth59715** [comment]
This is done.
