### ISSUE TITLE
Single file upload via web browser fails

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#207]
I just tried uploading a single text file via the web browser to the development server, and I got this error: 

<img width="781" alt="Screen Shot 2019-10-23 at 3 35 21 PM" src="https://user-images.githubusercontent.com/1464469/67428514-427a4480-f5ac-11e9-843f-e8a65035f3de.png">

**Comment by mcianfrocco** [comment]
To clarify - apparently only STAR files do not upload

**Comment by kenneth59715** [comment]
Added a 'STAR' entry into the enum in DataType.java.  .star files now upload.
The Format in the data list is 'Unknown', but Effciency Tool runs it.
