### ISSUE TITLE
new user globus_transfers directory fails

### ISSUE THREAD

**Issue by kenneth59715** [cianfrocco-lab/COSMIC-CryoEM-Gateway#210]
new user on production, fails to create dir under globus_transfers/<email>

gateway.log:
...
Nov 08 2019 15:19:48 [xec-25] INFO  -         DynamicTreeAction:47     | Node ID: in3
Nov 08 2019 15:19:48 [xec-25] INFO  -         DynamicTreeAction:98     | SRC Endpoint ID: c982d486-6d04-11e5-ba46-22000b92c6ec
Nov 08 2019 15:19:48 [xec-25] INFO  -         DynamicTreeAction:99     | SRC Path: /oasis/scratch-comet/kenneth/temp_project/shared/globustransfer//in3
Nov 08 2019 15:19:50 [xec-25] INFO  -         DynamicTreeAction:63     | Contents of /oasis/scratch-comet/kenneth/temp_project/shared/globustransfer//in3 on c982d486-6d04-11e5-ba46-22000b92c6ec:
Nov 08 2019 15:19:58 [xec-23] ERROR -            TransferAction:937    | Create directory: EndpointPermissionDenied(403 Forbidden) on request 'lL78wpE0X' resource '/endpoint/de463f97-6d04-11e5-ba46-22000b92c6ec/mkdir': Denied by endpoint, Error (mkdir)
Endpoint: XSEDE Comet (de463f97-6d04-11e5-ba46-22000b92c6ec)
Server: oasis-dm.sdsc.xsede.org:2811
Command: MKD /projects/cosmic2/gateway/globus_transfers/kenneth@globusid.org/test2/
Message: Fatal FTP Response
...

drwxr-x--- 2  514000 cosmic2    0 Nov  8 15:16 kenneth@globusid.org

Looks like group-write is off.  Need to find what is setting mode for the new dir.

**Comment by kenneth59715** [comment]
Having trouble reproducing this...

**Comment by monaw** [comment]
Sigh...this is an ongoing issue, see issue # 194.  There is code to change the permission but it doesn't seem to be working.  However, when I try to debug it, then it works...sigh.  I've been manually checking the globus_transfer/ directory for new account and changing the group permission...I don't have a better solution right now...maybe using a cronjob to change the permission?  need more work to see why the code isn't working...
