### ISSUE TITLE
new XSEDE gateway attributes submission

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#214]
There is a new XSEDE gateway attributes submission mechanism.  Info about this can be found at http://users.sdsc.edu/~amit/gateway_attr/.

**Comment by monaw** [comment]
@kenneth59715 - do you know how the old mechanism worked and where that code is for COSMIC2?  Also, has NSG updated to the new mechanism?

**Comment by monaw** [comment]
I created an API key for our gateway and it is stored in the gateway community account's home directory according to instruction at https://xsede-xdcdb-api.xsede.org/api/gateways.  Should we update comet_relion_submit.py, remove the previous call to gateway_submit_attributes and replace it with the new REST API call show at the URL above?

**Comment by kenneth59715** [comment]
I think that's how Subha did it for NSG.  However, to deal with outages
of the XSEDE service, we are supposed to arrange for retries, if the
service is down.  That means we need to save the job info and retry later
if it's down.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
New script is in place and comet_relion_submit.py has been modified to call that script.
rerun-gsa.py
The last ten jobs can be checked with
gsacheck.sh
failed job attribute uploads are saved in the remote_scipts/rerunfiles directory.
There are place where failed uploads can fail to be saved.  If the node is rebooted
after job submit and before the rerunfile is saved, then the record of job attributes
will be lost.  Not committed to git, yet.

**Comment by kenneth59715** [comment]
This is in git and put into production.
