### ISSUE TITLE
Production testing issue

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#216]
Hi @kenneth59715 - I was just testing out the production gateway for RELION jobs and, after uploading successfully via globus, I got this error: 

Fri Dec 13 08:26:02 PST 2019 > SUBMITTING : ERROR : NGBW-JOB-RELION_2D_CLASS_COMET-794D6C02C0AF4FA493A6D23547DDD430 : java.lang.Exception: Error submitting job : [Errno 2] No such file or directory: '/projects/cosmic2/gatewaydev/globus_transfers/mcianfro@umich.edu/testing /Extract/job009/particles.star'

It looks like it's using gatewaydev instead of gateway. 

Before this, today I was updating some pages on dev & production and I might have brought down a file from production onto dev, and then re-pushed it up. Where would this option be related to /projects/cosmic2/gatewaydev ?

**Comment by kenneth59715** [comment]
The globus directory is specified in build.properties.  Maybe you
did a dev clean and build without sourcing /projects/cosmic2/kennethtest/dev/devenv?
Can you try a clean and build on the production side and see if that fixes it?

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
Scratch that.  I see a problem in comet_relion_submit.py:

grep gatewaydev comet_relion_submit.py
GLOBUSTRANSFERSDIR = '/projects/cosmic2/gatewaydev/globus_transfers'
REMOTESCRIPTSDIR = '/home/cosmic2/gatewaydev/remote_scripts'
        userdir='/projects/cosmic2/gatewaydev/globus_transfers/'+usernamedir
/home/cosmic2/gatewaydev/remote_scripts/cryoef_star_csv_2_dat.py %s >> stdout.txt 2>>stderr.txt
[cosmic2@comet-ln2 remote_scripts]$ pwd
/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
Oh! Right, yes, this is related to getting these paths specified during
build.

Good catch - I'll fix and will redeploy for now.
