### ISSUE TITLE
usage.sh fails for Comet after CentOS7 upgrade

### ISSUE THREAD

**Issue by kenneth59715** [cianfrocco-lab/COSMIC-CryoEM-Gateway#218]
./usage.sh
Can't locate DBD/Pg.pm in @INC (@INC contains: /usr/local/apps/tgusage-3.0-r1/perl-libs/lib/perl5/site_perl/5.8.0 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/cipres-tgusage line 23.
BEGIN failed--compilation aborted at /home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/cipres-tgusage line 23.

**Comment by mcianfrocco** [comment]
This is working, correct @kenneth59715 ?

**Comment by kenneth59715** [comment]
This should be working now.

**Comment by kenneth59715** [comment]
It should be working now.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
