### ISSUE TITLE
New output files

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#220]
@kenneth59715 will give us some XML examples

**Comment by kenneth59715** [comment]
For example, these stanzas can be added to a pisexml file to let the user download
either _tmplog or all *.txt files:

    <parameter type="Results">
      <name>tmplog</name>
      <attributes>
        <filenames>_tmplog</filenames>
      </attributes>
    </parameter>

         <parameter type="Results">
            <name>all_files</name>
            <attributes>
                <filenames>*.txt</filenames>
            </attributes>
        </parameter>
