### ISSUE TITLE
Email chron job info

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#222]
Chron job email to cosmic2support@umich.edu that has the following info: 

Daily email with
- total SU usage
- SU per user
- how many new users
- how much disk space per user 
- how many jobs submitted

**Comment by kenneth59715** [comment]
What time window should these numbers cover?  disk space is total regardless of
time created, I assume.  Should the other numbers be only new stuff from the previous
24 hours?

**Comment by mcianfrocco** [comment]
Hi Kenneth,

I've broken this down into subcategories and it's more specific: 

SUs: 
- SU usage (cumulative)
- SU usage (last 24 hours)
- SU per user (last 24 hours)

Users: 
- Number of new users (cumulative)
- Number of new users (last 24 hours)

Disk space
- Disk space usage (cumulative)
- Disk space per user (cumultative) 

Jobs
- Number of jobs submitted (cumulative)
- Number of jobs submitted (last 24 hours)

**Comment by monaw** [comment]
I have a couple of minor suggestions:

1. Remove "new" from "Number of new users (cumulative) 21"
2. Move the last 2 lines about job submission above the user listing...maybe under the SU lines?

thanks!

**Comment by mcianfrocco** [comment]
This is working.
