### ISSUE TITLE
total storage calculation incorrect

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#223]
Mike's account on dev shows almost 600 GB of storage after uploading a single directory that is only about 6 GB in size.

**Comment by monaw** [comment]
@mcianfrocco - I manually ran the sql statement on the dev database and indeed, the total comes out to over 600 GB:
+---------------------+-----------------+
| TOTAL_DOCUMENTS | TOTAL_LENGTH |
+---------------------+-----------------+
|                               113 | 642379996600 |
+---------------------+-----------------+

	Upon further checking, I see what the problem is.  The Class2D/ upload is 6 GB in size total.  However there are 106 *.star files in the job157/ subdirectory and since we are counting the entire upload size per *.star file, that resulted in 106 * 6 = 636 GB.

	I remember now that we had decided to count the star file with the full size of the upload directory since we were only expecting 1 star file.  But now that there can be multiple star files in the same directory, we need to count the size differently…

	Ideally the database should store the size of the individual star files and the total storage size we display should come from the filesystem.  It is slower going to disk to get a total, especially if the user has a lot of data…many tens of GB or larger.  But perhaps the performance hit won’t be that bad because we can do the query when the user first login and then cache that number in memory.  What do you think?

**Comment by mcianfrocco** [comment]
Hi @monaw - thanks for looking into this. Ah, I see the problem with the way we originally did this. I think we should try to just store the actual size of the files and to see if this works. If things get slow we can try a different way.

**Comment by monaw** [comment]
@mcianfrocco - ok so store the actual size of each *.star file in the directory.  What about the user total?  Should we go to disk to get that info each time the user logs in and then cache it while the user remains logged in?  Alternatively we can setup another cron job that will update the database size of each user's storage size once every 30 minutes or 1 hour or some other time lapse?

**Comment by mcianfrocco** [comment]
@monaw - yes we could just directly measure the amount being used when a user logs in; that seems to be the most direct instead of a chron job. Would that work?

**Comment by monaw** [comment]
@mcianfrocco - it might take several seconds to get this...is that delay during login acceptable?

**Comment by mcianfrocco** [comment]
Let's try it and then see if it's too slow.

**Comment by monaw** [comment]
part of this is fixed; the *.star file size now is the actual file size, not the directory size.
