### ISSUE TITLE
Tool creation issue

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#224]
Hi @kenneth59715 ,

I'm trying to create a new tool that will operate solely on text files (and output a text file for download). 

The only input required is text file uploaded via the web browser. The is one optional input which is another text file. 

With this type of tool, everything compiles but then I run into an error that says 'Internal error" on the web when I try to save the parameters in the job submission process. 

Is the tool expecting a certain type of input? How do I change this? When I add any other parameter (e.g. a switch that has a default value), I'm able to successfully submit the job.

Here is the new tool XML file: 
gateway_config/sdk/src/main/resources/pisexml/csparc2star.xml

Mike

**Comment by kenneth59715** [comment]
I added a couple of hardcoded attributes to the scheduler.conf section, and it
submits:
*** csparc2star.xml.broken      2020-01-13 12:00:04.975639379 -0800
--- csparc2star.xml     2020-01-13 12:01:35.513313664 -0800
***************
*** 39,46 ****
--- 39,48 ----
                                <code>
  
                                 "runhours=1\\n" . 
+                  "ChargeFactor=1.0\\n" .
                             "ntasks-per-node=1\\n" .
                                 "node_exclusive=1\\n" .
+                  "cores_per_node=1\\n" .
                                 "nodes=1\\n"
                                </code>
                        </format>

It completes, but the only output I see is a single line of path info.

**Comment by mcianfrocco** [comment]
Another tool issue @kenneth59715 - 

I just created a new tool on dev: 

gateway_config/sdk/src/main/resources/pisexml/auto_micassess.xml

After adding into tool-registry, when I try to build the tool I get this error: 

> INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sdk ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 52 resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ sdk ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 485 source files to /projects/cosmic2/kennethtest/dev/41.14/portal-R41.14/build/sdk/target/classes
> [INFO] /projects/cosmic2/kennethtest/dev/41.14/portal-R41.14/build/sdk/src/main/java/org/ngbw/sdk/common/util/Resource.java: Some input files use or override a deprecated API.
> [INFO] /projects/cosmic2/kennethtest/dev/41.14/portal-R41.14/build/sdk/src/main/java/org/ngbw/sdk/common/util/Resource.java: Recompile with -Xlint:deprecation for details.
> [INFO] /projects/cosmic2/kennethtest/dev/41.14/portal-R41.14/build/sdk/src/main/java/org/ngbw/sdk/database/Folder.java: Some input files use unchecked or unsafe operations.
> [INFO] /projects/cosmic2/kennethtest/dev/41.14/portal-R41.14/build/sdk/src/main/java/org/ngbw/sdk/database/Folder.java: Recompile with -Xlint:unchecked for details.
> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR : 
> [INFO] -------------------------------------------------------------
> [ERROR] /projects/cosmic2/kennethtest/dev/41.14/portal-R41.14/build/sdk/src/main/java/org/ngbw/sdk/tool/validation/auto_micassessValidator.java:[17,8] class micassessValidator is public, should be declared in a file named micassessValidator.java
> [INFO] 1 error
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 9.783s
> [INFO] Finished at: Tue Jan 14 08:09:12 PST 2020
> [INFO] Final Memory: 16M/193M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project sdk: Compilation failure
> [ERROR] /projects/cosmic2/kennethtest/dev/41.14/portal-R41.14/build/sdk/src/main/java/org/ngbw/sdk/tool/validation/auto_micassessValidator.java:[17,8] class micassessValidator is public, should be declared in a file named micassessValidator.java
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> mvn returned exit code 1
> /projects/cosmic2/kennethtest/dev/41.14/portal-R41.14/sdk/build.py returned exit code 1

**Comment by mcianfrocco** [comment]
@kenneth59715 - nevermind! I found the typo that caused the issue. Sorry for the bother.

**Comment by mcianfrocco** [comment]
ok! I'm back at the same type of error that i had originally. I created a new tool that does not have any input paramters other than the user-provided STAR file: 

gateway_config/sdk/src/main/resources/pisexml/auto_micassess.xml

When I try to submit this job, I get an internal error message b/c there are no parameters selected (since there aren't any to begin with). 

@kenneth59715 can you take a look? Test data will be using the COSMIC2 T20S Globus endpoint, then uploading the directory named mic_upload_test. This will populate one data file mic_upload_test/micrographs.star	 in the data list.

**Comment by kenneth59715** [comment]
Looks like the java code does not handle a tool without input parameters.  I put a couple
of checks into the java code in a Freemarker template file (Freemarker and the template
file is used to convert pisexml spec into .jsp, .java, etc. source files).  This change is
on dev server, hasn't moved to production, yet.

diff -c portal/src/main/codeGe
neration/FreemarkerTemplate/pise2validationJava.ftl gateway_config/portal/src/ma
in/codeGeneration/FreemarkerTemplate/pise2validationJava.ftl
*** portal/src/main/codeGeneration/FreemarkerTemplate/pise2validationJava.ftl  2
019-05-22 10:53:19.115231525 -0700
--- gateway_config/portal/src/main/codeGeneration/FreemarkerTemplate/pise2valida
tionJava.ftl    2020-01-15 12:19:20.484157981 -0800
***************
*** 44,53 ****
                for (String missing : missingRequired) {
                        errors.put(missing, "You must enter a value for \"" + mi
ssing + "\"");
                }
!               for (String param : parameters.keySet()) {
!                       String error = validate(param, parameters.get(param));
!                       if (error != null)
!                               errors.put(param, error);
                }
                return errors;
        }
--- 44,55 ----
                for (String missing : missingRequired) {
                        errors.put(missing, "You must enter a value for \"" + mi
ssing + "\"");
                }
!               if (parameters != null){
!                       for (String param : parameters.keySet()) {
!                               String error = validate(param, parameters.get(param));
!                               if (error != null)
!                                       errors.put(param, error);
!                       }
                }
                return errors;
        }
***************
*** 78,86 ****
        private Set<String> validateRequiredParameters(Map<String, String> parameters) {
                Set<String> required = new HashSet<String>(requiredParameters.size());
                required.addAll(requiredParameters);
!               for (String parameter : parameters.keySet()) {
!                       if (required.contains(parameter))
!                               required.remove(parameter);
                }
                return required;
        }
--- 80,90 ----
        private Set<String> validateRequiredParameters(Map<String, String> parameters) {
                Set<String> required = new HashSet<String>(requiredParameters.size());
                required.addAll(requiredParameters);
!               if (parameters != null){
!                       for (String parameter : parameters.keySet()) {
!                               if (required.contains(parameter))
!                                       required.remove(parameter);
!                       }
                }
                return required;
        }

**Comment by mcianfrocco** [comment]
ok great. @kenneth59715 - it seems this is fixed now for me.

**Comment by monaw** [comment]
oops, the above checkin was for GitHub issue #244, not this one...sorry
