### ISSUE TITLE
web upload limit unchecked

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#225]
SGCI security team found that our gateway's web upload says 200 mb max but allows bigger.  Mona verified this:

![Screen Shot 2020-01-15 at 12 10 50 PM](https://user-images.githubusercontent.com/18472048/72467808-9736f100-3790-11ea-95a5-93d2b2127b3d.png)

![Screen Shot 2020-01-15 at 12 14 09 PM](https://user-images.githubusercontent.com/18472048/72467820-9d2cd200-3790-11ea-9263-ba5d5c8b8b1a.png)

**Comment by mcianfrocco** [comment]
@kenneth59715 - is there way to actually limit this on the upload page? Or how do we limit this?

**Comment by kenneth59715** [comment]
I don't see a total web upload space limit check in CreateData.java,
but I think that's where it should go.  For that user, check to see
what globus upload limit is, then enforce the same limit for web uploads?

**Comment by mcianfrocco** [comment]
Is there a rule of thumb for this? Like practically we should limit it to
500 MB to save frustrations of people trying to upload larger files?


_________________________
Michael A. Cianfrocco, Ph.D.
Assistant Professor, Department of Biological Chemistry
Research Assistant Professor, Life Sciences Institute
University of Michigan
Pronouns: he, him, his

**Comment by kenneth59715** [comment]
I think the per-upload practical limit will vary a lot, depending on the
connection from the user to SDSC. I would let them try whatever they
want. If we want a total per-user limit, we could implement that.
Is there a typical dataset size for cryo-em?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
In this case, it's not a dataset, it would just be individual 3D
reconstructions that they would use for analyzing datasets.

Perhaps, then, we just remove the limit warning from the website?

_________________________
Michael A. Cianfrocco, Ph.D.
Assistant Professor, Department of Biological Chemistry
Research Assistant Professor, Life Sciences Institute
University of Michigan
Pronouns: he, him, his

**Comment by kenneth59715** [comment]
Sounds reasonable to me. Do you want to assign removal of warning to me?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
will do

**Comment by mcianfrocco** [comment]
Hi @kenneth59715 can you remove this error message?

**Comment by kenneth59715** [comment]
Okay, I'll dig into it.

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
Warning on upload limit has been removed in staging.  Not rolled into production, yet.
