### ISSUE TITLE
folder filename allows disallowed characters!

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#226]
SGCI security team found that our folder creation allows characters that it claims to not allow!

Mona verified this and created a folder with $$:

![Screen Shot 2020-01-15 at 12 25 27 PM](https://user-images.githubusercontent.com/18472048/72468510-30b2d280-3792-11ea-82a4-ba9c32fc995e.png)

![Screen Shot 2020-01-15 at 12 25 49 PM](https://user-images.githubusercontent.com/18472048/72468517-35778680-3792-11ea-90c7-902ce2ed1b99.png)

**Comment by kenneth59715** [comment]
I think the filename also gets checked in CreateData.java...

**Comment by kenneth59715** [comment]
modified struts.xml, folderForm.jsp and FolderManager.java to add a check
and return error to user.

**Comment by kenneth59715** [comment]
Not rolled into production, yet.
