### ISSUE TITLE
Check that we aren't deleting data in workspace

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#230]
Make sure workspace files aren't being deleted

**Comment by kenneth59715** [comment]
I looked through DeleteTasks.java and did not find anything that deletes in workspace.
The data deletes are through UserDataItem.delete() and UserDataDirItem.delete()
I think task.delete() will delete the working dir, but not ARCHIVE.  Haven't actually tested that.
