### ISSUE TITLE
change deployment of remote_scripts to not require editing of scripts

### ISSUE THREAD

**Issue by kenneth59715** [cianfrocco-lab/COSMIC-CryoEM-Gateway#236]
Currently, at least some of the scripts in remote_scripts require editing when moving from
dev to production.  It would be better to put dev or production specific variables in a
config file, then have the scripts read from that, rather than changing values in the scripts
by hand.

**Comment by kenneth59715** [comment]
I think the way to do this is via the instance specific rc file specified in
build.properties:comet.rc=/home/cosmic2/kennethlaptop/bashrc.dev (for kennethlaptop instance)
in remote_scripts, python or bash scripts can read env vars to localize to the instance:
GLOBUSTRANSFERSDIR = os.environ['GLOBUSTRANSFERSDIR']
REMOTESCRIPTSDIR = os.environ['REMOTESCRIPTSDIR']

then use those variables to customize paths or other actions.

**Comment by mcianfrocco** [comment]
Kenneth completed this successfully.
