### ISSUE TITLE
deleteTasksD fails to remove files in globus_transfers

### ISSUE THREAD

**Issue by kenneth59715** [cianfrocco-lab/COSMIC-CryoEM-Gateway#240]
user with many mrc files in two directories in globus_transfers.
These files and dirs are not removed by deleteTasksD.
Looks like the directories with many mrc files an no star file
are not tracked as UserDataDirItems.

**Comment by mcianfrocco** [comment]
@kenneth59715 is this resolved?

**Comment by kenneth59715** [comment]
I thought it was, but need to verify.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
Hi @kenneth59715 this may or may no be related, but I see many directories in both production and dev workspace with the prefix "NGBW-JOB-" that are old and haven't been deleted. 

Can I manually delete this using "rm -rf" ? Or is there a preferred way to remove?

Mike

**Comment by kenneth59715** [comment]
Anything in workspace can be deleted. If the Tasks are running
or completed before loading results back to the portal, then
some information could be lost.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
