### ISSUE TITLE
Stalled job submission on cosmic2dev

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#245]
Hi @kenneth59715 - 

I just tried submitting a job for the automated preprocessing tool and I can't view the status of the job. The task creation is fine and it creates a new task, but when I click on 'View status' the page just hangs. 

It's weird b/c @yilaili was able to run this without issue on his account. 

If you want to test this, just upload the directory 'micrograph_uploading' from the T20S shared globus endpoint for testing cosmic2 that we usually use. Don't expand the directory, just click on this name. This will upload a directory of files and then show a single .star file as the data file. Use this data file as input for Automated Preprocessing and then provide the input parameters: 0.66 for pixel size, 300 keV for accelerating voltage and 2.7 for the spherical aberration on the input parameter page. 

Thanks,
Mike

**Comment by kenneth59715** [comment]
Not sure if this is the issue, but I'm seeing these messages in
submitJob.log.  I'll investigate and run tests tomorrow.

Mar 22 2020 19:23:01 [read-6] DEBUG -         BaseProcessWorker:687   [task=26, job=COSMIC2-JOB-PARTICLE_PICKING_CTF_MOTION-52A35C105B2440D8BC2DA0F663F69C3C] | Working directory [ /projects/cosmic2/gatewaydev/workspace/COSMIC2-JOB-PARTICLE_PICKING_CTF_MOTION-52A35C105B2440D8BC2DA0F663F69C3C/ ] moved to directory [ /projects/cosmic2/gatewaydev/workspace/FAILED/COSMIC2-JOB-PARTICLE_PICKING_CTF_MOTION-52A35C105B2440D8BC2DA0F663F69C3C/ ].
Mar 22 2020 19:23:01 [read-6] ERROR -              TaskInitiate:273   [task=26, job=COSMIC2-JOB-PARTICLE_PICKING_CTF_MOTION-52A35C105B2440D8BC2DA0F663F69C3C] |
java.lang.Exception: Error submitting job: Traceback (most recent call last):
  File "/home/cosmic2/gatewaydev/remote_scripts/comet_relion_submit.py", line 1045, in <module>
    """%(partition,jobname, runtime, mailuser, args['account'],jobdir,runcmd,REMOTESCRIPTSDIR,username,out_destination,outdir,runcmd,'')
TypeError: not enough arguments for format string

    at org.ngbw.sdk.tool.SSHExecProcessWorker.submitJob(SSHExecProcessWorker.java:288)

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
Mike,

 The Cosmic T20S endpoint is giving me an error:
Error, unable to get file count on the source endpoint ID, "COSMIC2 T20S".
Can you send me the file or put it somewhere on Comet where I can read it?

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
I did do a git pull on dev in remote_scripts on comet last Thu or Fri.  That may have wiped
out uncommitted changes.  Not sure if that is an issue.

**Comment by mcianfrocco** [comment]
Hi Kenneth, 

It's weird - the issue has resolved itself. Maybe something in the server was hanging last night w/ memory? EIther way it's not an issue so I'll close for now. 

RE: T20S endpoint, that is working for me - try again.
