### ISSUE TITLE
if logged in to app.globus.org then login fails with mismatched oauth state

### ISSUE THREAD

**Issue by kenneth59715** [cianfrocco-lab/COSMIC-CryoEM-Gateway#246]
I had an open browser window to https://app.globus.org.  I tried to go to
the staging home page, but got an error page.  The log indicated mismatched
oauth state:

Jun 01 2020 08:40:24 [xec-21] DEBUG -        AuthCallbackAction:70     | MONA: entered AuthCallbackAction.globuslogin()
Jun 01 2020 08:40:24 [xec-21] DEBUG -        AuthCallbackAction:97     | MONA: endpoint_activation_uri = https://app.globus.org/file-manager?origin_id=:endpoint_id
Jun 01 2020 08:40:24 [xec-21] DEBUG -               NgbwSupport:1044   | Mismatching Oauth States: org.apache.oltu.oauth2.common.exception.OAuthSystemException: Mismatching Oauth States
org.apache.oltu.oauth2.common.exception.OAuthSystemException: Mismatching Oauth States
    at edu.sdsc.globusauth.action.AuthCallbackAction.globuslogin(AuthCallbackAction.java:394)

Logging out of app.globus.org allowed me to log in to staging.

**Comment by monaw** [comment]
I ran into this also, in reverse...app.globus.org gave me the error.  I think ours and Globus session info is somehow clashing in the browser; needs further investigation

**Comment by kenneth59715** [comment]
Was able to click Home, the Login and that second time through worked, even through
I left myself logged in to app.globus.org.
