### ISSUE TITLE
Globus upload to shared space fails with mkdir permission denied

### ISSUE THREAD

**Issue by kenneth59715** [cianfrocco-lab/COSMIC-CryoEM-Gateway#247]
When trying to upload to staging, /projects/cosmic2/gatewaydev/globus_transfers/kenneth@globusid.org,
the transfer fails.  Details in app.globus.org in the event log for the transfer has
an error that gridFTP returned Permission denied on mkdir.  The event says the command
was MKD /projects/cosmic2/gatewaydev

**Comment by mcianfrocco** [comment]
@monaw is this due to a new user upload error?
