### ISSUE TITLE
Update how star files are found

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#252]
Due to user upload behavior, we now want to traverse directories until the first *.star file is found and then stop going deeper.

For example, if we have the following upload hierarchy:

	parent 1/
		child 1/
			a.star
			grandchild 1/
				b.star
		child 2/
			grandchild 2/
				c.star
		child 3/
			grandchild 3/
				great grandchild 3/
					d.star
		e.star
	parent 2/
		child 4/
			grandchild 5/
				grandchild 6/
					f.star

We want to find the following star files: a.star, (not b.star), c.star, d.star, e.star and f.star

**Comment by monaw** [comment]
algorithm:

```
if directory has file entries
    remove directory and save files
else if directory has subdirectories
    remove directory
else
    traverse directory (save *.star & traverse subdirectory but stop traversing when a *.star file is found or no more subdirectory to traverse)
```

**Comment by monaw** [comment]
@mcianfrocco - what if the user wants to upload some reference map (*.mrc) files?   Since they end in the same extension as the image files to be processed, how would the code know the difference since I presume we still want to show the reference map files in the listing but not the image data files?

**Comment by mcianfrocco** [comment]
Hi Mona,

Right now we'd request that users 1) upload individual MRC files or 2) use
STAR files and upload MRC volumes the same way we upload stacks. So, I
don't think we should do anything specific for volumes at this point.

Mike

_________________________
Michael A. Cianfrocco, Ph.D.
Assistant Professor, Department of Biological Chemistry
Research Assistant Professor, Life Sciences Institute
University of Michigan
Pronouns: he, him, his

**Comment by monaw** [comment]
**Test 1:**
![Screen Shot 2020-09-29 at 5 52 19 PM](https://user-images.githubusercontent.com/18472048/94631218-ab6a4200-027c-11eb-8e4f-f597a5884b79.png)
produces:
![Screen Shot 2020-09-29 at 5 51 16 PM](https://user-images.githubusercontent.com/18472048/94631234-b58c4080-027c-11eb-92ec-e840d6077cd8.png)

**Test 2:**
![Screen Shot 2020-09-29 at 6 19 55 PM](https://user-images.githubusercontent.com/18472048/94632883-95f71700-0280-11eb-99ac-10f18d97ec31.png)
produces:
![Screen Shot 2020-09-29 at 6 23 03 PM](https://user-images.githubusercontent.com/18472048/94632978-d8b8ef00-0280-11eb-9559-e13b33bc454b.png)

**Test 3**
![Screen Shot 2020-09-29 at 6 24 40 PM](https://user-images.githubusercontent.com/18472048/94633063-1c135d80-0281-11eb-8242-e89b34929567.png)
produces (same as Test 2):
![Screen Shot 2020-09-29 at 6 25 52 PM](https://user-images.githubusercontent.com/18472048/94633122-3baa8600-0281-11eb-8361-ece7ab3199be.png)

**Comment by monaw** [comment]
Now if we change the source endpoint path to default "/~/" and additional grand parents directories and one sibling star file:

```
COSMIC2/
        data/
                data.star
                parent 1/
                	child 1/
                		a.star
                		grandchild 1/
                			b.star
                	child 2/
                		grandchild 2/
                			c.star
                	child 3/
                		grandchild 3/
                			great grandchild 3/
                				d.star
                	e.star
                parent 2/
                	child 4/
		grandchild 5/
			grandchild 6/
				f.star
```

**Test 1:**

![Screen Shot 2020-09-29 at 6 40 12 PM](https://user-images.githubusercontent.com/18472048/94633795-4108d000-0283-11eb-83c7-291eebecf6cf.png)

produces:

![Screen Shot 2020-09-29 at 6 54 54 PM](https://user-images.githubusercontent.com/18472048/94634598-50891880-0285-11eb-8648-3cd7f6155826.png)

**Test 2:**

![Screen Shot 2020-09-29 at 6 56 10 PM](https://user-images.githubusercontent.com/18472048/94634672-83cba780-0285-11eb-8146-5f8c4213adab.png)

produces (same result as Test 1 above):

![Screen Shot 2020-09-29 at 6 57 42 PM](https://user-images.githubusercontent.com/18472048/94634748-b675a000-0285-11eb-965e-d9da59a809a0.png)

**Test 3:**

![Screen Shot 2020-09-29 at 7 05 44 PM](https://user-images.githubusercontent.com/18472048/94635166-dbb6de00-0286-11eb-9a36-3ca79c30b8b4.png)

produces:

![Screen Shot 2020-09-29 at 7 07 41 PM](https://user-images.githubusercontent.com/18472048/94635279-22a4d380-0287-11eb-8bbf-00a8c87c8340.png)

**Test 4:**

![Screen Shot 2020-09-29 at 7 10 32 PM](https://user-images.githubusercontent.com/18472048/94635468-8fb86900-0287-11eb-8927-4785061fd79f.png)

produces:

![Screen Shot 2020-09-29 at 7 12 02 PM](https://user-images.githubusercontent.com/18472048/94635525-ae1e6480-0287-11eb-9948-aff6e93b9a14.png)

**Comment by mcianfrocco** [comment]
Pushed to production
