### ISSUE TITLE
Github permissions error on cosmic2dev server github repo

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#262]
Hi @kenneth59715  - 

I'm trying to check in a new tool into our github repo from dev, but I'm getting a permissions issue with Github: 

(gatewayVE)[cosmic2-gw@cosmic2dev gateway_config]$ git pull
error: insufficient permission for adding an object to repository database .git/objects
fatal: git write-tree failed to write a tree

Do you know how to fix this? It seems like a chown permissions issue and I'm not sure exactly how to fix it. 

I found this help page: https://ducfilan.wordpress.com/2017/09/26/git-pull-error-error-insufficient-permission-for-adding-an-object-to-repository-database-gitobjects/

Mike

**Comment by kenneth59715** [comment]
Interesting! What command did you run and as which github user?
I usually git push from dev to github...

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
logged in as cosmic2-gw and using my account name mcianfrocco

**Comment by mcianfrocco** [comment]
It looks like there should be a .git folder which is missing from the github directory portal-R41.14/gateway_config

**Comment by kenneth59715** [comment]
I'll try the push as my github user.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
I think gateway_config is a symlink to
/projects/cosmic2/kennethtest/dev/41.14/COSMIC-CryoEM-Gateway/gateway_config
so the relevant .git is
/projects/cosmic2/kennethtest/dev/41.14/COSMIC-CryoEM-Gateway/.git

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
There are a number of directories with no group-write in

/projects/cosmic2/kennethtest/dev/41.14/COSMIC-CryoEM-Gateway/.git/objects

I think these are owned by mona. Probably need to add group write to these.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
Can you do that or does Mona have to do that?

**Comment by kenneth59715** [comment]
Okay, try it now. I did a mv and cp -ipr back, so the dirs should
be writable.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
Fixed! Thanks!
