### ISSUE TITLE
Progress bar for uploads

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#263]
Is it possible to have a progress bar for browser uploads?

**Comment by kenneth59715** [comment]
I don't know, I can investigate.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
Looks like there is a suggested way to do this.
https://stackoverflow.com/questions/9428977/file-upload-progress-bar-in-struts2

**Comment by mcianfrocco** [comment]
Not going to fix
