### ISSUE TITLE
Increase number of characters shown in pull down menu for data item in task

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#264]
Can we increase the length of characters shown in pull down menus? Right now it truncates long file names: 

<img width="960" alt="Screen Shot 2020-09-04 at 1 54 59 PM" src="https://user-images.githubusercontent.com/1464469/92271719-4ce8b880-eeb6-11ea-800b-74e3acc070d7.png">

**Comment by kenneth59715** [comment]
Hmmm, I'm not seeing anything in the pulldown.  Maybe something in my browser config does not
support that...

**Comment by kenneth59715** [comment]
What code generates that pulldown?  Is it dynamically generated?

**Comment by kenneth59715** [comment]
NgbwSupport.java has a constant, TEST_LENGTH, that gets used to truncateText
for dropdowns.  Set this large to prevent missing text.  I set this to 400 in staging,
but have not built or tested, yet.

**Comment by kenneth59715** [comment]
TEXT_LENGTH

**Comment by mcianfrocco** [comment]
Works. @kenneth59715 can you commit to the github repo and then close the issue?

**Comment by kenneth59715** [comment]
Okay, it's in github repo.
