### ISSUE TITLE
globus upload doesn't find .star file in nested directory?

### ISSUE THREAD

**Issue by kenneth59715** [cianfrocco-lab/COSMIC-CryoEM-Gateway#280]
I put a job directory with star file one level down, and this did not show up in datalist:
on staging,
seems to fail to find job007.nested, inside job007:
[kenneth@comet-ln3 in3]$ ls -R testnested
testnested:
Extract

testnested/Extract:
Icon  job007  job007.dup

testnested/Extract/job007:
default_pipeline.star  Movies                              run.err
Icon                   note.txt                            run.job
job007.nested          particles_cosmic_path_updated.star  run.out
job_pipeline.star      particles.star

testnested/Extract/job007/job007.nested:
default_pipeline.star  note.txt                            run.job
Icon                   particles_cosmic_path_updated.star  run.out
job_pipeline.star      particles.star
Movies                 run.err

testnested/Extract/job007/job007.nested/Movies:
20170629_00021_frameImage.mrcs  20170629_00024_frameImage.mrcs
20170629_00022_frameImage.mrcs  20170629_00025_frameImage.mrcs
20170629_00023_frameImage.mrcs  Icon

testnested/Extract/job007/Movies:
20170629_00021_frameImage.mrcs  20170629_00024_frameImage.mrcs
20170629_00022_frameImage.mrcs  20170629_00025_frameImage.mrcs
20170629_00023_frameImage.mrcs  Icon

testnested/Extract/job007.dup:
default_pipeline.star  note.txt                            run.job
Icon                   particles_cosmic_path_updated.star  run.out
job_pipeline.star      particles.star
Movies                 run.err

testnested/Extract/job007.dup/Movies:
20170629_00021_frameImage.mrcs  20170629_00024_frameImage.mrcs
20170629_00022_frameImage.mrcs  20170629_00025_frameImage.mrcs
20170629_00023_frameImage.mrcs  Icon

**Comment by mcianfrocco** [comment]
Related to #252
