### ISSUE TITLE
Expanse intermediate results

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#292]
@kenneth59715 - intermediate results are not working on the dev server running on Expanse. Perhaps a wrong hardcoded path?

**Comment by kenneth59715** [comment]
It's working for the sleep tool. Can you point me to the tool that
is failing and how to run a test? By the way, the live viewing may
be slower than on comet. The trilead ssh interaction java package
doens't work with the encryptions that expanse accepts, so I had
to drop in a commandline ssh file handler.

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
