### ISSUE TITLE
Displayed time from Globus during file transfer

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#30]
Is the displayed time in the Transfer status page UTC? I think it probably is. 

Could we indicate this to the user, by providing 'UTC' somewhere on the line: 

> Request Time: 2017-05-06 04:48:11+00:00

Perhaps even: 

> Request Time: 2017-05-06 04:48:11+00:00 UTC

**Comment by cdesyoun** [comment]
Hi @mcianfrocco , I will add "UTC" into the time field in the transfer status page as the display time.

**Comment by monaw** [comment]
@cdesyoun - Minor thing, if there is no completion time yet, the display says "null UTC"...see attached image.  May I suggest just leaving the display blank if there is no completion time?  Unless Mike want something else?

![screen shot 2017-05-12 at 12 31 13 pm](https://cloud.githubusercontent.com/assets/18472048/26013909/36c09e7c-370f-11e7-8854-4f57adb743ee.png)

**Comment by mcianfrocco** [comment]
A blank space is OK with me
