### ISSUE TITLE
Missing information in TransferRecord

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#43]
Hi Choonhan, there is a  new problem...it seems that some of the info originally in the TransferRecord are now missing, like DIRECTORY_NAMES and FILE_NAMES.  This also was working 2 months ago...

**Comment by cdesyoun** [comment]
I looked at the mysql database.
I could see my directory names which I transferred files yesterday.

MySQL [cosmic2_sg]> select tr_id, file_names, directory_names from transfer_record where tr_id between 114 and 119;
+-------+--------------------------------------------------+---------------------------+
| tr_id | file_names                                       | directory_names           |
+-------+--------------------------------------------------+---------------------------+
|   114 | example.star|transfer-api-client-java-master.zip | NULL                      |
|   115 | RIIbchimeraholo.pdb                              | NULL                      |
|   116 | RIIbchimeraholo.pdb                              | NULL                      |
|   117 | NULL                                             | globus-sample-data-portal |
|   118 | NULL                                             | cosmic2                   |
|   119 | NULL                                             | cosmic2                   |
+-------+--------------------------------------------------+---------------------------+
6 rows in set (0.00 sec)

MySQL [cosmic2_sg]>

**Comment by monaw** [comment]
ah sorry, my bad!  i uploaded a directory and was looking at the file field...sorry for the noise...
