### ISSUE TITLE
Usage statistic tracking?

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#48]
@monaw - are we tracking statistics yet for number of users, jobs submitted, etc?

**Comment by monaw** [comment]
Reply from Mark:

> Yes, I run queries using sql.
> I use MySQL workbench.
> I can send you stock queries I use if you like. Just tell me what you are looking to collect.
> And yes, I definitely manipulate the data in Excel.
> Like every good biologist of a certain age.

**Comment by monaw** [comment]
Also from Mark Miller:

It very much depends on what you are trying to accomplish.
Here is the query we use to report to XSEDE each quarter.
The lines that are commented out can be commented in to make self explanatory modifcations.
You can add statements specific to country, or tool name, etc.
 
There are ways to ask how much a user has stored (you have that already I think).
And you and ask about specific users, or sort by country instead of username, etc.
Let me know if there are specific things you are thinking about.
 
 
```
select                  users.username, users.INSTITUTION, users.COUNTRY, users.USER_ID, job_stats.EMAIL,
sum(job_stats.SU_CHARGED) as total_sus,
count(job_stats.TASK_ID  ) as num_jobs
from job_stats, users where
 
users.user_id = job_stats.user_id AND
#job_stats.resource != "TSCC" and
( job_stats.date_submitted >= '2016-1-01' and job_stats.date_submitted <= '2016-12-31' )
#and users.USERNAME not like "%guest%"
group by users.username, job_stats.email,                      
"username institution country user_id email sum(job_stats.SU_CHARGED)"
```

**Comment by monaw** [comment]
More from Mark...
[sql_query.zip](https://github.com/cianfrocco-lab/COSMIC-CryoEM-Gateway/files/1520162/sql_query.zip)

**Comment by mcianfrocco** [comment]
Thanks Mona! I'm sorry for such a naiive question - but how to I run the code that Mark sent you in the above example?

**Comment by mcianfrocco** [comment]
Nevermind - got it! Just figured out how to specify the database name, my bad. Thanks for getting this info - this will do it!

**Comment by mcianfrocco** [comment]
I got the above code from Mark to run, but I only see you as a user, even though I've submitted jobs: 

Database changed
+----------+-------------+---------+---------+---------------+-----------+----------+
| username | INSTITUTION | COUNTRY | USER_ID | EMAIL         | total_sus | num_jobs |
+----------+-------------+---------+---------+---------------+-----------+----------+
| mona     | UCSD SDSC   | US      |       1 | [removed by Mike] |      NULL |       29 |
+----------+-------------+---------+---------+---------------+-----------+----------+
1 row in set (0.00 sec)

Any thoughts why?

**Comment by monaw** [comment]
@mcianfrocco - can you give me the SQL code you used?

**Comment by mcianfrocco** [comment]
It was the one that Mark provided above: 

```
use cosmic2_sg
select  users.username, users.INSTITUTION, users.COUNTRY, users.USER_ID, job_stats.EMAIL,
sum(job_stats.SU_CHARGED) as total_sus,
count(job_stats.TASK_ID  ) as num_jobs
from job_stats, users where
 
users.user_id = job_stats.user_id AND
#job_stats.resource != "TSCC" and
( job_stats.date_submitted >= '2016-1-01' and job_stats.date_submitted <= '2016-12-31' )
#and users.USERNAME not like "%guest%"
group by users.username, job_stats.email,                      
"username institution country user_id email sum(job_stats.SU_CHARGED)"
```

**Comment by mcianfrocco** [comment]
FYI job SUs aren't being recorded. If you look at the database: 

```
MySQL [cosmic2_sg]> SELECT SU_CHARGED from job_stats;
+------------+
| SU_CHARGED |
+------------+
|       NULL |
|       NULL |
|       NULL |
|       NULL |
|       NULL |
|       NULL |
|       NULL |
|       NULL |
|       NULL |
|       NULL |
|       NULL |
|       NULL |
|       NULL |
|       NULL |
|       NULL |
```

**Comment by monaw** [comment]
this is linked to issue #70 cpu usage display...

**Comment by monaw** [comment]
tech notes

1. job_stats is the database table that contains the charged su info
```
MySQL [cosmic2_sg]> describe job_stats;
+------------------+---------------+------+-----+---------+-------+
| Field            | Type          | Null | Key | Default | Extra |
+------------------+---------------+------+-----+---------+-------+
| JOBHANDLE        | varchar(255)  | NO   | PRI | NULL    |       |
| RESOURCE         | varchar(100)  | NO   |     | NULL    |       |
| TASK_ID          | bigint(20)    | NO   |     | NULL    |       |
| USER_ID          | bigint(20)    | NO   |     | NULL    |       |
| TOOL_ID          | varchar(100)  | NO   |     | NULL    |       |
| EMAIL            | varchar(200)  | NO   |     | NULL    |       |
| SUBMITTER        | varchar(1023) | NO   |     | UNKNOWN |       |
| REMOTE_JOB_ID    | varchar(1023) | YES  |     | NULL    |       |
| TG_CHARGE_NUMBER | varchar(100)  | YES  |     | NULL    |       |
| DATE_ENTERED     | datetime      | NO   |     | NULL    |       |
| DATE_SUBMITTED   | datetime      | YES  |     | NULL    |       |
| DATE_TERMINATED  | datetime      | YES  |     | NULL    |       |
| SU_PREDICTED     | bigint(20)    | YES  |     | NULL    |       |
| SU_COMPUTED      | bigint(20)    | YES  |     | NULL    |       |
| SU_CHARGED       | bigint(20)    | YES  |     | NULL    |       |
| SU_OVERRIDE      | int(11)       | YES  |     | NULL    |       |
| APPNAME          | varchar(30)   | NO   |     |         |       |
+------------------+---------------+------+-----+---------+-------+
17 rows in set (0.00 sec)
```
2. /projects/cosmic2/gateway/scripts/usage.sh needs to be run to get the charge information from XSEDE and update the gateway database.  Example _usage.sh 01-01-2015_

**Comment by monaw** [comment]
tech notes:

1. login to cosmic2 vm as community account
2. cdscripts
3.
