### ISSUE TITLE
User-provided allocation

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#49]
Is the gateway setup to allow users to provide their own XSEDE allocation? Would they put it into their profile? Or where does it go?

**Comment by monaw** [comment]
Reply from Mark:

> There are two steps:
> 
> First, the user gets an allocation, and the PI adds cipres as an authorized user.
> Second, you add the users allocation ID number to the database in place of the community account.
> We have a script for that.
> 
> Add user personal allocation as follows:
> - log into portal2prod@qball2.sdsc.edu
> - run: userTgAllocation <username> <charge number>
> 
> It's easiest if the person tells you their username, but in this case, since I had her email but not her username I first ran: updateLastLogin -f --email=emurr001@ucr.edu and that told me the username associated with that email address.
> 
> To reset a users allocation
> Log in to portal2prod@qball2.sdsc.edu<mailto:portal2prod@qball2.sdsc.edu> and run
> userTgAllocation <username> NULL
> to change her back to using the cipres community account.
> Run
> userTgAllocation <username>
> to confirm.

**Comment by monaw** [comment]
@mcianfrocco - we need to test this to see if it still works for us.  Do you have another allocation account we can try your gateway account with?

**Comment by mcianfrocco** [comment]
@monaw - yes I have another account to which I am a part of. let me know when you are ready to test this out
