### ISSUE TITLE
Set storage limit for individual users

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#53]

**Comment by monaw** [comment]
There is a mechanism to set user storage quota.   In gateway_config/build.properties, there is:

```
# Values used for user data storage size display (150 GB and 120 GB)
 user.data.size.max=161061273600
 user.data.size.warn=128849018880
```
However, I'm not sure how/where this tracking is done and whether our directory-based dataset is being calculated correctly.  Need some testing...

**Comment by monaw** [comment]
yes, actually i added that mechanism to CIPRES last year (:  let me check to see if it is working in our gateway...

**Comment by monaw** [comment]
ok, warning is working; i did a test and set the value to about 1 GB (max is still 150GB) and here is what i got...
![screen shot 2018-01-18 at 5 39 37 pm](https://user-images.githubusercontent.com/18472048/35130641-d4e5e1de-fc76-11e7-8cb7-f4ab7bf0c792.png)

**Comment by monaw** [comment]
ok, max is also working (i changed max to about 4 GB)...
![screen shot 2018-01-18 at 5 43 38 pm](https://user-images.githubusercontent.com/18472048/35130724-390f6b30-fc77-11e7-8e9c-5fb51c93111a.png)

**Comment by mcianfrocco** [comment]
Hi Mona - great! 

Let's set the size warning at 50 GB and max at 100 GB.

**Comment by monaw** [comment]
Done, user.data.size.max=107374182400 and user.data.size.warning = 53687091200

**Comment by mcianfrocco** [comment]
Yes - size of the directory. 

BTW where are those parameters located in the code?

**Comment by monaw** [comment]
By the way, this limit is for ALL users, not individual users.  I presume you still want to do individual user limit?

The 2 parameters are set in gateway_config/build.properties

**Comment by mcianfrocco** [comment]
Ok great thanks - a per-user limit might be nice, but don't work on it, we are under a time crunch!

**Comment by monaw** [comment]
@mcianfrocco - ok, the gateway is now using the directory size for display and calculation and the "Total Storage" number on the left column now includes all directories as well as files.

Please verify by doing a new directory upload; note, previously uploaded directory size has NOT been changed but going forward the size should be correct.

**Comment by mcianfrocco** [comment]
Hi @monaw - I created a new directory and uploaded some data. I see the display in the data list but not in the summary size. (Although on a previous directory I saw that it was working, but since then I have deleted that directory)

![size](https://user-images.githubusercontent.com/1464469/35760956-e14934d0-0851-11e8-820b-f4b8e72f152b.png)

**Comment by monaw** [comment]
ah, i see the problem...asking Paul about the DB query for the join...

**Comment by monaw** [comment]
@mcianfrocco - ok, the DB query has been modified and the "Total Storage" should be working for you now .  Please login and verify...

**Comment by monaw** [comment]
@mcianfrocco - when you get a chance, please verify that the storage total is also working for you, thanks.

**Comment by mcianfrocco** [comment]
storage listing is working for me

**Comment by monaw** [comment]
terrific, closing this issue then
