### ISSUE TITLE
Typo on Task creation 

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#61]
'1 Inputs Set' should read '1 Input Set'

![error](https://user-images.githubusercontent.com/1464469/31867664-b353b0d2-b761-11e7-83f9-a6c1a1921a3e.png)

**Comment by monaw** [comment]
Fixed:

![screen shot 2017-12-04 at 6 24 57 pm](https://user-images.githubusercontent.com/18472048/33586889-7a3950c8-d920-11e7-9b3f-204a6d68f6a3.png)
