### ISSUE TITLE
Link in completion email is incorrect

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#62]
Completion email has link: http://cosmic2.sdsc.edu/gateway

Whereas it should actually read: https://cosmic2.sdsc.edu:8443/gateway

**Comment by monaw** [comment]
@mcianfrocco - where is this completion email link?

**Comment by mcianfrocco** [comment]
As in, where is it specified in the code?

**Comment by monaw** [comment]
um, i'm not sure where this change you want to happen is currently...is it in the gateway UI somewhere?  If yes, which page?

**Comment by mcianfrocco** [comment]
Hi Mona - it's in an email sent by the gateway to the user after the job finishes. 

The link is: 
http://cosmic2.sdsc.edu/gateway

And when I click it, it starts an automatic download of an empty file called 'gateway'

**Comment by monaw** [comment]
@mcianfrocco - Ok, it should now go to https://cosmic2.sdsc.edu/gateway which should work.  Please verify.  Sorry i cannot verify as I don't seem to be getting those emails...

**Comment by monaw** [comment]
@mcianfrocco - do you mean the following completion email:

![screen shot 2018-03-13 at 5 40 58 pm](https://user-images.githubusercontent.com/18472048/37377212-ce99b848-26e5-11e8-8cff-0e162d4b628b.png)

If yes, it has been fixed, please verify, thanks!

**Comment by mcianfrocco** [comment]
Hi Mona, 

Yes - this is the email and I'm not sure if the link works but that should be it

**Comment by monaw** [comment]
@mcianfrocco - I just verified that the email is now going to https://cosmic2.sdsc.edu/gateway
