### ISSUE TITLE
Interactive clicking of directories for finding files to transfer

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#63]
Hi @cdesyoun - you originally designed the globus transfer page on COSMIC to require users to type in the path of the directory. 

I noticed on the Modern Research Data Portal (demo from Globus) that their transfer web page had links that were clickable for directories, allowing the user to navigate into directories: 

https://mrdp.globus.org:5000/transfer

Is it possible to have this in the COSMIC2 gateway?

**Comment by monaw** [comment]
Yes, I think this would be a better solution.  There is more info about this at https://docs.globus.org/api/helper-pages/browse-endpoint/

**Comment by monaw** [comment]
@cdesyoun - FYI, one thing that I’m adding which will impact your Globus transfer is that I am adding a mechanism to disable user from being able to transfer/upload files.  I am planning to add a column in the user table, can_upload (similar to current can_submit field) and if that value is false, the user will NOT be able to transfer/upload.  There will be a new function in the User object which your code can query to see if the user is allowed to upload or not and if not, do NOT allow them to transfer.  We can discuss more details when you get to that point.
