### ISSUE TITLE
CIPRES user message RE: country of user

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#64]
Message popped up requesting country information for users and used 'CIPRES' as the gateway name. Needs to be updated.

**Comment by mcianfrocco** [comment]
Just to show a screenshot. New users are apparently shown this: 

![cipres](https://user-images.githubusercontent.com/1464469/37379130-9147221e-2708-11e8-84b1-a37de53f2e51.png)


Could we change to COSMIC2?

**Comment by monaw** [comment]
@mcianfrocco - ok, i've changed the text there and found a few more places and changed them also.  i can't get this message to popup for me to verify the update; how did you get it to show?

**Comment by mcianfrocco** [comment]
It shows up for new users - if you create a new account and then try, you will see it.

**Comment by monaw** [comment]
hmm, how does one create a new account?  i should know this but can't find the way...can you check to see if the text now has COSMIC2 instead of CIPRES?

**Comment by monaw** [comment]
@mcianfrocco - ok, the window showed up for me after i logged in a second time and the text is now updated:

![screen shot 2018-03-15 at 4 38 20 pm](https://user-images.githubusercontent.com/18472048/37496469-f2c5a9ee-286f-11e8-871a-6283725bf7e8.png)
