### ISSUE TITLE
Change name of Globus buttons 

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#68]
1) Since Globus is actually just syncing between sources - I think we should change teh 'Transfer' Button to say 'Sync'. This will make it more intuitive when users start moving data back and forth

2) On the Data summary page where users click 'Globus upload', I'd like it changed to 'Globus upload/download' so that users know this is where they go to download results when downloading back to local storage

**Comment by monaw** [comment]
1. Done:

![screen shot 2017-12-04 at 6 16 24 pm](https://user-images.githubusercontent.com/18472048/33586672-53f346ea-d91f-11e7-831a-5122e0e812d8.png)

2. Done:

![screen shot 2017-12-04 at 6 15 40 pm](https://user-images.githubusercontent.com/18472048/33586678-5e338ea8-d91f-11e7-9100-9b29ca3d1008.png)
