### ISSUE TITLE
Tasks page: CPU-usage & help info do not work 

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#70]
On the Tasks page, the CPU usage value seems wrong:

![cpu-usage](https://user-images.githubusercontent.com/1464469/32034055-4cf437f6-b9de-11e7-8b3e-3acc5c52f0d8.png)

And the 'Explain this' help link is broken

**Comment by monaw** [comment]
For the link, it currently will go to http://cosmic-cryoem.org/help/cpu_help.  Can a page be setup or should we remove the link or point it to somewhere else?

**Comment by mcianfrocco** [comment]
Created page - link now works.

**Comment by monaw** [comment]
@mcianfrocco - question for you, is TG-MCB140257 associated with the gateway charge account csd547?  which one is used when a job is submitted?  What about TG-MCB170058?

**Comment by monaw** [comment]
ok, i think the cpu accounting is now working:

![screen shot 2018-02-15 at 3 32 44 pm](https://user-images.githubusercontent.com/18472048/36286763-f688a894-1265-11e8-8b63-803ffc432fab.png)

Please verify that it is working for you.

Which account do you want to use, TG-MCB140257 or TG-MCB170058.  By the way, is this hard-coded into your backend script?  Do you want it to be passed to the script from the command line?

**Comment by mcianfrocco** [comment]
Hi @monaw - we use csd547 and it is linked to TG-MCB170058.

Regarding usage, I'd like to have the choice to add per-user XSEDE accounts such as using the approach we mentioned in #49 . So, whatever we need to code so that if we run the suggested code from Mark the account is passed along.

**Comment by mcianfrocco** [comment]
Hi Mona - I just fixed the bug in the code that was interrupting submission, and now jobs are running again successfully. The output is still not being ingested corrected, it gets stuck at "Status
LOAD_RESULTS". 

That said, the CPU usage number did not change for me after running this. 

Mike

**Comment by monaw** [comment]
@mcianfrocco - ok, every 30 minutes.
question for you, when the script submits the relion job to run, does it specify the account it is run under?  can you confirm that it is running under the cosmic2 account?
i'm asking because I submitted a few jobs yesterday and they were successful according to the gateway but when i query the job account database, it says no jobs were ran by cosmic2 user for the past month!

**Comment by monaw** [comment]
oh wow, ok something is going south because here is one of the jobs i ran yesterday on the gateway:

![screen shot 2018-05-25 at 1 51 28 pm](https://user-images.githubusercontent.com/18472048/40565918-3f8f6f90-6023-11e8-9b3a-ef788896f1b8.png)

I will look also and see if I can find anything wrong...

**Comment by mcianfrocco** [comment]
Hi @monaw - I just ran a test job and it completed successfully using the GPU nodes on Comet. That said, I don't see where the SU charge is on the comet-gpu account. 

However, I DO see CPU usage in the tasks page. For me, it says 14.

I just submitted a ticket to XSEDE help to see what I'm missing.
Mike

**Comment by mcianfrocco** [comment]
Yes - I did a test and it worked. I don't know why nothing shows up between March and June, but I did a test on June 14 and it see it on the allocation usage page. I also emailed with Mahidar and he confirmed that it worked.

**Comment by monaw** [comment]
I checked with the CIPRES team and they had to make some changes to the code to add the comet gpu.  Here is what he said:

> Hi Mona,
> 
> There are changes made in multiple places: 
> 
> 1. New table in DB, ‘resource_conversion’ 
> 2. New col added onto job_stats table which is a FK points to PK of resource_conversion.ID  
> 3. Modifications in usage.py to utilize the above 2 changes in DB. 
> 4. Changes made in Tool.getPredictedSus(Properties) method. 
> 
> Here is the break-down: 
> 
> The new table, resource_conversion, serves as a reference table with ID, RESOURCE, and CONVERSION.  All resources except ‘comet-gpu’ have CONVERSION = 1, and ‘comet-gpu’ has CONVERSION = 14. 
> 
> When the usage.py is called to update the job_stats table, it checks to see if the resource is ‘comet-gpu’ or other, and populates the job_stats.RESRC_CONVRTN_ID col accordingly if it is NULL (it might have been populated by Java class explained below).  When we need to calculate the total SU usages, it multiplies one of the SUs (SU_PREDICTED, SU_COMPUTED, SU_CHARGED, or SU_OVERRIDE) value with the resource_conversion.CONVERSION value to get correct representation of CPU usage. 
> 
> 
> When a job (or task) is created, job_stats.SU_PREDICTED col must be populated. The modifications here are: 
> 
> a) Get the ‘gpu’ property from scheduler.conf where values of gpu can be 0, 1, 2, 4, or not defined. 
> b) Calculate the ‘totalCores’ based on ‘gpu’ value ->  totalCores = 1 if gpu = null | 0  (OR)  totalCores = gpu
> c) Calculate the chargeFactor based on ‘gpu’ value ->  chargeFactor = 1.0 if gpu = null | 0  (OR)  chargeFactor = 1.5 if gpu = 1|2|4. 
> d) Calculate the coresPerNode based on ‘gpu’ value -> coresPerNode = ToolResource.getCoresPerNode() if gpu = null | 0, (OR)  coresPerNodes = 1 
> e) Calculate the finalTotalCores = nodes * coresPerNode * totalCores
> f) SU_PREDICTED = runHours * finalTotalCores * chargeFactor 
> g) Round it to 1 if it is less than 1 
> 
> For item d),  coresPerNode is ignored (set to 1) if gpu = 1|2|4, but it is respected if ‘gpu’ is not defined or 0. 
> 
> Hope this helps, happy to talk on the phone to explain to you in detail.  
> 
> Thanks,
> 
> --
> Tony

**Comment by monaw** [comment]
@mcianfrocco - since our code branched from the CIPRES code, we cannot simply update our code to get this new feature.  what would you like to do?  it will take some time to implement this for cosmic2...

**Comment by mcianfrocco** [comment]
Hi @monaw - right now, where is the CPU usage read into the database? Could we just over write it after calculating the conversion from GPU to CPU?
