### ISSUE TITLE
Size of directory on Globus transfer page is not size of directory 

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#72]
Perhaps this is a globus problem, but the directory sizes listed on the Transfer page are incorrect. Instead they just list the size of the actual directory name, which is like 3 bytes

**Comment by monaw** [comment]
@mcianfrocco - the size should now reflect the size of the star file which is more accurate since the list shows the star filename.  Ok?

**Comment by monaw** [comment]
@mcianfrocco - currently the Byte column should reflect the size of the directory that contains the respective star file.  Please confirm that this is working with a real data set, thanks!
