### ISSUE TITLE
Migrate gateway URL to new domain name 

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#75]
Not listing name here, but we need to move the URL from the current one to a name based on the cosmic-cryoem.org domain name.

**Comment by monaw** [comment]
Hi Mike, did you get a response from SDSC about how to do this?

**Comment by mcianfrocco** [comment]
Hi Mona - yes, I just forwarded you the email.

**Comment by monaw** [comment]
Hi Mike, before I follow up with Jeff Makey @ SDSC, few questions for you...

1. To clarify, you want the gateway URL to show https://cosmic-cryoem.org/portal/... right?
2. Do you have a way to manage your cosmic-cryoem.org domain name?
3. Who is currently hosting the cosmic-cryoem.org domain?

**Comment by mcianfrocco** [comment]
Hi Mona: 

1. yes, that URL looks good to me. 
2 & 3. cosmic-cryoem.org is hosted via GoDaddy using Wordpress.

Mike

**Comment by monaw** [comment]
hi @mcianfrocco - revisiting this issue...i'm wondering if you are planning to use our current server as production eventually or setup a new production when ready; if former, we can proceed with this task; if latter, then you probably want the URL above to go to that new instance right?

**Comment by mcianfrocco** [comment]
hi @monaw - I'd like the production server to be https://cosmic-cryoem.org/portal whereas our developmental version could be the current URL.

Thanks,
Mike

**Comment by monaw** [comment]
after meeting discussion, we will likely keep our current server as staging/testing and setup a new port or VM for production

**Comment by monaw** [comment]
just wanted to added that per our meeting on 2/15/19, we will keep our current server as production and setup new VM for staging
