### ISSUE TITLE
How to stop users from submitting/uploading/using gateway?

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#77]

**Comment by monaw** [comment]
there is a script, userCanSubmit, which can turn on and off job submission for a single user or all users; unfortunately there is a runtime problem with the java:
```
java -cp sdk*depend* -Dlog4j.configuration=sdk_log4j.xml org.ngbw.utils.UserCanSubmit
java: No match.
```
checking with Mark to see what's wrong...

**Comment by monaw** [comment]
@mcianfrocco - ok, not sure what happened but the script is working now.  I just ran it to disable my account from submitting jobs and it worked:

```
cosmic2 (19) % ./userCanSubmit
java.lang.Exception: usage: UserCanSubmit username [boolean]
cosmic2 (20) % ./userCanSubmit mona false
Task submission disabled for user mona
```
and this is what I see when I try to submit a job in the gateway:

![submit disabled](https://user-images.githubusercontent.com/18472048/32750752-7d54cd5e-c878-11e7-9abd-03d1cae6da35.png)

What do you think?

**Comment by mcianfrocco** [comment]
Looks good - where did you put that script on the gateway?

**Comment by monaw** [comment]
It is in /projects/cosmic2/gateway/scripts.  By the way, your should have an environment variable set to that location (SDK_VERSIONS=/projects/cosmic2/gateway/scripts)

**Comment by monaw** [comment]
@mcianfrocco - FYI, this won't stop the user from transferring files to the gateway.  Do you still want that feature?

**Comment by mcianfrocco** [comment]
Right - yes I'd like that feature too, just in case (!).

**Comment by monaw** [comment]
Ok, I will start a new issue for that and we can keep this one closed with the notes above
