### ISSUE TITLE
*.star file processing (was "When creating new uploaded Globus data entry, only look 1 level deep for *.star file" )

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#78]

**Comment by monaw** [comment]
Done.  Testing and working.

**Comment by monaw** [comment]
@mcianfrocco - can you refresh my memory on what where the *.star file will be found in the directory the user transfers with Globus?

What do you want the system to do in the following cases:

1. No *.star file in the top-level transferred directory?
2. Multiple *.star files in subdirectories of the transferred directory?

**Comment by mcianfrocco** [comment]
Hi Mona - I'd like to 'ingest' every .star file found within the directory selected for upload via Globus. 

That means if there is a directory such as this: 

DataFiles/

That has these files present: 

select1.star
select2.star
select3.star
Micrographs/  [<---- directory with actual image data in it]
README.txt
tmpfile.txt

I'd like the whole directory move up via Globus and then ingest each of the star files, so that the Globus page would look like: 

DataFiles/select1.star
DataFiles/select2.star
DataFiles/select3.star

Is that possible?

**Comment by monaw** [comment]
Yes it is possible.

Just to clarify, so if there are star files inside the Micrographs/ subdirectory (include any nested subdirectories), they should ALL be listed in the data page as separate entries right?

**Comment by mcianfrocco** [comment]
Hi mona - for the subdirectory (e.g. Micrographs), I do not want any of those files listed. I just want the star files listed in the first level of the uploaded directory.

**Comment by mcianfrocco** [comment]
Hi @monaw - just realized that there is one more use case to consider: 

There are many times where there is a specify filetype located two directories into a project, but, at least in this case, there is a specific name. 

So, I'd like to keep the functionalities shown above that you've already included (thanks!), and then now add this: 

Add all files as data objects if they are named 'particles.star' and located two directories into a given folder. 

For instance, if a directory looks like this: 

Extract/
Extract/job001/particles.star
Extract/job003/particles.star
Extract/job005/newtest.star

I'd like these two added into the data entry page: 
Extract/job001/particles.star
Extract/job003/particles.star

Sorry for the headache!

**Comment by monaw** [comment]
@mcianfrocco - now that we've changed the size to the directory, if there are multiple *.star files in the top-level directory, they would all have the same directory size which means the user storage total would be wrong...it would be too high.  What would you like to do about this?

**Comment by mcianfrocco** [comment]
I think this is OK - an overestimate is good enough for now. Long term we will have to deal with this specifically. We just need to finish things : )

**Comment by monaw** [comment]
need issue #93 resolved before able to continue...

**Comment by monaw** [comment]
@mcianfrocco - questions regarding the particles.star 2 directories down...for the following combined case:

data/data1.star
data/data2.star
data/particles.star
data/job001/job1.star
data/job001/particles.star
data/job002/Micrographs/particles.star
data/job003/job3.star

Are these the files you want listed and ignore all others?

data/data1.star
data/data2.star
data/particles.star
data/job001/particles.star

**Comment by mcianfrocco** [comment]
Yes - looks goods !

**Comment by monaw** [comment]
sorry, not actually done...that was just a question (:

**Comment by monaw** [comment]
ok, it is now working (:

here is the upload directory content:

cosmic2 (87) % pwd
/projects/cosmic2/gateway/globus_transfers/mona
cosmic2 (88) % ls -ltR test3e
test3e:
total 15
drwxrwxr-x 2 513948 cosmic2  3 Mar 13 17:15 job3/
drwxrwxr-x 2 513948 cosmic2  4 Mar 13 17:15 job1/
-rw-r--r-- 1 513948 cosmic2  6 Mar 13 17:15 data2.star
-rw-r--r-- 1 513948 cosmic2  6 Mar 13 17:15 data1.star
-rw-r--r-- 1 513948 cosmic2 10 Mar 13 17:15 particles.star
drwxrwxr-x 3 513948 cosmic2  3 Mar 13 17:15 job2/

test3e/job3:
total 5
-rw-r--r-- 1 513948 cosmic2 5 Mar 13 17:15 job3.star

test3e/job1:
total 9
-rw-r--r-- 1 513948 cosmic2  5 Mar 13 17:15 job1.star
-rw-r--r-- 1 513948 cosmic2 10 Mar 13 17:15 particles.star

test3e/job2:
total 1
drwxrwxr-x 2 513948 cosmic2 3 Mar 13 17:15 Micrographs/

test3e/job2/Micrographs:
total 5
-rw-r--r-- 1 513948 cosmic2 10 Mar 13 17:15 particles.star

and here is the resulting file listing:

![screen shot 2018-03-13 at 5 16 31 pm](https://user-images.githubusercontent.com/18472048/37376700-d3e1a714-26e2-11e8-9c90-b7010aa82e7a.png)

Please confirm that it is behaving as you wanted, thanks!

**Comment by monaw** [comment]
by the way, the Bytes column above shows the size of the directory that contains the respective *.star file...so it is possible that a nested subdirectory which contains particles.star will be double counted in the user's filesystem storage count

**Comment by monaw** [comment]
@mcianfrocco - not sure if you received notification of this issue's update?

**Comment by mcianfrocco** [comment]
hi mona - sorry i saw this but forgot to respond!  that's ok for double counting at this point. we can return to this later if this is an issue.

**Comment by monaw** [comment]
@mcianfrocco - if your testing shows any problem, feel free to reopen this issue, thanks.
