### ISSUE TITLE
Move tools' output directory to advanced with default 

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#79]

**Comment by monaw** [comment]
@mcianfrocco - ok, I've moved the output directory to advanced parameters section for all 3 tools.  The value defaults to "output" and is the first parameter in the advanced section.

![screen shot 2017-11-13 at 3 05 03 pm](https://user-images.githubusercontent.com/18472048/32754255-f15debfc-c884-11e7-9ce1-5f5b47630614.png)

Let me know if you want any other changes or you can close this issue if you are satisfied

**Comment by mcianfrocco** [comment]
Looks good !

**Comment by mcianfrocco** [comment]
Actually - I want to remove this option altogether : ) This will make handling output files much easier.

**Comment by monaw** [comment]
ok, i've removed this parameter from all 3 tools.

need to test that the job submission and processing still works...

**Comment by monaw** [comment]
job submission and processing seems to be still working (: 

what is the output directory name going to be?  you sure you don't want the user to be able to specify this?

**Comment by mcianfrocco** [comment]
Yes still working! 

I am automatically naming the outputs and putting it back into the user globus directory. This is standard for the 'normal' RELION workflow, so this will be familiar to many users. For now, I think this is easier than users having to decide - this gives them a systematic name.

**Comment by mcianfrocco** [comment]
When I log in, I see this: 

![errror](https://user-images.githubusercontent.com/1464469/37378618-506bdcaa-2706-11e8-95b1-cf4e6fc97ee6.png)

But, after clicking 'Home' the error goes away and things are displayed correctly.

**Comment by monaw** [comment]
@mcianfrocco - i'm closing this issue and opening a new one for your login error
