### ISSUE TITLE
Setup Google Analytics for the gateway

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#80]

**Comment by monaw** [comment]
@mcianfrocco - do you want to setup the Google Analytics account for this gateway or should I?  If you set it up, can you also include sciencegateways@gmail.com as an user who can read and analyze the data?

**Comment by mcianfrocco** [comment]
Hi Mona,

I can try to add it, but what URL do I use? cosmic-cryoem.org? Or a different one?

**Comment by monaw** [comment]
Ah, hmm...we might need to wait on this until we get the portal URL correct...

**Comment by monaw** [comment]
#75

**Comment by monaw** [comment]
Marlon would like to get our google analytics info for our production server, not staging.

**Comment by mcianfrocco** [comment]
Set up & add Marlon to view information

**Comment by monaw** [comment]
Add sciencegateways@gmail.com to be able to access and analytics; Marlon will be able to use that account to check, thanks!

**Comment by monaw** [comment]
Hi @mcianfrocco, did you get a chance to add the SGCI email to the Google Analytics?  Marlon says he doesn't have access yet...

**Comment by mcianfrocco** [comment]
Hmm - thought I did. I will check
