### ISSUE TITLE
Remove button from Task summary page: 'Save to current folder'

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#81]
This appears to be a holdover from CIPRES. 

@monaw - perhaps you could walk me through how to remove this button?

![ex1](https://user-images.githubusercontent.com/1464469/32761443-56601d18-c8c1-11e7-9e77-8244998dfadc.png)

**Comment by monaw** [comment]
Done
