### ISSUE TITLE
How to stop users from uploading/transferring to the gateway?

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#82]

**Comment by monaw** [comment]
@mcianfrocco - do you feel issue #53 is good enough?  it doesn't stop the user from transferring to the gateway but will prevent user from submitting jobs.  if you would still like a mechanism to stop the user from transferring to the gateway if they exceed the storage limit, might be able to disable the sync button on the Globus page when the target endpoint is the COSMIC2 gateway storage.  would you like that solution?

**Comment by mcianfrocco** [comment]
Hi @monaw - as long as we have the ability to turn off their submission this should be good enough. 

I forget is there a way to turn off a specific user's access to the gateway? As in, perhaps someone is abusing this and we want to stop them. 

I'm wondering about the extreme scenario where a user just max's out our storage and we can't stop them. If we could at least turn off their account that would be enough.

**Comment by mcianfrocco** [comment]
Otherwise #53 is good enough for all normal users who don't try to abuse the system : )

**Comment by monaw** [comment]
@mcianfrocco - issue #53 is a mechanism to stop job submission when their storage size exceeds a limit but it will not prevent them from uploading more data; currently there is no mechanism to do that but can be added if desired.

Ok to close this issue since you say above this is good enough for now?

**Comment by mcianfrocco** [comment]
yes - OK to close
