### ISSUE TITLE
Remove relion maximum runtime from task options

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#83]
Users should not have this choice - gateway will decide.

**Comment by monaw** [comment]
Done, removed from all 3 tools:

![screen shot 2018-02-15 at 11 48 16 am](https://user-images.githubusercontent.com/18472048/36277618-3dc698b2-1246-11e8-925f-e918df0d71a2.png)

![screen shot 2018-02-15 at 11 48 35 am](https://user-images.githubusercontent.com/18472048/36277638-48c341de-1246-11e8-8305-bbd879f69c73.png)

![screen shot 2018-02-15 at 11 48 48 am](https://user-images.githubusercontent.com/18472048/36277648-4ef72cbe-1246-11e8-932f-17772b5b398f.png)

Need to check and make sure job submission is still working...
