### ISSUE TITLE
No choice for globus upload for empty directories

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#85]
It appears that we have lost the button for a Globus upload for empty directories? I was just testing a new directory, and these options only let me use the web browser upload option: 

<img width="489" alt="globusmissing" src="https://user-images.githubusercontent.com/1464469/33511337-07a531c0-d6e7-11e7-9a6b-9d875f8ec869.png">

**Comment by monaw** [comment]
Added button for Globus upload and changed text on current (browser) button:

![screen shot 2017-12-04 at 5 50 59 pm](https://user-images.githubusercontent.com/18472048/33586090-64229f28-d91c-11e7-986a-295a0f4ddc60.png)
