### ISSUE TITLE
Runtime error in all-gateway.log

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#86]
Noticed the following error in the logs during Mike's testing...

> Dec 05 2017 17:48:21 [xec-18] DEBUG -           SFTPFileHandler:79     | Configured host: comet
> Dec 05 2017 17:48:27 [exec-9] DEBUG -           SFTPFileHandler:79     | Configured host: comet
> Dec 05 2017 17:48:55 [exec-9] DEBUG -           SFTPFileHandler:79     | Configured host: comet
> Dec 05 2017 17:49:04 [exec-9] DEBUG -           SFTPFileHandler:79     | Configured host: comet
> Dec 05 2017 17:49:08 [xec-20] DEBUG -           SFTPFileHandler:79     | Configured host: comet
> Dec 05 2017 17:49:08 [xec-20] ERROR - ultDispatcherErrorHandler:42     | Exception occurred during processing request: org.apache.jasper.JasperException: java.lang.IllegalStateException: getOutputStream() has already been called for this response
> java.lang.RuntimeException: org.apache.jasper.JasperException: java.lang.IllegalStateException: getOutputStream() has already been called for this response
> 	at com.opensymphony.sitemesh.webapp.decorator.BaseWebAppDecorator.render(BaseWebAppDecorator.java:39)
> 	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:84)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
> 	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:603)
> 	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:542)
> 	at org.apache.struts2.dispatcher.ServletDispatcherResult.doExecute(ServletDispatcherResult.java:166)
> 	at org.apache.struts2.dispatcher.StrutsResultSupport.execute(StrutsResultSupport.java:191)
> 	at com.opensymphony.xwork2.DefaultActionInvocation.executeResult(DefaultActionInvocation.java:372)
> 	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:276)
> 	at org.apache.struts2.impl.StrutsActionProxy.execute(StrutsActionProxy.java:54)
> 	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:575)
> 	at org.apache.struts2.dispatcher.ng.ExecuteOperations.executeAction(ExecuteOperations.java:81)
> 	at org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:99)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
> 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442)
> 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082)
> 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623)
> 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:748)
>

**Comment by monaw** [comment]
just checked all-gateway.log.* and no such error since 12/7/2017 but perhaps because we have not been submitting jobs; recheck after transfer & job submission are completely working again...

**Comment by mcianfrocco** [comment]
Perhaps this is related to the security certificate, but I am still getting gateway errors on the transfer page.

**Comment by monaw** [comment]
ok, just checked the logs again and looks like no such error since 2/4/18.

@mcianfrocco - are you still seeing gateway errors on the transfer page?  if not, can you repeat your testing and I can check the logs again to see if the above error shows up or not...

**Comment by mcianfrocco** [comment]
Hi mona - 

I got this error again where as soon as I select a file for upload I get the standard gateway error. 

![errror](https://user-images.githubusercontent.com/1464469/37378991-f02bc72c-2707-11e8-87d1-34294da33f39.png)

Perhaps this is due to something weird with my account? Perhaps we could wipe my previous accounts to start fresh? 

To test this, I just logged in using a new account that I did NOT link to my previous account (using a gmail account) and I did not get this problem. 

However, there was a hiccup it seems after I initiated a globus transfer: 

![cometstorageerror](https://user-images.githubusercontent.com/1464469/37379032-1c1ff5b0-2708-11e8-859e-f0b2a13b09a7.png)

This went away after refreshing the page. The file was transferred successfully and ingested successfully, but just wanted to post this.

Mike

**Comment by mcianfrocco** [comment]
Hi @cdesyoun - I'm getting a globus error for all of my accounts. Do you think you could take a look at the logs?

**Comment by cdesyoun** [comment]
Hi @mcianfrocco, I looked into the all-gateway.log file. It seems to me your endpoints for "Life Sciences Institute - CryoEM Endpoint" and "LSI-CryoEM" are not authenticated with globus properly or not existed.
When searching these endpoints in globus, I got these info below:
1. "There are no endpoints that match “Life Sciences Institute - CryoEM Endpoint”.
2. Found two endpoints for cosmic2 below:
Display Name: U Michigan Life Sciences Institute 
UUID: 3ccf082a-6b2b-11e8-92ba-0a6d4e044368 
Display Name: cryoem-workshop 
UUID:ffbd304c-699a-11e8-92a0-0a6d4e044368 

UUIDs for endpoints in the log file are different with these above endpoints registered in globus.
I think you need to clean up your endpoint list and register it again.

Thanks,
Choonhan Youn

<pre>
Jul 10 2018 11:24:14 [exec-4] INFO  -            TransferAction:285    | SRC Name: Life Sciences Institute - CryoEM Endpoint::SOURCE
Jul 10 2018 11:24:14 [exec-4] INFO  -            TransferAction:286    | SRC Display Name: Life Sciences Institute - CryoEM Endpoint
Jul 10 2018 11:24:14 [exec-4] INFO  -            TransferAction:289    | Source Endpoint activation....
Jul 10 2018 11:24:14 [exec-4] ERROR - ceptionMappingInterceptor:42     | null
PermissionDenied(403 Forbidden) on request 'Ue80lmRbh' resource '/endpoint/7eaac9ce-a5c4-11e6-9ace-22000a1e3b52': Not authorized for that endpoint
	at org.globusonline.transfer.JSONTransferAPIClient.constructAPIError(JSONTransferAPIClient.java:164)
	at org.globusonline.transfer.BaseTransferAPIClient.request(BaseTransferAPIClient.java:202)
	at org.globusonline.transfer.JSONTransferAPIClient.requestResult(JSONTransferAPIClient.java:242)
</pre>
<pre>
Jul 10 2018 11:24:50 [exec-4] INFO  -            TransferAction:285    | SRC Name: LSI-CryoEM::SOURCE
Jul 10 2018 11:24:50 [exec-4] INFO  -            TransferAction:286    | SRC Display Name: LSI-CryoEM
Jul 10 2018 11:24:50 [exec-4] INFO  -            TransferAction:289    | Source Endpoint activation....
Jul 10 2018 11:24:51 [exec-4] ERROR - ceptionMappingInterceptor:42     | null
EndpointDeleted(404 Not Found) on request 'WGtEIINcy' resource '/endpoint/8e34d8a8-a682-11e6-9ad2-22000a1e3b52': Endpoint '8e34d8a8-a682-11
e6-9ad2-22000a1e3b52' has been deleted
	at org.globusonline.transfer.JSONTransferAPIClient.constructAPIError(JSONTransferAPIClient.java:164)
	at org.globusonline.transfer.BaseTransferAPIClient.request(BaseTransferAPIClient.java:202)
	at org.globusonline.transfer.JSONTransferAPIClient.requestResult(JSONTransferAPIClient.java:242)
</pre>

**Comment by mcianfrocco** [comment]
Hi @cdesyoun ,

Thanks for looking into this. Yes, those endpoints changed, but I'm surprised it would cause a major failure of the globus interface for end-users on our gateway. 

How do I remove these? And, how do we prevent this from causing problems to users in the future?

**Comment by monaw** [comment]
@cdesyoun - thanks for debugging that!  Can you take this opportunity to properly catch the error and display a better error to the user and in the logs, including maybe notifying the gateway admin if problem persists?

**Comment by cdesyoun** [comment]
Hi @mcianfrocco , hmm, in those cases, I may need to look into globus endpoint activation service in more details. As one quick solution, please log into the glous, https://www.globus.org. and then click "Bookmarks" link in the "Manage Data". It shows you your registered endpoints including the path.
Please remove all and then go to cosmic2 gateway and register your new endpoints again.

Thanks,
Choonhan Youn

**Comment by mcianfrocco** [comment]
Ok - thanks @cdesyoun ! I'll try this for now.

**Comment by mcianfrocco** [comment]
Hi @cdesyoun - I've just gotten around to deleting these managed bookmarks, but I am still having a problem: 

After trying to click on 'Upload data via Globus' I get the standard error from the gateway saying: 

> An error has occurred. If you continue to have difficulty using the site, please report the error to us.

Any ideas on what is happening on the backend? If I got to the Transfers page, I can see past globus transfers from my account.

Thanks,
Mike

**Comment by cdesyoun** [comment]
Hi @mcianfrocco , I looked into the log file. I saw lots of errors related to globus endpoints below:
<pre>
EndpointDeleted(404 Not Found) on request 'JftUeEhWG' resource '/endpoint/8e34d8a8-a682-11e6-9ad2-22000a1e3b52': Endpoint '8e34d8a8-a682-11
e6-9ad2-22000a1e3b52' has been deleted
PermissionDenied(403 Forbidden) on request 'yqF9Pj07j' resource '/endpoint/7eaac9ce-a5c4-11e6-9ace-22000a1e3b52': Not authorized for that e
ndpoint
</pre>

Are you sure you did delete all of bookmarked endpoints on your globus account?
If so, for debugging your problem, can we share your all of globus accounts?
Please email me about that.

Thanks,
Choonhan Youn

**Comment by cdesyoun** [comment]
Hi @mcianfrocco , I looked into the database. You have 5 different accounts below:
<pre>
MySQL [cosmic2_sg]> select * from oauth_profile where first_name='Michael';
+------------+--------------------------------+------------+--------------------------------------+------------------------+------------+---------+-------------------------------------------+-------------------+
| PROFILE_ID | EMAIL                          | FIRST_NAME | IDENTITY_ID                          | INSTITUTION            | LAST_NAME  | USER_ID | USERNAME                                  | LINK_USERNAME     |
+------------+--------------------------------+------------+--------------------------------------+------------------------+------------+---------+-------------------------------------------+-------------------+
|          2 | mcianfro@umich.edu             | Michael    | 37982d7c-0751-11e6-8ffd-478bd27b5d6d | University of Michigan | Cianfrocco |       3 | 046f34cb53bd98610154360b8be90cf2@ucsd.edu | michaelc          |
|          5 | micianfrocco@ucsd.edu          | Michael    | ded25a31-a5dd-4aae-b710-db16ac7d6da4 |                        | Cianfrocco |       3 | micianfr@xsede.org                        | michaelc          |
|          8 | mcianfro@umich.edu             | Michael    | 9f00a359-0c3e-428e-8dca-83a04612615f | University of Michigan | Cianfrocco |       3 | mcianfro@umich.edu                        | michaelc          |
|          9 | michael.a.cianfrocco@gmail.com | Michael    | 065cbc44-9e1e-472a-b787-6f134d5d8d4e |                        | Cianfrocco |      60 | michael.a.cianfrocco@gmail.com            | micianfrocco      |
|         12 | cmanfro@gmail.com              | Michael    | a07a6798-7f15-456c-abe2-1cf46e76d0bb |                        | Cianfrocco |      69 | cmanfro@gmail.com                         | cmanfro@gmail.com |
+------------+--------------------------------+------------+--------------------------------------+------------------------+------------+---------+-------------------------------------------+-------------------+
5 rows in set (0.01 sec)
</pre>
It means that you select five different identity providers provided by the globus auth. 
First of all, I think we need to clean up your accounts in the database to avoid the confusion.

Thanks,
Choonhan Youn

**Comment by mcianfrocco** [comment]
Ah - never mind, yes, there were other bookmarks in my other linked accounts. Thank you @cdesyoun for pointing this out!
