### ISSUE TITLE
Multi-page data listing not working!

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#87]
If data list page is multiple pages, first page is displayed on all pages or page listing is not updating?

**Comment by kenneth59715** [comment]
In DataManager.java, commenting out the refreshFolderDataTabs(); line makes the
next page contents show up.  
    public List<? extends FolderItem> getCurrentAllDataTab()
    {   
        logger.debug("in getCurrentAllDataTab()");
            logger.debug("before refreshFolderDataTabs(), getFolderDataTabs().getCurrentTabContents().size(): " + getFolderDataTabs().getCurrentTabContents().size() );
        //logger.debug ( "MONA: entered getCurrentAllDataTab()" );
        // added this or else new Globus transfer files won't show up in UI
        // without logout/login
        refreshFolderDataTabs();

**Comment by monaw** [comment]
@kenneth59715 - I just did some testing and looks like the Globus transfers don't need that refreshFolderDataTabs() call so I commented it out but the multipage data listing still doesn't work.  it works for you?

**Comment by kenneth59715** [comment]
Mona,

 The refreshFolderDataTabs() line is not commented out in DataManager.java:

  // Added by Mona to also show new Globus directory data.  Function
    // modelled after the above getCurrentDataTab()
    //TODO: add sort functionality to user interface
    public List<? extends FolderItem> getCurrentAllDataTab()
    {
        //logger.debug ( "MONA: entered getCurrentAllDataTab()" );
        // added this or else new Globus transfer files won't show up in UI
        // without logout/login
        refreshFolderDataTabs();

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
Decided on 1/3/18 to allow users to list _everything_ - we shall see how it goes!

**Comment by kenneth59715** [comment]
in dataList.jsp, hardcoded number of records shown to 2000.

**Comment by monaw** [comment]
@kenneth59715 - is it possible to not have a limit?

**Comment by kenneth59715** [comment]
I think we decided to just set it to a large fixed limit for the beta.
It's possible to have multipage work again, but getCurrentAllDataTab() needs to not do refreshFolderDataTabs().  Some other way to do that refresh needs to be developed.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by monaw** [comment]
@kenneth59715 - i'm seeing weird behavior for one of my data folder listing...the page says there are 198 entries but it is showing only 20 even though the record listing size selector says 2000:

![screen shot 2019-01-17 at 6 08 43 pm](https://user-images.githubusercontent.com/18472048/51361069-2082ed00-1a83-11e9-954d-812a54a21a51.png)

**Comment by kenneth59715** [comment]
Not sure what would be doing that.  I'm seeing 68 data items in mine.  I'm not seeing any
new globus data items, though.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
Okay, I might try using my repo with code from last week to see what
happens.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
