### ISSUE TITLE
Deleting data does not work

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#89]
Data delete button on task page doesn't work - just throws generic error message. When page is refreshed, there is nothing removed from data list.

**Comment by monaw** [comment]
Runtime error in log:

```
Jan 16 2018 15:13:12 [exec-5] ERROR - ceptionMappingInterceptor:42     | 1
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.ngbw.web.actions.DataManager.deleteSelectedDataItems(DataManager.java:1642)
	at org.ngbw.web.actions.DataManager.deleteSelected(DataManager.java:271)
	at org.ngbw.web.actions.DataManager.cancel(DataManager.java:230)
```

**Comment by monaw** [comment]
Ok, fixed and tested successfully.
@mcianfrocco - please confirm that it works you too

**Comment by mcianfrocco** [comment]
Hi @monaw - I just tried to delete some existing data and I got an error: 

An error has occurred. If you continue to have difficulty using the site, please report the error to us.

**Comment by monaw** [comment]
@mcianfrocco - oops!  sheesh...sorry wrong issue!  this issue is not fixed...

**Comment by mcianfrocco** [comment]
: )

**Comment by monaw** [comment]
@mcianfrocco - looks like there is problem with delete on both.data listing page and task listing page.  I've fixed the one on the data listing page and still working on the one in the task listing page.  Question though, if the user selects a *.star file to delete, should the gateway delete just the *.star file or the entire directory?
![screen shot 2018-01-18 at 2 33 51 pm](https://user-images.githubusercontent.com/18472048/35125891-1e1cbe7a-fc60-11e7-9ff1-df2c1cab5ea6.png)

**Comment by monaw** [comment]
@mcianfrocco - ok, task delete is now working; feel free to test both and please answer question above about delete *.star data files, thanks!
![screen shot 2018-01-18 at 3 18 45 pm](https://user-images.githubusercontent.com/18472048/35126691-6265efea-fc63-11e7-9e17-c0ea2833a69d.png)

**Comment by mcianfrocco** [comment]
Great! Thanks Mona. 

Yes - let's make it so that if a user deletes the star file, it deletes the entire directory. 

Mike

**Comment by mcianfrocco** [comment]
Hi Mona, I just tried to delete some data but it gave me this error (see attached).

And, you'll also see that it is not returning a directory size for me. 

![error](https://user-images.githubusercontent.com/1464469/35131928-be5f16f4-fc96-11e7-836b-b4c4f9c1e554.png)

**Comment by monaw** [comment]
@mcianfrocco - since it is possible for a Globus transferred directory to be listed in the "Data" folder in more than one of the user's folders, how would you like to handle the case if the user deletes it in one Data folder?  Here are some possible options (#3 will take more work than #1 or #2 which is about equal amount of work):

1. The gateway should NOT delete the actual directory, only delete the entry listed in that specific Data folder, and notify user that the actual directory is still used/useable in other folders?
2. The gateway should go ahead and delete the actual directory and all entries from all Data folders and notify user
3. The gateway should let the user choose whether to delete from only current Data folder or from all Data folders?

**Comment by mcianfrocco** [comment]
Hi Mona - I'd like to do option 2 as I want to give users the ability to 'clean up' their data storage folder. 

Thanks!
mike

**Comment by monaw** [comment]
@mcianfrocco - you sure about that?  when user is deleting data from one folder, i don't think they expect the data to be deleted from another...

**Comment by mcianfrocco** [comment]
Or, what if we have a delete all data button? I guess I want to give users the choice to remove their own data, so this delete all data is what they would press when they are finished?

**Comment by monaw** [comment]
I think that's a related but separate issue/function.  i'm asking about the "Delete Selected" button at the bottom of the "All Data" page.  It is possible that user will have the same data listed in several of their folders, should deleting one place the data is listed delete it from all their other folders...if you have time, perhaps we can do a hangout to discuss?  I'm on now...

**Comment by monaw** [comment]
@mcianfrocco - ok, deleting directory is now working; please confirm...

**Comment by monaw** [comment]
@mcianfrocco - ok, I've updated the pre-delete warning dialog text:

![screen shot 2018-01-31 at 3 38 18 pm](https://user-images.githubusercontent.com/18472048/35653424-08464afc-069d-11e8-9ca6-6e5f1ec9fa91.png)

let me know what changes you would like...

**Comment by mcianfrocco** [comment]
Hi Mona, 

It worked at deleting some data, but then when I re-uploaded the same data to delete it again, I'm now getting an error saying that "1 data item could not be deleted." Is it a database issue? Or?

**Comment by monaw** [comment]
From the logs, I see these were successfully deleted:

1. mcianfro/cosmic/Particles/shiny_2sets.star
2. mcianfro/cosmic/Particles/shiny_2sets_testDup.star

and these failed during delete:

1. Particles_for_cosmic2/
2. Particles/

Were the ones you are able to delete older folders from previous and the folders you are not able to delete newer?  Were they transferred with the previous file browser or recently updated file browser?

**Comment by mcianfrocco** [comment]
For Particles_for_cosmic2, I created a new folder on the cosmic portal and then uploaded the files. Now, I can't delete it.

**Comment by monaw** [comment]
@mcianfrocco - hmm, I just did an upload and was able to deleted.  i think the issue may be the directory permission...let's do the following tests:

1. delete your Extract_cosmic/
2. delete your relion20_tutorial/

Let me know the results, thanks!

**Comment by mcianfrocco** [comment]
Yes - works now. Must've been some weird hiccup b/c of the user permission. 

Thanks!

**Comment by monaw** [comment]
terrific!  i noticed the directory permission looked odd and had the SDSC admin change the permission.

so you can delete Particles_for_cosmic2/ also now?

**Comment by mcianfrocco** [comment]
Well - I just deleted everything manually from the cosmic2 user account and then I uploaded / deleted.

**Comment by mcianfrocco** [comment]
Just tried to delete data:

<img width="1169" alt="delete_issue" src="https://user-images.githubusercontent.com/1464469/52085456-8d61b100-2572-11e9-82be-a2ec24dc7580.png">

Deleting does not work

**Comment by monaw** [comment]
@mcianfrocco - awhile back we added a warning about deleting star files:

> Are you sure?  If you delete these items, you will not be able to recover them. Also, if you are deleting a STAR file data directory and it appears in multiple folders, ALL entries will be deleted as well!

This was before we prepended the user folder to the files.  Since now this doesn't apply, I'm going to remove the second sentence.

**Comment by monaw** [comment]
@mcianfrocco - just to confirm...if the user selects a star file to delete, the gateway should delete the ENTIRE Globus transfer directory containing that star file right?

**Comment by mcianfrocco** [comment]
Yes and the warning message looks good.

**Comment by monaw** [comment]
@mcianfrocco - is this new user warning/confirmation dialog box message ok?

> Are you sure?  If you delete these items, you will not be able to recover them. Warning, deleting a star file will remove the entire directory!

**Comment by monaw** [comment]
@mcianfrocco - also, if the user has several star files in the same data directory (for example see attached image)

![Screen Shot 2019-03-28 at 3 52 46 PM](https://user-images.githubusercontent.com/18472048/55198041-abfab780-5171-11e9-98a4-7c0ee9c245ca.png)

then if they delete one, all will be deleted since they are in the same parent directory.

**Comment by mcianfrocco** [comment]
That's ok - you also tell them this in the warning message.

**Comment by monaw** [comment]
add call to re-calculate user data size displayed

**Comment by monaw** [comment]
ok I just finished testing delete and it is working and the display for the user storage upload updated correctly (:

**Comment by mcianfrocco** [comment]
Awesome @monaw ! I tested it and it also worked for me. Closing this now : )

**Comment by monaw** [comment]
i found a problem...the delete removed the data entries from the database which had the exact same path/name even though the data is in different folders!

**Comment by monaw** [comment]
ok, i've fixed the problem...now deleting a star file is restricted to the user folder so exact same path & file in other user folder will not be deleted
