### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#92]
Runtime error in the logs:

> [...]
> Jan 29 2018 12:57:29 [xec-14] ERROR - ceptionMappingInterceptor:42     | null
> AuthenticationFailed(401 Unauthorized) on request 'ZG5bOfuVA' resource '/endpoint_search': Token is not active
> 	at org.globusonline.transfer.JSONTransferAPIClient.constructAPIError(JSONTransferAPIClient.java:164)
> 	at org.globusonline.transfer.BaseTransferAPIClient.request(BaseTransferAPIClient.java:202)
> 	at org.globusonline.transfer.JSONTransferAPIClient.requestResult(JSONTransferAPIClient.java:242)
> 	at org.globusonline.transfer.JSONTransferAPIClient.getResult(JSONTransferAPIClient.java:190)
> 	at edu.sdsc.globusauth.action.EndpointListAction.my_endpoint_search_transfer(EndpointListAction.java:243)
> 	at edu.sdsc.globusauth.action.TransferAction.transfer(TransferAction.java:94)
> [...]

**Comment by cdesyoun** [comment]
I guess the different session may cause this problem.
I updated my code below:

In "EndpointListJSONAction.java"
From: 
public class EndpointListJSONAction extends Basic Action {
To:
public class EndpointListJSONAction extends NgbwSupport {

In  "DynamicTreeAction,java"
From:
public class DynamicTreeAction extends BasicAction {
To:
public class DynamicTreeAction extends NgbwSupport {

**Comment by cdesyoun** [comment]
Deployed it.

**Comment by monaw** [comment]
Thanks Choonhan! I don't see this error in the log anymore (:
