### ISSUE TITLE
Runtime error about invalid proxy

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#93]
Generic runtime error is seeing in gateway:

>An error has occurred. If you continue to have difficulty using the site, please report the error to us.

And these errors in the log:

> [...]
> Feb 13 2018 15:03:49 [exec-2] INFO  -            TransferAction:671    | 0 type: delegate_proxy
> Feb 13 2018 15:03:49 [exec-2] INFO  -            TransferAction:672    | 0 name: public_key
> Feb 13 2018 15:03:49 [exec-2] ERROR - ceptionMappingInterceptor:42     | null
> BadRequest(400 Bad Request) on request 'dbg9nUUd1' resource '/endpoint/de463f97-6d04-11e5-ba46-22000b92c6ec/activate': invalid proxy: is expired
> 	at org.globusonline.transfer.JSONTransferAPIClient.constructAPIError(JSONTransferAPIClient.java:164)
> 	at org.globusonline.transfer.BaseTransferAPIClient.request(BaseTransferAPIClient.java:202)
> 	at org.globusonline.transfer.JSONTransferAPIClient.requestResult(JSONTransferAPIClient.java:242)
> 	at org.globusonline.transfer.JSONTransferAPIClient.postResult(JSONTransferAPIClient.java:204)
> 	at edu.sdsc.globusauth.action.TransferAction.delegateProxyActivation(TransferAction.java:652)
> 	at edu.sdsc.globusauth.action.TransferAction.transfer(TransferAction.java:280)
> [...]

**Comment by monaw** [comment]
@cdesyoun - I tried logging out and back in but that didn't resolve this error...

**Comment by mcianfrocco** [comment]
I'm also seeing this error

**Comment by cdesyoun** [comment]
@monaw , @mcianfrocco , the user certificate for the community account was expired.
<pre>
Validity
            Not Before: Jan  9 00:00:00 2017 GMT
            Not After : Feb  8 23:59:59 2018 GMT
</pre>

I sent email to XSEDE security people who handles it.
Once I get it, I will update it.

**Comment by monaw** [comment]
@cdesyoun - Ah thanks!  So this is a yearly renewal?  Can they make it for longer than 1-year?

Is it possible to add some code to catch this condition and send email to the portal admin instead of throwing the generic error message to the user?

**Comment by cdesyoun** [comment]
@monaw , well, adding the check routine is very inefficient. Further more, the validation date is more than a year. For this, I don't think we need to check it periodically. 

As my understanding, usually the validity date for the certificate is a year or around because of security reasons.

**Comment by monaw** [comment]
@cdesyoun - how did you get/check the expiration date for the community account?

By checking, I don't mean via a Globus API call but internal to our code...I just did a quick look through the code and it looks like you already have a catch in JSONTransferAPIClient.java, line 171 to catch this error.  Because this is an error that requires the admin's immediate attention since the user will not know what's wrong or what to do, it would be good if our code can email the admin...I believe there is code to email admin already...let me know if you cannot find it.

If I've misunderstood what you mean by "check routine is inefficient", please elaborate, thanks.

**Comment by cdesyoun** [comment]
In that case, in order to get the valid certificate from XSEDE, I guess it will take some time.
You can use the cron job to notify the admin a month earlier before the certificate is going to expire.

**Comment by monaw** [comment]
@cdesyoun - ok, so how to check when the community account certificate will expire?

**Comment by cdesyoun** [comment]
New certificate was issued. 
I updated it. When testing the gateway, it went well.

I asked xsede to get the certificate that has more longer time, more than a year. But, the IGTF certs are only valid for a year.  That's a requirement defined by the IGTF.

The validity time for the certificate is as follows:
Expires :      03/17/2019 23:59 GMT

Since we know the expiration date for the certificate, we can set up the date, for example, 02/17/2019 to notify admin using the cron job on cosmic2.sdsc.edu.

**Comment by monaw** [comment]
@cdesyoun - terrific thanks!  please document this process step:

1. how to check certificate status
2. how to make the request to update certificate (email to help@xsede.org or open an issue in the portal?)
3. how to put the new certificate in place

**Comment by cdesyoun** [comment]
Number 2 option is best. When expiring it, let someone send an email to XSEDE help desk.

**Comment by monaw** [comment]
@cdesyoun - thanks; how about #3...put new certificate in place?  Is there anything "we" need to do or does XSEDE take care of that as well?

**Comment by cdesyoun** [comment]
When requesting the certificate to XSEDE, XSEDE will send you the steps including links via an email. After downloading it, you will see several X509 public key certificates inside it. You can use the last one. The certificate location is in the property file, "portal/src/main/resources/oauth_consumer.properties".  You can update the public key in this file, "user_cred.pem".
