### ISSUE TITLE
Globus interface allows listing of community account home directory!

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#94]
User is able to list the community account's home directory on comet:

![screen shot 2018-03-07 at 3 48 32 pm](https://user-images.githubusercontent.com/18472048/37124871-0c51a84c-221f-11e8-8e24-51a093bdb111.png)

**Comment by monaw** [comment]
Ah ok thanks Choonhan!  I deleted that endpoint and when I tried to add it back, it gives a notification which is great!

![screen shot 2018-04-09 at 10 22 04 am](https://user-images.githubusercontent.com/18472048/38512461-0c9aa62a-3be0-11e8-8943-aa271f8aba00.png)

Can you make a minor change to the text..."XSEDE Comet is managed by the COSMIC2 gateway and in order to protect all users' data, it cannot be added as your endpoint.  Sorry."  unless Mike has another preference..

**Comment by monaw** [comment]
One other thing, is it possible to change the name of the endpoint from "XSEDE Comet" to "COSMIC2 Science Gateway Storage"?

**Comment by monaw** [comment]
@cdesyoun - it loos like the security check above to not allow user to add XSEDE Comet endpoint and list the content is done in javascript.  Does the backend function also check?  javascript is not the best place to do security checks since it is server-side and potentially can be modified by the user...

**Comment by cdesyoun** [comment]
This is done.
