### ISSUE TITLE
end point error message

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#97]
the system use to display a user-friendly endpoint name but seems to have lost that ability:

![screen shot 2018-03-26 at 9 52 32 am](https://user-images.githubusercontent.com/18472048/37920379-8f05384c-30db-11e8-91d8-2fc7c9348c89.png)

please display user-friendly endpoint name for all error messages

**Comment by cdesyoun** [comment]
I improved the error message using the display name for the endpoint.
